/**
 * A drift guard, in the spirit of docsContextTemplate.test.ts.
 *
 * SERENE_PUB_SECURE_COOKIES existed in the code for a long time while being
 * documented in exactly zero places — not .env.example, not the docs, not
 * HOSTING.md. XFF_DEPTH, BODY_SIZE_LIMIT and PORT_HEADER were in the same
 * position. Nothing catches that except a test, because every individual
 * change looks complete on its own.
 *
 * This asserts the direction that actually matters: anything advertised in
 * .env.example must be explained in the reference documentation.
 */
import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import { describe, expect, it } from "vitest"

const root = resolve(__dirname, "../../../..")
const read = (p: string) => readFileSync(resolve(root, p), "utf8")

/** SCREAMING_SNAKE names on an assignment line, commented out or not. */
function declaredVars(text: string): string[] {
	const names = new Set<string>()
	for (const line of text.split("\n")) {
		const match = line.match(/^#?\s*([A-Z][A-Z0-9_]{3,})=/)
		if (match) names.add(match[1])
	}
	return [...names].sort()
}

describe("environment variable documentation", () => {
	it("documents every variable offered in .env.example", () => {
		const docs = read("docs/environment-variables.md")
		const missing = declaredVars(read(".env.example")).filter(
			(name) => !docs.includes(name)
		)
		expect(
			missing,
			`these are in .env.example but absent from docs/environment-variables.md: ${missing.join(", ")}`
		).toEqual([])
	})

	it("documents every variable offered in the shipped desktop .env.example", () => {
		// This file is what users actually find next to the executable. It was
		// previously generated by a heredoc inside release.yml and had drifted
		// to four variables, none of them hosting-related.
		const docs = read("docs/environment-variables.md")
		const missing = declaredVars(read("dist-assets/.env.example")).filter(
			(name) => !docs.includes(name)
		)
		expect(
			missing,
			`these are in dist-assets/.env.example but absent from docs/environment-variables.md: ${missing.join(", ")}`
		).toEqual([])
	})

	it("keeps the canonical settings in both .env.example files", () => {
		// The two files serve different audiences and will never be identical,
		// but a hosting setting missing from the desktop one is invisible to
		// the users most likely to need it.
		const dist = read("dist-assets/.env.example")
		for (const name of ["PUBLIC_URL", "TRUSTED_PROXIES"]) {
			expect(
				dist,
				`${name} missing from the shipped .env.example`
			).toContain(name)
		}
	})
})
