import { sql } from "drizzle-orm"
import { rawRows } from "../rawRows"
import { pruneUnshippedLedgerRows } from "../migrationLedgerRepair"
import type { DataUpgradeContext } from "./index"

/**
 * 0.5.3 → 0.6.0, part A: the attic stash.
 *
 * `0095_schema_0_6_0` is generated by drizzle-kit, and a generated migration
 * cannot carry 0.5.3 rows across: it adds NOT NULL columns with no default to
 * populated tables, drops columns whose values 0.6 still needs, and repoints
 * foreign keys at tables that start empty. So before its SQL runs, every
 * table in `public` is copied verbatim into the `attic_0_5_3` schema and then
 * emptied. The DDL meets only empty tables, which is exactly the fresh-install
 * case it is generated for.
 *
 * The rows go back at boot, in the 0.6 shape, from the `attic` startup task —
 * not here: that ETL needs seeded rows (specs, presets, templates, the
 * definition registry) and app code, neither of which exists inside a
 * migration transaction. The attic's presence is the one "upgrade pending"
 * signal; the boot path drops the schema once the restore and the config
 * wiring have both succeeded.
 *
 * Runs only on an existing database (`skipUpgrades` on a fresh install) and
 * only while `0095_schema_0_6_0` is pending, which is true of a 0.5.3
 * database and nothing else. Atomic with that migration: a crash anywhere in
 * here leaves the 0.5.3 database exactly as it was.
 *
 * Raw SQL only, discovered from the catalog rather than listed, so no table
 * can be forgotten and nothing here ages with `schema.ts`.
 */

export const ATTIC_SCHEMA = "attic_0_5_3"
export const ATTIC_MANIFEST = "__manifest"
/**
 * The ledger rows the upgrade pruned (hash, created_at), kept for the attic
 * restore's upgrade note. Present only when at least one row was pruned.
 */
export const ATTIC_LEDGER_PRUNED = "__ledger_pruned"

const ident = (name: string) => `"${name.replace(/"/g, '""')}"`

async function publicTables(tx: MigrationTx): Promise<string[]> {
	const rows = rawRows<{ table_name: string }>(
		await tx.execute(
			sql.raw(`SELECT table_name FROM information_schema.tables
				WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
				ORDER BY table_name`)
		)
	)
	return rows.map((r) => r.table_name)
}

export async function before(tx: MigrationTx): Promise<void> {
	const tables = await publicTables(tx)
	const attic = ident(ATTIC_SCHEMA)

	// No IF NOT EXISTS: an attic already present here means two upgrades are
	// interleaving, and the only safe answer is to stop.
	await tx.execute(sql.raw(`CREATE SCHEMA ${attic}`))
	await tx.execute(
		sql.raw(`CREATE TABLE ${attic}.${ident(ATTIC_MANIFEST)}
			(table_name text PRIMARY KEY, row_count bigint NOT NULL)`)
	)

	for (const t of tables) {
		await tx.execute(
			sql.raw(`CREATE TABLE ${attic}.${ident(t)} AS TABLE public.${ident(t)}`)
		)
		await tx.execute(
			sql.raw(`INSERT INTO ${attic}.${ident(ATTIC_MANIFEST)} (table_name, row_count)
				SELECT '${t.replace(/'/g, "''")}', count(*) FROM ${attic}.${ident(t)}`)
		)
	}

	if (tables.length) {
		await tx.execute(
			sql.raw(
				`TRUNCATE ${tables.map((t) => `public.${ident(t)}`).join(", ")} CASCADE`
			)
		)
	}
}

export async function run(
	tx: MigrationTx,
	ctx: DataUpgradeContext
): Promise<void> {
	const rows = rawRows<{ n: number }>(
		await tx.execute(
			sql.raw(`SELECT count(*)::int AS n FROM information_schema.schemata
				WHERE schema_name = '${ATTIC_SCHEMA}'`)
		)
	)
	if (!rows.length || Number(rows[0].n) !== 1) {
		throw new Error(
			`0.6.0 upgrade: schema "${ATTIC_SCHEMA}" is missing after 0095_schema_0_6_0; ` +
				`the 0.5.3 rows were not stashed.`
		)
	}

	// The ledger rows 0.5.x's old and dev chains left, matching no file this
	// build ships, are pruned here and only here (owner ruling 2026-10-02):
	// this transaction is entered once, by a 0.5.3 database, and never by a
	// fresh pub or one already on 0.6. What went is kept in the attic for the
	// restore's upgrade note, so the person is told.
	const pruned = await pruneUnshippedLedgerRows(tx, ctx.shippedHashes)
	if (pruned.length) {
		const table = `${ident(ATTIC_SCHEMA)}.${ident(ATTIC_LEDGER_PRUNED)}`
		await tx.execute(
			sql.raw(`CREATE TABLE ${table} (hash text NOT NULL, created_at bigint)`)
		)
		for (let i = 0; i < pruned.length; i += 500)
			await tx.execute(
				sql`INSERT INTO ${sql.raw(table)} (hash, created_at) VALUES ${sql.join(
					pruned
						.slice(i, i + 500)
						.map((r) => sql`(${r.hash}, ${Number.isFinite(r.createdAt) ? r.createdAt : null})`),
					sql`, `
				)}`
			)
	}
}
