/**
 * The 0166 data upgrade, against a database rebuilt into 0.5's shape.
 *
 * This is the highest-risk piece of 28: it is the one step that touches a real
 * user's existing files, it runs exactly once, and a partial result is worse
 * than a failure. So the legacy columns and tables that 0167 dropped are
 * recreated here by hand, populated the way a 0.5 install would have them —
 * including the references that are already broken in the wild — and the
 * upgrade is run against that.
 *
 * **`media` is one of those hand-built tables now.** 0182 split it into `files`
 * + `variants` and dropped it, so it is no longer in `schema.ts` — but the
 * upgrade still runs, anchored to 0166 and inside 0166's own transaction, where
 * `media` is exactly the table it writes to (0182 then drops the result, which
 * is the no-backfill ruling stated in that migration). An upgrade is judged
 * against the schema at its anchor, not today's, which is why it speaks raw SQL
 * in the first place — and why the read-backs below do too.
 */
import { beforeAll, afterAll, describe, expect, test, vi } from "vitest"
import fs from "fs/promises"
import os from "os"
import path from "path"
import { sql, type SQL } from "drizzle-orm"
import { PNG } from "pngjs"
import * as schema from "$lib/server/db/schema"
import type { TestDb } from "$lib/server/utils/testDb"

// beforeAll builds the DB and the legacy fixture tree — also real work, not
// covered by testTimeout, so hookTimeout needs the same 60s budget.
vi.setConfig({ testTimeout: 60_000, hookTimeout: 60_000 })

let db: TestDb
let dataDir: string

vi.mock("$lib/server/db", async () => {
	const { createTestDb } = await import("$lib/server/utils/testDb")
	return { db: await createTestDb() }
})

function png(seed: number): Buffer {
	const p = new PNG({ width: 2, height: 2 })
	for (let i = 0; i < p.data.length; i += 4) {
		p.data[i] = seed
		p.data[i + 1] = 10
		p.data[i + 2] = 20
		p.data[i + 3] = 255
	}
	return PNG.sync.write(p)
}

/** Write a file where a 0.5 install would have put it, and return the
 *  `/images/...` URL that install would have stored in the database. */
async function legacyFile(rel: string, bytes: Buffer): Promise<string> {
	const abs = path.join(dataDir, rel)
	await fs.mkdir(path.dirname(abs), { recursive: true })
	await fs.writeFile(abs, bytes)
	return `/images/${rel}`
}

/** A row of the hand-built `media` table — 0166's shape, and therefore
 *  snake_case: there is no Drizzle model to read it back through. */
interface LegacyMedia {
	id: number
	user_id: number
	character_id: number | null
	persona_id: number | null
	session_id: number | null
	hash: string
	mime: string
	kind: string
	path: string
	position: number
	variant: string | null
}

async function mediaRows(
	where: SQL = sql`TRUE`,
	orderBy: SQL = sql`id`
): Promise<LegacyMedia[]> {
	const res: any = await db.execute(
		sql`SELECT * FROM media WHERE ${where} ORDER BY ${orderBy}`
	)
	return (res.rows ?? res) as LegacyMedia[]
}

let userId: number
let charId: number
let personaId: number
let sessionId: number

beforeAll(async () => {
	dataDir = await fs.mkdtemp(path.join(os.tmpdir(), "serene-pub-0166-int-"))
	process.env.SERENE_PUB_DATA_DIR = dataDir
	const dbModule = await import("$lib/server/db")
	db = dbModule.db as unknown as TestDb

	const { createTestUser } = await import("$lib/server/utils/testDb")
	const user = await createTestUser(db, "upgrade-user")
	userId = user.id

	// Rebuild 0.5's shape on top of the current schema — plus `media` itself,
	// which 0182 dropped. Copied from 0166's own DDL rather than derived from
	// anything current: the upgrade writes twelve of these columns by name, and
	// a table that merely resembles 0166's would let a column rename pass here
	// and fail on a real user's database.
	await db.execute(sql`CREATE TABLE media (
		id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		user_id integer NOT NULL,
		character_id integer,
		persona_id integer,
		session_id integer,
		message_id integer,
		visibility text NOT NULL DEFAULT 'scoped',
		hash text NOT NULL,
		mime text NOT NULL,
		bytes integer NOT NULL,
		kind text NOT NULL,
		path text NOT NULL,
		filename text,
		width integer,
		height integer,
		parent_media_id integer,
		variant text,
		position integer NOT NULL DEFAULT 0,
		created_at timestamp NOT NULL DEFAULT now())`)
	// Per-user, with `variant` in the key so an original and a derivative could
	// share a hash. It is what the session-asset branch's ON CONFLICT relies on.
	await db.execute(
		sql`CREATE UNIQUE INDEX media_user_hash_variant_unique
			ON media (user_id, hash, variant)`
	)
	await db.execute(sql`ALTER TABLE characters ADD COLUMN avatar text`)
	await db.execute(sql`ALTER TABLE personas ADD COLUMN avatar text`)
	await db.execute(sql`CREATE TABLE character_gallery_images (
		id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		character_id integer NOT NULL,
		path text NOT NULL,
		position integer NOT NULL DEFAULT 0)`)
	await db.execute(sql`CREATE TABLE persona_gallery_images (
		id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		persona_id integer NOT NULL,
		path text NOT NULL,
		position integer NOT NULL DEFAULT 0)`)
	await db.execute(sql`CREATE TABLE session_assets (
		id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		session_id integer NOT NULL,
		hash text NOT NULL,
		mime text NOT NULL,
		bytes integer NOT NULL,
		path text NOT NULL,
		created_by integer)`)

	const [character] = await db
		.insert(schema.characters)
		.values({ userId, name: "Legacy Char", description: "" })
		.returning()
	charId = character.id
	const [persona] = await db
		.insert(schema.personas)
		.values({
			userId,
			name: "Legacy Persona",
			description: "",
			isDefault: false
		})
		.returning()
	personaId = persona.id
	const [session] = await db
		.insert(schema.sessions)
		.values({ userId, name: "Legacy Session", isGroup: false })
		.returning()
	sessionId = session.id

	// --- Character: an avatar plus two gallery images, one of which IS the
	// avatar (0.5 stored the same path in both places).
	const avatarUrl = await legacyFile(
		`data/users/${userId}/characters/${charId}/avatar-aaaa.png`,
		png(1)
	)
	const galleryUrl = await legacyFile(
		`data/users/${userId}/characters/${charId}/gal-bbbb.png`,
		png(2)
	)
	await db.execute(
		sql`UPDATE characters SET avatar = ${avatarUrl} WHERE id = ${charId}`
	)
	await db.execute(sql`INSERT INTO character_gallery_images
		(character_id, path, position) VALUES
		(${charId}, ${avatarUrl}, 0), (${charId}, ${galleryUrl}, 1)`)

	// --- Persona: a bare filename, the pre-URL format. Already broken in the
	// running app — nothing serves it — so the upgrade must drop it, not
	// invent a location for it.
	await db.execute(
		sql`UPDATE personas SET avatar = 'user-default.png' WHERE id = ${personaId}`
	)
	await db.execute(sql`INSERT INTO persona_gallery_images
		(persona_id, path, position) VALUES (${personaId}, ${await legacyFile(
			`data/users/${userId}/personas/${personaId}/p-cccc.png`,
			png(3)
		)}, 0)`)

	// --- A shipped default background (must be left alone) and an uploaded
	// one (must move).
	const bgUrl = await legacyFile(
		`data/users/${userId}/backgrounds/bg-dddd.png`,
		png(4)
	)
	// createTestUser does not create a settings row, so make the one a real
	// install would have.
	await db
		.insert(schema.userSettings)
		.values({ userId, backgroundImagePath: bgUrl })

	// --- A session asset, already hash-addressed under the old tree.
	const assetBytes = png(5)
	const assetHash = "deadbeef"
	await legacyFile(`session_assets/${sessionId}/${assetHash}`, assetBytes)
	await db.execute(sql`INSERT INTO session_assets
		(session_id, hash, mime, bytes, path, created_by) VALUES
		(${sessionId}, ${assetHash}, 'image/png', ${assetBytes.byteLength},
		 ${`session_assets/${sessionId}/${assetHash}`}, ${userId})`)

	// --- A gallery row whose file was deleted out from under it. 0.5 let this
	// happen routinely (listCharacterGallery reconciled it away at read time).
	await db.execute(sql`INSERT INTO character_gallery_images
		(character_id, path, position) VALUES
		(${charId}, ${`/images/data/users/${userId}/characters/${charId}/gone.png`}, 2)`)

	const { run } = await import("./0166_media")
	await run(db)
})

afterAll(async () => {
	await fs.rm(dataDir, { recursive: true, force: true })
})

describe("0166 data upgrade", () => {
	test("the character's avatar becomes a media row and a pointer", async () => {
		const row = await db.query.characters.findFirst({
			where: (c, { eq }) => eq(c.id, charId)
		})
		expect(row?.avatarMediaId).toBeTruthy()
		const [media] = await mediaRows(sql`id = ${row!.avatarMediaId!}`)
		expect(media.character_id).toBe(charId)
		expect(media.kind).toBe("image")
		expect(media.mime).toBe("image/png")
	})

	test("the avatar and the gallery row that shared its path dedupe to one row", async () => {
		const rows = await mediaRows(sql`character_id = ${charId}`)
		// avatar+gallery[0] were the same file, gallery[1] is distinct, and
		// gallery[2]'s file is missing — so two rows, not four.
		expect(rows).toHaveLength(2)
		const hashes = new Set(rows.map((r) => r.hash))
		expect(hashes.size).toBe(2)
	})

	test("gallery ordering survives", async () => {
		const rows = await mediaRows(
			sql`character_id = ${charId}`,
			sql`position`
		)
		expect(rows.map((r) => r.position)).toEqual([0, 1])
	})

	test("an unresolvable persona avatar is dropped, not invented", async () => {
		const row = await db.query.personas.findFirst({
			where: (p, { eq }) => eq(p.id, personaId)
		})
		expect(row?.avatarMediaId).toBeNull()
		// Its gallery image did resolve, so the persona is not empty — the
		// drop is surgical, not a bail-out.
		expect(await mediaRows(sql`persona_id = ${personaId}`)).toHaveLength(1)
	})

	test("an uploaded background moves and clears the static column", async () => {
		const settings = await db.query.userSettings.findFirst({
			where: (u, { eq }) => eq(u.userId, userId)
		})
		expect(settings?.backgroundMediaId).toBeTruthy()
		expect(settings?.backgroundImagePath).toBeNull()
		const [media] = await mediaRows(
			sql`id = ${settings!.backgroundMediaId!}`
		)
		// No entity parent — it lands in the user-level bucket and stays
		// owner-only.
		expect(media.character_id).toBeNull()
		expect(media.path).toContain(
			path.join("data", "users", String(userId), "backgrounds")
		)
	})

	test("a session asset moves into the shared layout", async () => {
		const rows = await mediaRows(sql`session_id = ${sessionId}`)
		expect(rows).toHaveLength(1)
		expect(rows[0].path).toContain(
			path.join(
				"data",
				"users",
				String(userId),
				"sessions",
				String(sessionId)
			)
		)
		expect(rows[0].hash).toBe("deadbeef")
	})

	test("every migrated file exists at its new path, and the source tree is untouched", async () => {
		const rows = await mediaRows()
		expect(rows.length).toBeGreaterThan(0)
		for (const row of rows) {
			await fs.access(path.join(dataDir, row.path))
		}
		// Copies, not moves: a rolled-back transaction has to leave the
		// original files in place.
		await fs.access(
			path.join(
				dataDir,
				`data/users/${userId}/characters/${charId}/avatar-aaaa.png`
			)
		)
	})

	test("no thumbnails are generated inside the upgrade", async () => {
		const thumbs = await mediaRows(sql`variant IS NOT NULL`)
		// Encoding thousands of images inside a migration transaction is how
		// an upgrade appears to hang. 0182 went further and made every
		// derivation lazy, so what backfills these is now the first request
		// that wants one rather than a boot pass.
		expect(thumbs).toHaveLength(0)
	})
})
