/**
 * The data-upgrade runner (see ./index.ts).
 *
 * Exercised against a purpose-built migration folder rather than the app's real
 * one, so the ordering guarantees can be asserted with a schema small enough to
 * reason about: 0000 creates a table, 0001 adds a column, the upgrade fills it
 * in JS, 0002 makes it NOT NULL. If the upgrade does not land between 0001 and
 * 0002, 0002 fails — which makes the ordering claim self-checking.
 */
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest"
import fs from "fs"
import os from "os"
import path from "path"
import { PGlite } from "@electric-sql/pglite"
import { drizzle } from "drizzle-orm/pglite"
import { runMigrationsWithUpgrades, type DataUpgrade } from "./index"

let folder: string
let client: PGlite
let db: any

function writeJournal(entries: { tag: string; when: number }[]) {
	fs.mkdirSync(path.join(folder, "meta"), { recursive: true })
	fs.writeFileSync(
		path.join(folder, "meta/_journal.json"),
		JSON.stringify({
			version: "7",
			dialect: "postgresql",
			entries: entries.map((e, idx) => ({
				idx,
				version: "7",
				when: e.when,
				tag: e.tag,
				breakpoints: true
			}))
		})
	)
}

beforeEach(async () => {
	folder = fs.mkdtempSync(path.join(os.tmpdir(), "sp-dataupgrade-"))
	fs.writeFileSync(
		path.join(folder, "0000_first.sql"),
		`CREATE TABLE "widget" ("id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "legacy" text);`
	)
	fs.writeFileSync(
		path.join(folder, "0001_add_col.sql"),
		`ALTER TABLE "widget" ADD COLUMN "computed" text;`
	)
	fs.writeFileSync(
		path.join(folder, "0002_contract.sql"),
		`ALTER TABLE "widget" ALTER COLUMN "computed" SET NOT NULL;`
	)
	writeJournal([
		{ tag: "0000_first", when: 1000 },
		{ tag: "0001_add_col", when: 1001 },
		{ tag: "0002_contract", when: 1002 }
	])
	client = new PGlite()
	db = drizzle(client)
}, 60_000)

afterEach(() => {
	fs.rmSync(folder, { recursive: true, force: true })
})

/** Put the database in the state an older install would be in. */
async function seedOldInstall() {
	await client.query(`CREATE SCHEMA IF NOT EXISTS drizzle`)
	await client.query(`CREATE TABLE IF NOT EXISTS drizzle.__drizzle_migrations
		(id SERIAL PRIMARY KEY, hash text NOT NULL, created_at bigint)`)
	await client.query(`CREATE TABLE "widget"
		("id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "legacy" text)`)
	await client.query(
		`INSERT INTO drizzle.__drizzle_migrations (hash, created_at) VALUES ('seed', 1000)`
	)
	await client.query(`INSERT INTO widget (legacy) VALUES ('abc'), ('defgh')`)
}

function upgrade(run: (tx: any) => Promise<void>): DataUpgrade[] {
	return [{ afterMigration: "0001_add_col", load: async () => ({ run }) }]
}

const fillComputed = async (tx: any) => {
	const res = await tx.execute(`SELECT id, legacy FROM widget`)
	for (const r of res.rows ?? res) {
		await tx.execute(
			`UPDATE widget SET computed = '${String(r.legacy).length}' WHERE id = ${r.id}`
		)
	}
}

async function isNullable(): Promise<boolean> {
	const r =
		await client.query(`SELECT is_nullable FROM information_schema.columns
		WHERE table_name='widget' AND column_name='computed'`)
	return (r.rows[0] as any).is_nullable === "YES"
}

describe("ordering", () => {
	test("runs the upgrade between its anchor and the migration that follows", async () => {
		await seedOldInstall()
		const run = vi.fn(fillComputed)

		const res = await runMigrationsWithUpgrades(db, {
			migrationsFolder: folder,
			upgrades: upgrade(run)
		})

		expect(res.upgradesRun).toEqual(["0001_add_col"])
		// 0002 sets NOT NULL — it could only have succeeded if the upgrade
		// populated the column first.
		expect(await isNullable()).toBe(false)
		const rows = await client.query(
			`SELECT computed FROM widget ORDER BY id`
		)
		expect(rows.rows.map((r: any) => r.computed)).toEqual(["3", "5"])
	})

	test("does not re-run on a second boot", async () => {
		await seedOldInstall()
		const run = vi.fn(fillComputed)
		const upgrades = upgrade(run)

		await runMigrationsWithUpgrades(db, {
			migrationsFolder: folder,
			upgrades
		})
		const second = await runMigrationsWithUpgrades(db, {
			migrationsFolder: folder,
			upgrades
		})

		expect(run).toHaveBeenCalledTimes(1)
		expect(second.upgradesRun).toEqual([])
	})
})

describe("fresh installs", () => {
	test("skipUpgrades applies every migration and runs no upgrade", async () => {
		const run = vi.fn(fillComputed)

		// A new database has no legacy content to transform; the upgrade would
		// be a no-op at best and a misfire at worst.
		const res = await runMigrationsWithUpgrades(db, {
			migrationsFolder: folder,
			upgrades: upgrade(run),
			skipUpgrades: true
		})

		expect(run).not.toHaveBeenCalled()
		expect(res.upgradesRun).toEqual([])
		expect(await isNullable()).toBe(false)
	})
})

describe("atomicity", () => {
	test("a failing upgrade rolls back its anchor migration, and the retry succeeds", async () => {
		await seedOldInstall()
		let attempts = 0
		const flaky = async (tx: any) => {
			attempts++
			await fillComputed(tx)
			if (attempts === 1) throw new Error("simulated crash mid-upgrade")
		}

		await expect(
			runMigrationsWithUpgrades(db, {
				migrationsFolder: folder,
				upgrades: upgrade(flaky)
			})
		).rejects.toThrow(/simulated crash/)

		// The anchor migration must NOT have survived on its own — otherwise
		// the next boot would see it applied and never retry the upgrade,
		// losing the transformation permanently.
		const cols =
			await client.query(`SELECT column_name FROM information_schema.columns
			WHERE table_name='widget' AND column_name='computed'`)
		expect(cols.rows).toHaveLength(0)

		const res = await runMigrationsWithUpgrades(db, {
			migrationsFolder: folder,
			upgrades: upgrade(fillComputed)
		})
		expect(res.upgradesRun).toEqual(["0001_add_col"])
		expect(await isNullable()).toBe(false)
	})
})

describe("misconfiguration is loud", () => {
	test("rejects a journal whose timestamps are not strictly increasing", async () => {
		writeJournal([
			{ tag: "0000_first", when: 1000 },
			{ tag: "0001_add_col", when: 1000 },
			{ tag: "0002_contract", when: 1002 }
		])
		// Drizzle compares against the newest applied row only, so a
		// non-increasing `when` makes that migration silently never apply.
		await expect(
			runMigrationsWithUpgrades(db, { migrationsFolder: folder })
		).rejects.toThrow(/out of order/i)
	})

	test("rejects an upgrade anchored to a migration that does not exist", async () => {
		await expect(
			runMigrationsWithUpgrades(db, {
				migrationsFolder: folder,
				upgrades: [
					{
						afterMigration: "0009_typo",
						load: async () => ({ run: async () => {} })
					}
				]
			})
		).rejects.toThrow(/not in the migration journal/i)
	})
})
