CREATE TABLE "chat_guests" (
	"chat_id" integer NOT NULL,
	"user_id" integer NOT NULL,
	"is_player" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"show_home_page_banner" boolean DEFAULT true,
	"enable_easy_persona_creation" boolean DEFAULT true NOT NULL,
	"enable_easy_character_creation" boolean DEFAULT true NOT NULL,
	"show_all_character_fields" boolean DEFAULT false NOT NULL,
	"created_at" date DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	"updated_at" date DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "tags" ADD COLUMN "user_id" integer;--> statement-breakpoint
-- Update existing tags to belong to user 1 (if user 1 exists)
UPDATE "tags" SET "user_id" = 1 WHERE "user_id" IS NULL AND EXISTS (SELECT 1 FROM "users" WHERE "id" = 1);--> statement-breakpoint
-- If no user 1 exists, we need to handle this case - for now, we'll create a default user
INSERT INTO "users" ("id", "username", "created_at", "updated_at") 
SELECT 1, 'admin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM "users" WHERE "id" = 1);--> statement-breakpoint
-- Update any remaining null user_ids to 1
UPDATE "tags" SET "user_id" = 1 WHERE "user_id" IS NULL;--> statement-breakpoint
-- Now we can safely add the NOT NULL constraint
ALTER TABLE "tags" ALTER COLUMN "user_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "is_admin" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "chat_guests" ADD CONSTRAINT "chat_guests_chat_id_chats_id_fk" FOREIGN KEY ("chat_id") REFERENCES "public"."chats"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_guests" ADD CONSTRAINT "chat_guests_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_settings" ADD CONSTRAINT "user_settings_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "chat_guests_pk" ON "chat_guests" USING btree ("chat_id","user_id");--> statement-breakpoint
ALTER TABLE "tags" ADD CONSTRAINT "tags_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;