CREATE TABLE "narrative_edges" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "narrative_edges_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"from_node_id" integer NOT NULL,
	"to_node_id" integer NOT NULL,
	"edge_type" text NOT NULL,
	"notes" text,
	"created_at" date DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "narrative_nodes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "narrative_nodes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lorebook_id" integer NOT NULL,
	"scene_id" integer,
	"node_type" text NOT NULL,
	"node_state" text DEFAULT 'active' NOT NULL,
	"content" text DEFAULT '' NOT NULL,
	"summary" text,
	"embedding" real[],
	"character_ids" json DEFAULT '[]'::json NOT NULL,
	"chat_id" integer,
	"pending_review" boolean DEFAULT false NOT NULL,
	"created_at" date DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	"updated_at" date DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scenes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scenes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"chat_id" integer NOT NULL,
	"lorebook_id" integer,
	"selected_message_ids" json DEFAULT '[]'::json NOT NULL,
	"summary" text,
	"embedding" real[],
	"graphed" boolean DEFAULT false NOT NULL,
	"created_at" date DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	"updated_at" date DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "character_lore_entries" ADD COLUMN "embedding" real[];--> statement-breakpoint
ALTER TABLE "characters" ADD COLUMN "embedding" real[];--> statement-breakpoint
ALTER TABLE "chat_messages" ADD COLUMN "embedding" real[];--> statement-breakpoint
ALTER TABLE "history_entries" ADD COLUMN "embedding" real[];--> statement-breakpoint
ALTER TABLE "personas" ADD COLUMN "embedding" real[];--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "vectorization_enabled" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "embedding_model_name" text;--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "embedding_model_dimensions" integer;--> statement-breakpoint
ALTER TABLE "world_lore_entries" ADD COLUMN "embedding" real[];--> statement-breakpoint
ALTER TABLE "narrative_edges" ADD CONSTRAINT "narrative_edges_from_node_id_narrative_nodes_id_fk" FOREIGN KEY ("from_node_id") REFERENCES "public"."narrative_nodes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "narrative_edges" ADD CONSTRAINT "narrative_edges_to_node_id_narrative_nodes_id_fk" FOREIGN KEY ("to_node_id") REFERENCES "public"."narrative_nodes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "narrative_nodes" ADD CONSTRAINT "narrative_nodes_lorebook_id_lorebooks_id_fk" FOREIGN KEY ("lorebook_id") REFERENCES "public"."lorebooks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "narrative_nodes" ADD CONSTRAINT "narrative_nodes_scene_id_scenes_id_fk" FOREIGN KEY ("scene_id") REFERENCES "public"."scenes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "narrative_nodes" ADD CONSTRAINT "narrative_nodes_chat_id_chats_id_fk" FOREIGN KEY ("chat_id") REFERENCES "public"."chats"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scenes" ADD CONSTRAINT "scenes_chat_id_chats_id_fk" FOREIGN KEY ("chat_id") REFERENCES "public"."chats"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scenes" ADD CONSTRAINT "scenes_lorebook_id_lorebooks_id_fk" FOREIGN KEY ("lorebook_id") REFERENCES "public"."lorebooks"("id") ON DELETE set null ON UPDATE no action;