CREATE TABLE "character_summarize_configs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "character_summarize_configs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"is_immutable" boolean DEFAULT false NOT NULL,
	"name" text NOT NULL,
	"batch_system_prompt" text NOT NULL,
	"synth_system_prompt" text NOT NULL,
	"name_system_prompt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scene_summarize_configs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scene_summarize_configs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"is_immutable" boolean DEFAULT false NOT NULL,
	"name" text NOT NULL,
	"batch_system_prompt" text NOT NULL,
	"synth_system_prompt" text NOT NULL,
	"name_system_prompt" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "world_summarize_configs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "world_summarize_configs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"is_immutable" boolean DEFAULT false NOT NULL,
	"name" text NOT NULL,
	"batch_system_prompt" text NOT NULL,
	"synth_system_prompt" text NOT NULL,
	"name_system_prompt" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "default_summarize_world_config_id" integer;--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "default_summarize_character_config_id" integer;--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "default_summarize_scene_config_id" integer;--> statement-breakpoint
ALTER TABLE "user_settings" ADD COLUMN "active_summarize_world_config_id" integer;--> statement-breakpoint
ALTER TABLE "user_settings" ADD COLUMN "active_summarize_character_config_id" integer;--> statement-breakpoint
ALTER TABLE "user_settings" ADD COLUMN "active_summarize_scene_config_id" integer;--> statement-breakpoint
ALTER TABLE "system_settings" ADD CONSTRAINT "system_settings_default_summarize_world_config_id_world_summarize_configs_id_fk" FOREIGN KEY ("default_summarize_world_config_id") REFERENCES "public"."world_summarize_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_settings" ADD CONSTRAINT "system_settings_default_summarize_character_config_id_character_summarize_configs_id_fk" FOREIGN KEY ("default_summarize_character_config_id") REFERENCES "public"."character_summarize_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_settings" ADD CONSTRAINT "system_settings_default_summarize_scene_config_id_scene_summarize_configs_id_fk" FOREIGN KEY ("default_summarize_scene_config_id") REFERENCES "public"."scene_summarize_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_settings" ADD CONSTRAINT "user_settings_active_summarize_world_config_id_world_summarize_configs_id_fk" FOREIGN KEY ("active_summarize_world_config_id") REFERENCES "public"."world_summarize_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_settings" ADD CONSTRAINT "user_settings_active_summarize_character_config_id_character_summarize_configs_id_fk" FOREIGN KEY ("active_summarize_character_config_id") REFERENCES "public"."character_summarize_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_settings" ADD CONSTRAINT "user_settings_active_summarize_scene_config_id_scene_summarize_configs_id_fk" FOREIGN KEY ("active_summarize_scene_config_id") REFERENCES "public"."scene_summarize_configs"("id") ON DELETE set null ON UPDATE no action;