CREATE TABLE "setup" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "setup_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"summarization_step_complete" boolean DEFAULT false NOT NULL,
	"rag_step_complete" boolean DEFAULT false NOT NULL,
	CONSTRAINT "setup_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
ALTER TABLE "setup" ADD CONSTRAINT "setup_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;