CREATE TABLE "graph_build_configs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "graph_build_configs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"is_immutable" boolean DEFAULT false NOT NULL,
	"name" text NOT NULL,
	"node_resolution_system_prompt" text DEFAULT '' NOT NULL,
	"pre_filter_system_prompt" text DEFAULT '' NOT NULL,
	"perspective_system_prompt" text DEFAULT '' NOT NULL,
	"node_resolution_connection_id" integer,
	"node_resolution_sampling_config_id" integer,
	"pre_filter_connection_id" integer,
	"pre_filter_sampling_config_id" integer,
	"perspective_connection_id" integer,
	"perspective_sampling_config_id" integer
);
--> statement-breakpoint
ALTER TABLE "user_settings" DROP CONSTRAINT "user_settings_active_connection_id_connections_id_fk";
--> statement-breakpoint
ALTER TABLE "user_settings" DROP CONSTRAINT "user_settings_active_sampling_id_sampling_configs_id_fk";
--> statement-breakpoint
ALTER TABLE "character_summarize_configs" ADD COLUMN "batch_connection_id" integer;--> statement-breakpoint
ALTER TABLE "character_summarize_configs" ADD COLUMN "batch_sampling_config_id" integer;--> statement-breakpoint
ALTER TABLE "character_summarize_configs" ADD COLUMN "synth_connection_id" integer;--> statement-breakpoint
ALTER TABLE "character_summarize_configs" ADD COLUMN "synth_sampling_config_id" integer;--> statement-breakpoint
ALTER TABLE "character_summarize_configs" ADD COLUMN "name_connection_id" integer;--> statement-breakpoint
ALTER TABLE "character_summarize_configs" ADD COLUMN "name_sampling_config_id" integer;--> statement-breakpoint
ALTER TABLE "chats" ADD COLUMN "connection_id" integer;--> statement-breakpoint
ALTER TABLE "chats" ADD COLUMN "sampling_config_id" integer;--> statement-breakpoint
ALTER TABLE "prompt_configs" ADD COLUMN "connection_id" integer;--> statement-breakpoint
ALTER TABLE "prompt_configs" ADD COLUMN "sampling_config_id" integer;--> statement-breakpoint
ALTER TABLE "scene_summarize_configs" ADD COLUMN "batch_connection_id" integer;--> statement-breakpoint
ALTER TABLE "scene_summarize_configs" ADD COLUMN "batch_sampling_config_id" integer;--> statement-breakpoint
ALTER TABLE "scene_summarize_configs" ADD COLUMN "synth_connection_id" integer;--> statement-breakpoint
ALTER TABLE "scene_summarize_configs" ADD COLUMN "synth_sampling_config_id" integer;--> statement-breakpoint
ALTER TABLE "scene_summarize_configs" ADD COLUMN "name_connection_id" integer;--> statement-breakpoint
ALTER TABLE "scene_summarize_configs" ADD COLUMN "name_sampling_config_id" integer;--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "default_graph_build_config_id" integer;--> statement-breakpoint
ALTER TABLE "world_summarize_configs" ADD COLUMN "batch_connection_id" integer;--> statement-breakpoint
ALTER TABLE "world_summarize_configs" ADD COLUMN "batch_sampling_config_id" integer;--> statement-breakpoint
ALTER TABLE "world_summarize_configs" ADD COLUMN "synth_connection_id" integer;--> statement-breakpoint
ALTER TABLE "world_summarize_configs" ADD COLUMN "synth_sampling_config_id" integer;--> statement-breakpoint
ALTER TABLE "world_summarize_configs" ADD COLUMN "name_connection_id" integer;--> statement-breakpoint
ALTER TABLE "world_summarize_configs" ADD COLUMN "name_sampling_config_id" integer;--> statement-breakpoint
ALTER TABLE "graph_build_configs" ADD CONSTRAINT "graph_build_configs_node_resolution_connection_id_connections_id_fk" FOREIGN KEY ("node_resolution_connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "graph_build_configs" ADD CONSTRAINT "graph_build_configs_node_resolution_sampling_config_id_sampling_configs_id_fk" FOREIGN KEY ("node_resolution_sampling_config_id") REFERENCES "public"."sampling_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "graph_build_configs" ADD CONSTRAINT "graph_build_configs_pre_filter_connection_id_connections_id_fk" FOREIGN KEY ("pre_filter_connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "graph_build_configs" ADD CONSTRAINT "graph_build_configs_pre_filter_sampling_config_id_sampling_configs_id_fk" FOREIGN KEY ("pre_filter_sampling_config_id") REFERENCES "public"."sampling_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "graph_build_configs" ADD CONSTRAINT "graph_build_configs_perspective_connection_id_connections_id_fk" FOREIGN KEY ("perspective_connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "graph_build_configs" ADD CONSTRAINT "graph_build_configs_perspective_sampling_config_id_sampling_configs_id_fk" FOREIGN KEY ("perspective_sampling_config_id") REFERENCES "public"."sampling_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "character_summarize_configs" ADD CONSTRAINT "character_summarize_configs_batch_connection_id_connections_id_fk" FOREIGN KEY ("batch_connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "character_summarize_configs" ADD CONSTRAINT "character_summarize_configs_batch_sampling_config_id_sampling_configs_id_fk" FOREIGN KEY ("batch_sampling_config_id") REFERENCES "public"."sampling_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "character_summarize_configs" ADD CONSTRAINT "character_summarize_configs_synth_connection_id_connections_id_fk" FOREIGN KEY ("synth_connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "character_summarize_configs" ADD CONSTRAINT "character_summarize_configs_synth_sampling_config_id_sampling_configs_id_fk" FOREIGN KEY ("synth_sampling_config_id") REFERENCES "public"."sampling_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "character_summarize_configs" ADD CONSTRAINT "character_summarize_configs_name_connection_id_connections_id_fk" FOREIGN KEY ("name_connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "character_summarize_configs" ADD CONSTRAINT "character_summarize_configs_name_sampling_config_id_sampling_configs_id_fk" FOREIGN KEY ("name_sampling_config_id") REFERENCES "public"."sampling_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chats" ADD CONSTRAINT "chats_connection_id_connections_id_fk" FOREIGN KEY ("connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chats" ADD CONSTRAINT "chats_sampling_config_id_sampling_configs_id_fk" FOREIGN KEY ("sampling_config_id") REFERENCES "public"."sampling_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prompt_configs" ADD CONSTRAINT "prompt_configs_connection_id_connections_id_fk" FOREIGN KEY ("connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prompt_configs" ADD CONSTRAINT "prompt_configs_sampling_config_id_sampling_configs_id_fk" FOREIGN KEY ("sampling_config_id") REFERENCES "public"."sampling_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scene_summarize_configs" ADD CONSTRAINT "scene_summarize_configs_batch_connection_id_connections_id_fk" FOREIGN KEY ("batch_connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scene_summarize_configs" ADD CONSTRAINT "scene_summarize_configs_batch_sampling_config_id_sampling_configs_id_fk" FOREIGN KEY ("batch_sampling_config_id") REFERENCES "public"."sampling_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scene_summarize_configs" ADD CONSTRAINT "scene_summarize_configs_synth_connection_id_connections_id_fk" FOREIGN KEY ("synth_connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scene_summarize_configs" ADD CONSTRAINT "scene_summarize_configs_synth_sampling_config_id_sampling_configs_id_fk" FOREIGN KEY ("synth_sampling_config_id") REFERENCES "public"."sampling_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scene_summarize_configs" ADD CONSTRAINT "scene_summarize_configs_name_connection_id_connections_id_fk" FOREIGN KEY ("name_connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scene_summarize_configs" ADD CONSTRAINT "scene_summarize_configs_name_sampling_config_id_sampling_configs_id_fk" FOREIGN KEY ("name_sampling_config_id") REFERENCES "public"."sampling_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_settings" ADD CONSTRAINT "system_settings_default_graph_build_config_id_graph_build_configs_id_fk" FOREIGN KEY ("default_graph_build_config_id") REFERENCES "public"."graph_build_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "world_summarize_configs" ADD CONSTRAINT "world_summarize_configs_batch_connection_id_connections_id_fk" FOREIGN KEY ("batch_connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "world_summarize_configs" ADD CONSTRAINT "world_summarize_configs_batch_sampling_config_id_sampling_configs_id_fk" FOREIGN KEY ("batch_sampling_config_id") REFERENCES "public"."sampling_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "world_summarize_configs" ADD CONSTRAINT "world_summarize_configs_synth_connection_id_connections_id_fk" FOREIGN KEY ("synth_connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "world_summarize_configs" ADD CONSTRAINT "world_summarize_configs_synth_sampling_config_id_sampling_configs_id_fk" FOREIGN KEY ("synth_sampling_config_id") REFERENCES "public"."sampling_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "world_summarize_configs" ADD CONSTRAINT "world_summarize_configs_name_connection_id_connections_id_fk" FOREIGN KEY ("name_connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "world_summarize_configs" ADD CONSTRAINT "world_summarize_configs_name_sampling_config_id_sampling_configs_id_fk" FOREIGN KEY ("name_sampling_config_id") REFERENCES "public"."sampling_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_settings" DROP COLUMN "active_connection_id";--> statement-breakpoint
ALTER TABLE "user_settings" DROP COLUMN "active_sampling_id";