CREATE TABLE "custom_themes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "custom_themes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"label" text NOT NULL,
	"css" text NOT NULL,
	"uploaded_by" integer,
	"is_instance_theme" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "custom_themes_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "koboldcpp_models" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "koboldcpp_models_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"filename" text NOT NULL,
	"model_name" text NOT NULL,
	"model_url" text,
	"download_url" text,
	"description" text,
	"quantization" text,
	"size_bytes" bigint,
	"status" text DEFAULT 'downloading' NOT NULL,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "koboldcpp_models_filename_unique" UNIQUE("filename")
);
--> statement-breakpoint
ALTER TABLE "koboldcpp_settings" ADD COLUMN "koboldcpp_managed_subprocess_timeout_secs" integer DEFAULT 1800 NOT NULL;--> statement-breakpoint
ALTER TABLE "koboldcpp_settings" ADD COLUMN "koboldcpp_managed_release_tag" text;--> statement-breakpoint
ALTER TABLE "custom_themes" ADD CONSTRAINT "custom_themes_uploaded_by_users_id_fk" FOREIGN KEY ("uploaded_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;