CREATE TABLE "binding_merge_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "binding_merge_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lorebook_id" integer NOT NULL,
	"user_id" integer NOT NULL,
	"survivor_id" integer,
	"absorbed_snapshot" json NOT NULL,
	"relationship_rewrites" json DEFAULT '[]'::json NOT NULL,
	"deleted_relationships" json DEFAULT '[]'::json NOT NULL,
	"scene_snapshots" json DEFAULT '[]'::json NOT NULL,
	"absorbed_aliases_added" json DEFAULT '[]'::json NOT NULL,
	"reassigned_character_lore_entry_ids" json DEFAULT '[]'::json NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "lorebook_bindings" ADD COLUMN "absorbed_aliases" json DEFAULT '[]'::json NOT NULL;--> statement-breakpoint
ALTER TABLE "binding_merge_logs" ADD CONSTRAINT "binding_merge_logs_lorebook_id_lorebooks_id_fk" FOREIGN KEY ("lorebook_id") REFERENCES "public"."lorebooks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "binding_merge_logs" ADD CONSTRAINT "binding_merge_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "binding_merge_logs" ADD CONSTRAINT "binding_merge_logs_survivor_id_lorebook_bindings_id_fk" FOREIGN KEY ("survivor_id") REFERENCES "public"."lorebook_bindings"("id") ON DELETE set null ON UPDATE no action;