CREATE TABLE "dismissed_duplicate_pairs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dismissed_duplicate_pairs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lorebook_id" integer NOT NULL,
	"binding_id_a" integer NOT NULL,
	"binding_id_b" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "dismissed_duplicate_pairs" ADD CONSTRAINT "dismissed_duplicate_pairs_lorebook_id_lorebooks_id_fk" FOREIGN KEY ("lorebook_id") REFERENCES "public"."lorebooks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dismissed_duplicate_pairs" ADD CONSTRAINT "dismissed_duplicate_pairs_binding_id_a_lorebook_bindings_id_fk" FOREIGN KEY ("binding_id_a") REFERENCES "public"."lorebook_bindings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dismissed_duplicate_pairs" ADD CONSTRAINT "dismissed_duplicate_pairs_binding_id_b_lorebook_bindings_id_fk" FOREIGN KEY ("binding_id_b") REFERENCES "public"."lorebook_bindings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "dismissed_duplicate_pairs_unique" ON "dismissed_duplicate_pairs" USING btree ("lorebook_id","binding_id_a","binding_id_b");