CREATE TABLE "scene_characters" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scene_characters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scene_id" integer NOT NULL,
	"binding_id" integer NOT NULL,
	"role" text NOT NULL,
	"ordinal" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "scene_characters" ADD CONSTRAINT "scene_characters_scene_id_scenes_id_fk" FOREIGN KEY ("scene_id") REFERENCES "public"."scenes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scene_characters" ADD CONSTRAINT "scene_characters_binding_id_lorebook_bindings_id_fk" FOREIGN KEY ("binding_id") REFERENCES "public"."lorebook_bindings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "scene_characters_unique" ON "scene_characters" USING btree ("scene_id","binding_id","role");--> statement-breakpoint
CREATE INDEX "scene_characters_scene_id_idx" ON "scene_characters" USING btree ("scene_id");--> statement-breakpoint
CREATE INDEX "scene_characters_binding_id_idx" ON "scene_characters" USING btree ("binding_id");--> statement-breakpoint

-- ── Data conversion, BEFORE the columns are dropped ──────────────────────────
--
-- The old arrays could physically hold three different things depending on
-- which version of the app wrote the row: binding ids, pre-merge character
-- NAME STRINGS, or nothing. Both id and name forms are converted here, which
-- is what finally makes the "fix pre-merge scenes" tooling unnecessary — a
-- name string cannot exist in an integer FK column.
--
-- Anything that still resolves to nothing (an id whose binding was deleted, a
-- name matching no binding in that lorebook) is dropped rather than migrated.
-- It could not have been used anyway: every consumer already had to tolerate
-- and skip dangling ids, which is precisely the class of bug the FK ends.
--
-- Order is preserved via WITH ORDINALITY → `ordinal`, because lorebook export
-- serializes the cast in stored order and import hashes those bytes to detect
-- "unchanged vs conflict" — a reordered migration would silently mark every
-- lorebook conflicted on re-import.
--
-- Roles are migrated independently and a character present in BOTH arrays gets
-- BOTH rows. That is real, reachable data (absorb remaps each array
-- separately), and it is why the unique index includes `role` — a role-less
-- constraint would fail this very migration.
INSERT INTO "scene_characters" ("scene_id", "binding_id", "role", "ordinal")
WITH expanded AS (
	SELECT s."id" AS scene_id, s."lorebook_id" AS lorebook_id, e.val, e.ord
	FROM "scenes" s
	CROSS JOIN LATERAL json_array_elements(s."participant_characters")
		WITH ORDINALITY AS e(val, ord)
	WHERE json_typeof(s."participant_characters") = 'array'
),
-- One binding per array position: an ambiguous legacy name matching two
-- same-named bindings resolves to the lowest id rather than duplicating.
matched AS (
	SELECT DISTINCT ON (x.scene_id, x.ord) x.scene_id, b."id" AS binding_id, x.ord
	FROM expanded x
	JOIN "lorebook_bindings" b ON b."lorebook_id" = x.lorebook_id AND (
		(json_typeof(x.val) = 'number' AND b."id" = (x.val #>> '{}')::int)
		OR (json_typeof(x.val) = 'string'
			AND btrim(b."name") <> ''
			AND lower(btrim(b."name")) = lower(btrim(x.val #>> '{}')))
	)
	ORDER BY x.scene_id, x.ord, b."id"
),
-- One row per (scene, binding): a name repeated in the same array collapses to
-- its first position, satisfying the unique index.
deduped AS (
	SELECT DISTINCT ON (scene_id, binding_id) scene_id, binding_id, ord
	FROM matched
	ORDER BY scene_id, binding_id, ord
)
SELECT scene_id, binding_id, 'participant', (ord - 1)::int FROM deduped;
--> statement-breakpoint
INSERT INTO "scene_characters" ("scene_id", "binding_id", "role", "ordinal")
WITH expanded AS (
	SELECT s."id" AS scene_id, s."lorebook_id" AS lorebook_id, e.val, e.ord
	FROM "scenes" s
	CROSS JOIN LATERAL json_array_elements(s."mentioned_characters")
		WITH ORDINALITY AS e(val, ord)
	WHERE json_typeof(s."mentioned_characters") = 'array'
),
matched AS (
	SELECT DISTINCT ON (x.scene_id, x.ord) x.scene_id, b."id" AS binding_id, x.ord
	FROM expanded x
	JOIN "lorebook_bindings" b ON b."lorebook_id" = x.lorebook_id AND (
		(json_typeof(x.val) = 'number' AND b."id" = (x.val #>> '{}')::int)
		OR (json_typeof(x.val) = 'string'
			AND btrim(b."name") <> ''
			AND lower(btrim(b."name")) = lower(btrim(x.val #>> '{}')))
	)
	ORDER BY x.scene_id, x.ord, b."id"
),
deduped AS (
	SELECT DISTINCT ON (scene_id, binding_id) scene_id, binding_id, ord
	FROM matched
	ORDER BY scene_id, binding_id, ord
)
SELECT scene_id, binding_id, 'mentioned', (ord - 1)::int FROM deduped;
--> statement-breakpoint

-- Legacy name strings are now resolved, so scenes that were only ever "pending
-- a pre-merge fix" count as resolved. A scene whose cast genuinely converted
-- to nothing keeps cast_resolved_at NULL and gets re-derived on the next build.
UPDATE "scenes" SET "cast_resolved_at" = now()
WHERE "cast_resolved_at" IS NULL
	AND EXISTS (SELECT 1 FROM "scene_characters" sc WHERE sc."scene_id" = "scenes"."id");
--> statement-breakpoint
ALTER TABLE "scenes" DROP COLUMN "participant_characters";--> statement-breakpoint
ALTER TABLE "scenes" DROP COLUMN "mentioned_characters";
