CREATE TABLE "pipeline_blocks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_blocks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_version_id" integer NOT NULL,
	"block_id" text NOT NULL,
	"kind" text NOT NULL,
	"parent_block_id" text,
	"mode" text,
	"max" integer,
	"over_ref" json,
	"repeat_while" json,
	"position" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "pipeline_blocks_kind_check" CHECK ("pipeline_blocks"."kind" IN ('async', 'map', 'loop')),
	CONSTRAINT "pipeline_blocks_bounded_check" CHECK ("pipeline_blocks"."kind" = 'async' OR "pipeline_blocks"."max" IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE "pipeline_edges" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_edges_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_version_id" integer NOT NULL,
	"from_node_id" integer NOT NULL,
	"from_port" text NOT NULL,
	"to_node_id" integer NOT NULL,
	"to_port" text NOT NULL,
	"edge_shape" text,
	"streaming" boolean,
	"implicit" boolean
);
--> statement-breakpoint
CREATE TABLE "pipeline_event_registry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_event_registry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"family" text DEFAULT 'data' NOT NULL,
	"payload_shape" json,
	"owner_plugin_id" integer,
	"affects_user" boolean DEFAULT false NOT NULL,
	"description_i18n" json,
	CONSTRAINT "pipeline_event_registry_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "pipeline_event_subscriptions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_event_subscriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"event_ref" text NOT NULL,
	"event_slug" text NOT NULL,
	"event_version" integer DEFAULT 1 NOT NULL,
	"spec_version_id" integer NOT NULL,
	"preset_id" integer,
	"depth_bound" integer,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_by" integer
);
--> statement-breakpoint
CREATE TABLE "pipeline_includes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_includes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_version_id" integer NOT NULL,
	"key" text NOT NULL,
	"fragment_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pipeline_nodes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_nodes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_version_id" integer NOT NULL,
	"node_key" text NOT NULL,
	"kind" text NOT NULL,
	"type_id" text NOT NULL,
	"type_version" integer DEFAULT 1 NOT NULL,
	"config" json DEFAULT '{}'::json NOT NULL,
	"resolved_refs" json,
	"block_id" text,
	"block_kind" text,
	"block_chain" text,
	"toggleable" boolean DEFAULT false NOT NULL,
	"enabled_default" boolean DEFAULT true NOT NULL,
	"budget_tokens" integer,
	"budget_calls" integer,
	"position" integer NOT NULL,
	CONSTRAINT "pipeline_nodes_kind_check" CHECK ("pipeline_nodes"."kind" IN ('input', 'query', 'task', 'provider', 'consumer'))
);
--> statement-breakpoint
CREATE TABLE "pipeline_preset_values" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_preset_values_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"preset_id" integer NOT NULL,
	"node_key" text NOT NULL,
	"slot" text NOT NULL,
	"path" text,
	"value" json
);
--> statement-breakpoint
CREATE TABLE "pipeline_presets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_presets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_version_id" integer NOT NULL,
	"slug" text NOT NULL,
	"label" text NOT NULL,
	"description" text,
	"owner_slug" text,
	"owner_plugin_id" integer,
	"is_default" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pipeline_spec_versions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_spec_versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_id" integer NOT NULL,
	"semver" text NOT NULL,
	"engine_range" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"canonical_hash" text NOT NULL,
	"schema_version" integer DEFAULT 1 NOT NULL,
	"derived_from_spec_version_id" integer,
	"migrated_from" text,
	"mode" json,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"published_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "pipeline_specs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_specs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"source_plugin_id" integer,
	"active_version_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_specs_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "pipeline_type_registry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_type_registry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type_id" text NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"kind" text NOT NULL,
	"owner_plugin_id" integer,
	"status" text DEFAULT 'live' NOT NULL,
	"transport" text DEFAULT 'node' NOT NULL,
	"ports" json DEFAULT '{}'::json NOT NULL,
	"slots" json DEFAULT '{}'::json NOT NULL,
	"config_schema" json,
	"effects" text,
	"causes_event" text,
	"is_public" boolean DEFAULT false NOT NULL,
	"declares_randomness" boolean DEFAULT false NOT NULL,
	"early_exit" boolean DEFAULT false NOT NULL,
	"timeout_ms_default" integer,
	"timeout_kind" text DEFAULT 'wall',
	"connection_kind" text,
	"usage_extractor" text,
	"i18n" json,
	"release" text,
	"content_hash" text
);
--> statement-breakpoint
ALTER TABLE "pipeline_blocks" ADD CONSTRAINT "pipeline_blocks_spec_version_id_pipeline_spec_versions_id_fk" FOREIGN KEY ("spec_version_id") REFERENCES "public"."pipeline_spec_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_edges" ADD CONSTRAINT "pipeline_edges_spec_version_id_pipeline_spec_versions_id_fk" FOREIGN KEY ("spec_version_id") REFERENCES "public"."pipeline_spec_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_edges" ADD CONSTRAINT "pipeline_edges_from_node_id_pipeline_nodes_id_fk" FOREIGN KEY ("from_node_id") REFERENCES "public"."pipeline_nodes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_edges" ADD CONSTRAINT "pipeline_edges_to_node_id_pipeline_nodes_id_fk" FOREIGN KEY ("to_node_id") REFERENCES "public"."pipeline_nodes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_event_subscriptions" ADD CONSTRAINT "pipeline_event_subscriptions_spec_version_id_pipeline_spec_versions_id_fk" FOREIGN KEY ("spec_version_id") REFERENCES "public"."pipeline_spec_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_event_subscriptions" ADD CONSTRAINT "pipeline_event_subscriptions_preset_id_pipeline_presets_id_fk" FOREIGN KEY ("preset_id") REFERENCES "public"."pipeline_presets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_event_subscriptions" ADD CONSTRAINT "pipeline_event_subscriptions_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_includes" ADD CONSTRAINT "pipeline_includes_spec_version_id_pipeline_spec_versions_id_fk" FOREIGN KEY ("spec_version_id") REFERENCES "public"."pipeline_spec_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_nodes" ADD CONSTRAINT "pipeline_nodes_spec_version_id_pipeline_spec_versions_id_fk" FOREIGN KEY ("spec_version_id") REFERENCES "public"."pipeline_spec_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_preset_values" ADD CONSTRAINT "pipeline_preset_values_preset_id_pipeline_presets_id_fk" FOREIGN KEY ("preset_id") REFERENCES "public"."pipeline_presets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_presets" ADD CONSTRAINT "pipeline_presets_spec_version_id_pipeline_spec_versions_id_fk" FOREIGN KEY ("spec_version_id") REFERENCES "public"."pipeline_spec_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_spec_versions" ADD CONSTRAINT "pipeline_spec_versions_spec_id_pipeline_specs_id_fk" FOREIGN KEY ("spec_id") REFERENCES "public"."pipeline_specs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_blocks_version_block_idx" ON "pipeline_blocks" USING btree ("spec_version_id","block_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_nodes_version_key_idx" ON "pipeline_nodes" USING btree ("spec_version_id","node_key");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_presets_version_slug_idx" ON "pipeline_presets" USING btree ("spec_version_id","slug");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_spec_versions_spec_semver_idx" ON "pipeline_spec_versions" USING btree ("spec_id","semver");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_type_registry_type_version_idx" ON "pipeline_type_registry" USING btree ("type_id","version");