CREATE TABLE "account_invites" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "account_invites_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token_hash" text NOT NULL,
	"kind" text NOT NULL,
	"user_id" integer,
	"created_by" integer,
	"expires_at" timestamp NOT NULL,
	"used_at" timestamp,
	"revoked_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "account_invites_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE TABLE "connection_defaults" (
	"input" text NOT NULL,
	"output" text NOT NULL,
	"connection_id" integer,
	"sampling_config_id" integer,
	CONSTRAINT "connection_defaults_input_output_pk" PRIMARY KEY("input","output"),
	CONSTRAINT "connection_defaults_sides_check" CHECK ("connection_defaults"."input" <> '' AND "connection_defaults"."output" <> '')
);
--> statement-breakpoint
CREATE TABLE "connection_scripts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "connection_scripts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"connection_id" integer NOT NULL,
	"script_id" integer NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "entry_annotations" (
	"entry_id" integer NOT NULL,
	"entity_key" text NOT NULL,
	"surface" text DEFAULT '' NOT NULL,
	"normalized" text DEFAULT '' NOT NULL,
	"tier" text NOT NULL,
	"character_id" integer,
	"persona_id" integer,
	"ref_entry_id" integer,
	"confidence" real DEFAULT 1 NOT NULL,
	"mentions" integer DEFAULT 0 NOT NULL,
	"spans" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"extractor_version" text NOT NULL,
	"source_hash" text NOT NULL,
	"gazetteer_hash" text NOT NULL,
	"annotated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "entry_annotations_pkey" PRIMARY KEY("entry_id","entity_key")
);
--> statement-breakpoint
CREATE TABLE "files" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "files_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uuid" uuid DEFAULT (gen_random_uuid ()) NOT NULL,
	"rev" integer DEFAULT 0 NOT NULL,
	"display_variant_id" integer,
	"display_mime" text,
	"display_bytes" integer,
	"user_id" integer NOT NULL,
	"character_id" integer,
	"persona_id" integer,
	"session_id" integer,
	"message_id" integer,
	"visibility" text DEFAULT 'scoped' NOT NULL,
	"kind" text NOT NULL,
	"hash" text NOT NULL,
	"filename" text,
	"width" integer,
	"height" integer,
	"duration_ms" integer,
	"position" integer DEFAULT 0 NOT NULL,
	"meta" json,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "files_uuid_unique" UNIQUE("uuid"),
	CONSTRAINT "files_visibility_check" CHECK ("files"."visibility" IN ('scoped', 'private'))
);
--> statement-breakpoint
CREATE TABLE "lorebook_entries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lorebook_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lorebook_id" integer NOT NULL,
	"type_id" text NOT NULL,
	"type_version" integer NOT NULL,
	"keys" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"match_mode" text,
	"use_regex" boolean,
	"case_sensitive" boolean,
	"secondary_keys" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"selective_logic" text,
	"recursion_depth" integer,
	"content" text DEFAULT '' NOT NULL,
	"constant" boolean DEFAULT false NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"archived" boolean DEFAULT false NOT NULL,
	"weight" real,
	"provenance" text DEFAULT 'human' NOT NULL,
	"position" integer NOT NULL,
	"title" text,
	"anchor_binding_id" integer,
	"anchor_entry_id" integer,
	"fields" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"extra_json" json DEFAULT '{}'::json NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "lorebook_entries_position_uq" UNIQUE("lorebook_id","type_id","position")
);
--> statement-breakpoint
CREATE TABLE "lorebook_entry_vectors" (
	"entry_id" integer NOT NULL,
	"vector_name" text NOT NULL,
	"chunk_index" integer DEFAULT 0 NOT NULL,
	"model" text,
	"model_version" text,
	"normalization" text,
	"dims" integer NOT NULL,
	"vector" real[] NOT NULL,
	"source_hash" text,
	"extractor_version" text,
	"gazetteer_hash" text,
	"chunk_meta" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"vectorized_at" timestamp,
	CONSTRAINT "lorebook_entry_vectors_pkey" PRIMARY KEY("entry_id","vector_name","chunk_index")
);
--> statement-breakpoint
CREATE TABLE "message_annotations" (
	"message_id" integer NOT NULL,
	"entity_key" text NOT NULL,
	"surface" text DEFAULT '' NOT NULL,
	"normalized" text DEFAULT '' NOT NULL,
	"tier" text NOT NULL,
	"character_id" integer,
	"persona_id" integer,
	"ref_entry_id" integer,
	"confidence" real DEFAULT 1 NOT NULL,
	"mentions" integer DEFAULT 0 NOT NULL,
	"spans" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"extractor_version" text NOT NULL,
	"source_hash" text NOT NULL,
	"gazetteer_hash" text NOT NULL,
	"annotated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "message_annotations_pkey" PRIMARY KEY("message_id","entity_key")
);
--> statement-breakpoint
CREATE TABLE "message_parts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "message_parts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"message_id" integer NOT NULL,
	"step" integer DEFAULT 0 NOT NULL,
	"revision" integer DEFAULT 0 NOT NULL,
	"ordinal" integer DEFAULT 0 NOT NULL,
	"type" text NOT NULL,
	"content" text,
	"data" json
);
--> statement-breakpoint
CREATE TABLE "messages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" integer NOT NULL,
	"channel" text DEFAULT 'main' NOT NULL,
	"kind" text DEFAULT 'core:chat' NOT NULL,
	"version" text,
	"user_id" integer,
	"character_id" integer,
	"persona_id" integer,
	"speaker_label" text,
	"role" text NOT NULL,
	"status" text DEFAULT 'settled' NOT NULL,
	"error" json,
	"active_revisions" json DEFAULT '{"0":0}'::json NOT NULL,
	"extras" json DEFAULT '{}'::json NOT NULL,
	"is_hidden" boolean DEFAULT false NOT NULL,
	"is_edited" boolean DEFAULT false NOT NULL,
	"debug_meta" json,
	"queue_item_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pipeline_blocks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_blocks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_version_id" integer NOT NULL,
	"block_id" text NOT NULL,
	"kind" text NOT NULL,
	"parent_block_id" text,
	"mode" text,
	"max" integer,
	"over_ref" json,
	"repeat_while" json,
	"on_ref" json,
	"routes" json,
	"position" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "pipeline_blocks_kind_check" CHECK ("pipeline_blocks"."kind" IN ('async', 'map', 'loop', 'route')),
	CONSTRAINT "pipeline_blocks_bounded_check" CHECK ("pipeline_blocks"."kind" IN ('async', 'route') OR "pipeline_blocks"."max" IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE "pipeline_config_notices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_config_notices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"config_id" integer NOT NULL,
	"kind" text NOT NULL,
	"node_key" text NOT NULL,
	"slot" text NOT NULL,
	"path" text DEFAULT '' NOT NULL,
	"label" text,
	"previous_value" json,
	"spec_version_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"acknowledged_at" timestamp,
	CONSTRAINT "pipeline_config_notices_kind_check" CHECK ("pipeline_config_notices"."kind" IN ('culled', 'backfilled'))
);
--> statement-breakpoint
CREATE TABLE "pipeline_config_selections" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_config_selections_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_id" integer NOT NULL,
	"scope_kind" text NOT NULL,
	"scope_id" integer DEFAULT 0 NOT NULL,
	"preset_slug" text,
	"config_id" integer,
	"updated_by" integer,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_config_selections_scope_check" CHECK ("pipeline_config_selections"."scope_kind" IN ('instance', 'session'))
);
--> statement-breakpoint
CREATE TABLE "pipeline_config_values" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_config_values_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"config_id" integer NOT NULL,
	"node_key" text NOT NULL,
	"slot" text NOT NULL,
	"path" text DEFAULT '' NOT NULL,
	"value" json
);
--> statement-breakpoint
CREATE TABLE "pipeline_configs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_configs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_id" integer NOT NULL,
	"seed_key" text,
	"name" text NOT NULL,
	"is_immutable" boolean DEFAULT false NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"included_actions" json,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_configs_seed_key_unique" UNIQUE("seed_key")
);
--> statement-breakpoint
CREATE TABLE "pipeline_context_templates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_context_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"node_type_id" text NOT NULL,
	"created_for_spec_id" integer,
	"engine" text DEFAULT 'core:template/handlebars@1' NOT NULL,
	"name" text NOT NULL,
	"source" text DEFAULT '' NOT NULL,
	"seed_key" text,
	"is_immutable" boolean DEFAULT false NOT NULL,
	"migrated_from_context_config_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_context_templates_seed_key_unique" UNIQUE("seed_key")
);
--> statement-breakpoint
CREATE TABLE "pipeline_edges" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_edges_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_version_id" integer NOT NULL,
	"from_node_id" integer,
	"from_block_id" text,
	"from_port" text NOT NULL,
	"to_node_id" integer NOT NULL,
	"to_port" text NOT NULL,
	"edge_shape" text,
	"streaming" boolean,
	"implicit" boolean,
	CONSTRAINT "pipeline_edges_one_source_check" CHECK (("pipeline_edges"."from_node_id" IS NULL) <> ("pipeline_edges"."from_block_id" IS NULL))
);
--> statement-breakpoint
CREATE TABLE "pipeline_event_registry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_event_registry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"family" text DEFAULT 'data' NOT NULL,
	"payload_shape" json,
	"owner_plugin_id" integer,
	"affects_user" boolean DEFAULT false NOT NULL,
	"description_i18n" json,
	CONSTRAINT "pipeline_event_registry_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "pipeline_event_subscriptions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_event_subscriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"event_ref" text NOT NULL,
	"event_slug" text NOT NULL,
	"event_version" integer DEFAULT 1 NOT NULL,
	"spec_version_id" integer NOT NULL,
	"preset_id" integer,
	"depth_bound" integer,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_by" integer
);
--> statement-breakpoint
CREATE TABLE "pipeline_function_bindings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_function_bindings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scope_kind" text NOT NULL,
	"scope_id" integer DEFAULT 0 NOT NULL,
	"genre_id" text NOT NULL,
	"function_key" text NOT NULL,
	"spec_id" integer NOT NULL,
	"updated_by" integer,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_function_bindings_scope_check" CHECK ("pipeline_function_bindings"."scope_kind" IN ('instance', 'session'))
);
--> statement-breakpoint
CREATE TABLE "pipeline_includes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_includes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_version_id" integer NOT NULL,
	"key" text NOT NULL,
	"fragment_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pipeline_node_overrides" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_node_overrides_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_id" integer NOT NULL,
	"scope_kind" text NOT NULL,
	"scope_id" integer DEFAULT 0 NOT NULL,
	"node_key" text NOT NULL,
	"slot" text NOT NULL,
	"path" text DEFAULT '' NOT NULL,
	"value" json,
	"updated_by" integer,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_node_overrides_scope_check" CHECK ("pipeline_node_overrides"."scope_kind" = 'session')
);
--> statement-breakpoint
CREATE TABLE "pipeline_node_rebinds" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_node_rebinds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_id" integer NOT NULL,
	"scope_kind" text NOT NULL,
	"scope_id" integer DEFAULT 0 NOT NULL,
	"node_key" text NOT NULL,
	"type_id" text NOT NULL,
	"updated_by" integer,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_node_rebinds_scope_check" CHECK ("pipeline_node_rebinds"."scope_kind" IN ('instance', 'session'))
);
--> statement-breakpoint
CREATE TABLE "pipeline_nodes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_nodes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_version_id" integer NOT NULL,
	"node_key" text NOT NULL,
	"kind" text NOT NULL,
	"type_id" text NOT NULL,
	"type_version" integer DEFAULT 1 NOT NULL,
	"config" json DEFAULT '{}'::json NOT NULL,
	"resolved_refs" json,
	"block_id" text,
	"block_kind" text,
	"block_chain" text,
	"toggleable" boolean DEFAULT false NOT NULL,
	"enabled_default" boolean DEFAULT true NOT NULL,
	"budget_tokens" integer,
	"budget_calls" integer,
	"position" integer NOT NULL,
	CONSTRAINT "pipeline_nodes_kind_check" CHECK ("pipeline_nodes"."kind" IN ('input', 'query', 'task', 'provider', 'consumer'))
);
--> statement-breakpoint
CREATE TABLE "pipeline_preset_values" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_preset_values_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"preset_id" integer NOT NULL,
	"node_key" text NOT NULL,
	"slot" text NOT NULL,
	"path" text,
	"value" json
);
--> statement-breakpoint
CREATE TABLE "pipeline_presets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_presets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_version_id" integer NOT NULL,
	"slug" text NOT NULL,
	"label" text NOT NULL,
	"description" text,
	"owner_slug" text,
	"owner_plugin_id" integer,
	"is_default" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pipeline_prompts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_prompts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"node_type_id" text NOT NULL,
	"slot" text NOT NULL,
	"created_for_spec_id" integer,
	"default_for_specs" json DEFAULT '[]'::json NOT NULL,
	"seed_key" text,
	"name" text NOT NULL,
	"is_immutable" boolean DEFAULT false NOT NULL,
	"fields" json DEFAULT '{}'::json NOT NULL,
	"archived_fields" json DEFAULT '{}'::json NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_prompts_seed_key_unique" UNIQUE("seed_key")
);
--> statement-breakpoint
CREATE TABLE "pipeline_run_nodes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_run_nodes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"run_id" integer NOT NULL,
	"seq" integer NOT NULL,
	"node_key" text NOT NULL,
	"kind" text NOT NULL,
	"type_id" text NOT NULL,
	"result" text NOT NULL,
	"reason" text,
	"elapsed_ms" integer DEFAULT 0 NOT NULL,
	"tokens" integer,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pipeline_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"run_id" text NOT NULL,
	"spec_slug" text NOT NULL,
	"spec_version" text NOT NULL,
	"spec_version_id" integer,
	"session_id" integer,
	"user_id" integer,
	"message_id" integer,
	"outcome" text NOT NULL,
	"halt_node_key" text,
	"halt_reason" text,
	"trigger_source" text NOT NULL,
	"seed" text NOT NULL,
	"is_preview" boolean DEFAULT false NOT NULL,
	"started_at" timestamp NOT NULL,
	"ended_at" timestamp NOT NULL,
	"elapsed_ms" integer DEFAULT 0 NOT NULL,
	"tokens_spent" integer DEFAULT 0 NOT NULL,
	"receipt" json NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_runs_run_id_unique" UNIQUE("run_id")
);
--> statement-breakpoint
CREATE TABLE "pipeline_scripts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_scripts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type_id" text NOT NULL,
	"seed_key" text,
	"name" text NOT NULL,
	"is_immutable" boolean DEFAULT false NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"source" text DEFAULT '' NOT NULL,
	"vars_in" json DEFAULT '[]'::json NOT NULL,
	"vars_out" json DEFAULT '[]'::json NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_scripts_seed_key_unique" UNIQUE("seed_key")
);
--> statement-breakpoint
CREATE TABLE "pipeline_spec_versions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_spec_versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_id" integer NOT NULL,
	"semver" text NOT NULL,
	"engine_range" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"canonical_hash" text NOT NULL,
	"schema_version" integer DEFAULT 1 NOT NULL,
	"derived_from_spec_version_id" integer,
	"migrated_from" text,
	"genre" json,
	"input_genre" text,
	"input_event" text,
	"contributes" json,
	"taxonomy" json,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"published_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "pipeline_specs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_specs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"source_plugin_id" integer,
	"active_version_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_specs_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "pipeline_type_registry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_type_registry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type_id" text NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"kind" text NOT NULL,
	"owner_plugin_id" integer,
	"status" text DEFAULT 'live' NOT NULL,
	"transport" text DEFAULT 'node' NOT NULL,
	"ports" json DEFAULT '{}'::json NOT NULL,
	"slots" json DEFAULT '{}'::json NOT NULL,
	"config_schema" json,
	"effects" text,
	"optional" boolean DEFAULT false NOT NULL,
	"semantics" text,
	"script_points" json,
	"session_shape" json,
	"entry_shape" json,
	"causes_event" text,
	"is_public" boolean DEFAULT false NOT NULL,
	"declares_randomness" boolean DEFAULT false NOT NULL,
	"early_exit" boolean DEFAULT false NOT NULL,
	"timeout_ms_default" integer,
	"timeout_kind" text DEFAULT 'wall',
	"connection_kind" text,
	"usage_extractor" text,
	"i18n" json,
	"release" text,
	"content_hash" text
);
--> statement-breakpoint
CREATE TABLE "pipeline_variable_templates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_variable_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"variable_id" text NOT NULL,
	"engine" text DEFAULT 'core:template/handlebars@1' NOT NULL,
	"name" text NOT NULL,
	"source" text DEFAULT '' NOT NULL,
	"seed_key" text,
	"is_immutable" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_variable_templates_seed_key_unique" UNIQUE("seed_key")
);
--> statement-breakpoint
CREATE TABLE "plugin_files" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plugin_files_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"plugin_id" text NOT NULL,
	"path" text NOT NULL,
	"mime" text NOT NULL,
	"content" text NOT NULL,
	"hash" text NOT NULL,
	"bytes" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "plugin_hook_invocations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plugin_hook_invocations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"plugin_id" text NOT NULL,
	"plugin_name" text NOT NULL,
	"bundle_hash" text NOT NULL,
	"hook_name" text NOT NULL,
	"backend" text NOT NULL,
	"mode" text NOT NULL,
	"triggered_by" text,
	"run_id" text,
	"queued_at" timestamp NOT NULL,
	"started_at" timestamp NOT NULL,
	"finished_at" timestamp NOT NULL,
	"duration_ms" integer NOT NULL,
	"ok" boolean NOT NULL,
	"outcome" text NOT NULL,
	"reason" text
);
--> statement-breakpoint
CREATE TABLE "plugin_rows" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plugin_rows_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"plugin_id" text NOT NULL,
	"key" text NOT NULL,
	"value" json,
	"bytes" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "plugins" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plugins_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"plugin_id" text NOT NULL,
	"name" text NOT NULL,
	"version" text DEFAULT '0.0.0' NOT NULL,
	"bundle_source" text NOT NULL,
	"bundle_hash" text NOT NULL,
	"backends" json DEFAULT '["quickjs"]'::json NOT NULL,
	"backend" text DEFAULT 'quickjs' NOT NULL,
	"sequential" boolean DEFAULT false NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"manifest" json DEFAULT '{}'::json NOT NULL,
	"admin_denied" json DEFAULT '[]'::json NOT NULL,
	"storage_quota_override" bigint,
	"settings" json DEFAULT '{}'::json NOT NULL,
	"installed_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "plugins_plugin_id_unique" UNIQUE("plugin_id"),
	CONSTRAINT "plugins_backend_check" CHECK ("plugins"."backend" IN ('quickjs', 'ses'))
);
--> statement-breakpoint
CREATE TABLE "servers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "servers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"is_seeded" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "servers_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "session_functions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_functions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" integer NOT NULL,
	"genre_id" text NOT NULL,
	"function_key" text NOT NULL,
	"enabled" boolean NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session_genre_settings" (
	"genre_id" text PRIMARY KEY NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"default_preset_id" integer,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session_layout_presets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_layout_presets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"seed_key" text,
	"genre_id" text NOT NULL,
	"author_user_id" integer,
	"name" text NOT NULL,
	"layout" json DEFAULT '{}'::json NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "session_layout_presets_seed_key_unique" UNIQUE("seed_key")
);
--> statement-breakpoint
CREATE TABLE "session_panel_layouts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_panel_layouts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" integer NOT NULL,
	"user_id" integer NOT NULL,
	"layout" json DEFAULT '{}'::json NOT NULL,
	"layout_preset_id" integer,
	"layout_settings" json DEFAULT '{}'::json NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session_presets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_presets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"seed_key" text,
	"name" text NOT NULL,
	"description" text,
	"genre_id" text NOT NULL,
	"primary_slug" text,
	"bindings" json DEFAULT '{}'::json NOT NULL,
	"config_selections" json DEFAULT '{}'::json NOT NULL,
	"included_actions" json,
	"defaults" json,
	"enabled" boolean DEFAULT true NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"is_immutable" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "session_presets_seed_key_unique" UNIQUE("seed_key")
);
--> statement-breakpoint
CREATE TABLE "tunnels" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tunnels_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"server_id" integer NOT NULL,
	"provider" text NOT NULL,
	"mode" text NOT NULL,
	"credential" json,
	"hostname" text,
	"enabled" boolean DEFAULT false NOT NULL,
	"auto_start" boolean DEFAULT false NOT NULL,
	"status" text DEFAULT 'stopped' NOT NULL,
	"last_error" text,
	"ttl_seconds" integer,
	"expires_at" timestamp,
	"started_at" timestamp,
	"stopped_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ui_translations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ui_translations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"language" text NOT NULL,
	"source_key" text NOT NULL,
	"source" text NOT NULL,
	"translated" text NOT NULL,
	"engine" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_totp" (
	"user_id" integer PRIMARY KEY NOT NULL,
	"secret" json NOT NULL,
	"enabled_at" timestamp,
	"last_used_step" integer,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_totp_recovery_codes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_totp_recovery_codes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"code_hash" text NOT NULL,
	"used_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "variants" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "variants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"file_id" integer NOT NULL,
	"variant" text NOT NULL,
	"mime" text NOT NULL,
	"bytes" integer NOT NULL,
	"path" text NOT NULL,
	"hash" text NOT NULL,
	"width" integer,
	"height" integer,
	"is_original" boolean DEFAULT false NOT NULL,
	"cache" boolean DEFAULT false NOT NULL,
	"fidelity" text DEFAULT 'full' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "variants_variant_check" CHECK ("variants"."variant" IN ('original', 'display', 'thumb')),
	CONSTRAINT "variants_fidelity_check" CHECK ("variants"."fidelity" IN ('full', 'reduced'))
);
--> statement-breakpoint
CREATE TABLE "widget_styles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "widget_styles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"widget_slug" text NOT NULL,
	"source" text DEFAULT 'user' NOT NULL,
	"owner_user_id" integer,
	"visibility" text DEFAULT 'private' NOT NULL,
	"title" text NOT NULL,
	"css" text DEFAULT '' NOT NULL,
	"vars" json DEFAULT '{}'::json NOT NULL,
	"seeded_by_version" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "widget_styles_slug_unique" UNIQUE("slug"),
	CONSTRAINT "widget_styles_source_check" CHECK ("widget_styles"."source" IN ('system', 'user')),
	CONSTRAINT "widget_styles_visibility_check" CHECK ("widget_styles"."visibility" IN ('system', 'private', 'shared'))
);
--> statement-breakpoint
ALTER TABLE "character_gallery_images" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "persona_gallery_images" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "character_gallery_images" CASCADE;--> statement-breakpoint
DROP TABLE "persona_gallery_images" CASCADE;--> statement-breakpoint
ALTER TABLE "chat_characters" RENAME TO "session_characters";--> statement-breakpoint
ALTER TABLE "chat_guests" RENAME TO "session_guests";--> statement-breakpoint
ALTER TABLE "chat_lorebooks" RENAME TO "session_lorebooks";--> statement-breakpoint
ALTER TABLE "chat_messages" RENAME TO "session_messages";--> statement-breakpoint
ALTER TABLE "chat_personas" RENAME TO "session_personas";--> statement-breakpoint
ALTER TABLE "chat_tags" RENAME TO "session_tags";--> statement-breakpoint
ALTER TABLE "chats" RENAME TO "sessions";--> statement-breakpoint
ALTER TABLE "session_characters" DROP CONSTRAINT "chat_characters_chat_id_chats_id_fk";
--> statement-breakpoint
ALTER TABLE "session_characters" DROP CONSTRAINT "chat_characters_character_id_characters_id_fk";
--> statement-breakpoint
ALTER TABLE "session_guests" DROP CONSTRAINT "chat_guests_chat_id_chats_id_fk";
--> statement-breakpoint
ALTER TABLE "session_guests" DROP CONSTRAINT "chat_guests_user_id_users_id_fk";
--> statement-breakpoint
ALTER TABLE "session_lorebooks" DROP CONSTRAINT "chat_lorebooks_chat_id_chats_id_fk";
--> statement-breakpoint
ALTER TABLE "session_lorebooks" DROP CONSTRAINT "chat_lorebooks_lorebook_id_lorebooks_id_fk";
--> statement-breakpoint
ALTER TABLE "session_messages" DROP CONSTRAINT "chat_messages_chat_id_chats_id_fk";
--> statement-breakpoint
ALTER TABLE "session_messages" DROP CONSTRAINT "chat_messages_user_id_users_id_fk";
--> statement-breakpoint
ALTER TABLE "session_messages" DROP CONSTRAINT "chat_messages_character_id_characters_id_fk";
--> statement-breakpoint
ALTER TABLE "session_messages" DROP CONSTRAINT "chat_messages_persona_id_personas_id_fk";
--> statement-breakpoint
ALTER TABLE "session_personas" DROP CONSTRAINT "chat_personas_chat_id_chats_id_fk";
--> statement-breakpoint
ALTER TABLE "session_personas" DROP CONSTRAINT "chat_personas_persona_id_personas_id_fk";
--> statement-breakpoint
ALTER TABLE "session_tags" DROP CONSTRAINT "chat_tags_chat_id_chats_id_fk";
--> statement-breakpoint
ALTER TABLE "session_tags" DROP CONSTRAINT "chat_tags_tag_id_tags_id_fk";
--> statement-breakpoint
ALTER TABLE "sessions" DROP CONSTRAINT "chats_user_id_users_id_fk";
--> statement-breakpoint
ALTER TABLE "sessions" DROP CONSTRAINT "chats_lorebook_id_lorebooks_id_fk";
--> statement-breakpoint
ALTER TABLE "sessions" DROP CONSTRAINT "chats_connection_id_connections_id_fk";
--> statement-breakpoint
ALTER TABLE "sessions" DROP CONSTRAINT "chats_sampling_config_id_sampling_configs_id_fk";
--> statement-breakpoint
ALTER TABLE "sessions" DROP CONSTRAINT "chats_prompt_config_id_prompt_configs_id_fk";
--> statement-breakpoint
ALTER TABLE "sessions" DROP CONSTRAINT "chats_narrator_prompt_config_id_narrator_prompt_configs_id_fk";
--> statement-breakpoint
ALTER TABLE "lorebook_bindings" DROP CONSTRAINT "lorebook_bindings_history_entry_id_history_entries_id_fk";
--> statement-breakpoint
ALTER TABLE "narrative_relationships" DROP CONSTRAINT "narrative_relationships_history_entry_id_history_entries_id_fk";
--> statement-breakpoint
ALTER TABLE "scenes" DROP CONSTRAINT "scenes_chat_id_chats_id_fk";
--> statement-breakpoint
ALTER TABLE "scenes" DROP CONSTRAINT "scenes_history_entry_id_history_entries_id_fk";
--> statement-breakpoint
ALTER TABLE "system_settings" DROP CONSTRAINT "system_settings_default_connection_id_connections_id_fk";
--> statement-breakpoint
ALTER TABLE "system_settings" DROP CONSTRAINT "system_settings_default_sampling_id_sampling_configs_id_fk";
--> statement-breakpoint
DROP INDEX "chat_characters_pk";--> statement-breakpoint
DROP INDEX "chat_characters_character_id_idx";--> statement-breakpoint
DROP INDEX "chat_guests_pk";--> statement-breakpoint
DROP INDEX "chat_messages_chat_id_idx";--> statement-breakpoint
DROP INDEX "chat_personas_pk";--> statement-breakpoint
DROP INDEX "chat_personas_persona_id_idx";--> statement-breakpoint
DROP INDEX "chat_tags_unique";--> statement-breakpoint
DROP INDEX "chats_user_id_idx";--> statement-breakpoint
DROP INDEX "scenes_chat_id_idx";--> statement-breakpoint
ALTER TABLE "character_lore_entries" ADD COLUMN "retrieval_strategy" text;--> statement-breakpoint
ALTER TABLE "character_lore_entries" ADD COLUMN "match_mode" text;--> statement-breakpoint
ALTER TABLE "character_lore_entries" ADD COLUMN "recursion_depth" integer;--> statement-breakpoint
ALTER TABLE "characters" ADD COLUMN "avatar_media_id" integer;--> statement-breakpoint
ALTER TABLE "session_characters" ADD COLUMN "session_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "session_guests" ADD COLUMN "session_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "session_lorebooks" ADD COLUMN "session_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "session_messages" ADD COLUMN "session_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "session_messages" ADD COLUMN "channel" text DEFAULT 'main' NOT NULL;--> statement-breakpoint
ALTER TABLE "session_personas" ADD COLUMN "session_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "session_tags" ADD COLUMN "session_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "genre_id" text DEFAULT 'core:genre/chat' NOT NULL;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "preset_id" integer;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "genre_fields" json DEFAULT '{}'::json NOT NULL;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "session_type" text DEFAULT 'roleplay' NOT NULL;--> statement-breakpoint
ALTER TABLE "connections" ADD COLUMN "modality" text DEFAULT 'text-gen' NOT NULL;--> statement-breakpoint
ALTER TABLE "connections" ADD COLUMN "capabilities" json DEFAULT '{}'::json NOT NULL;--> statement-breakpoint
ALTER TABLE "connections" ADD COLUMN "preset" text;--> statement-breakpoint
ALTER TABLE "context_configs" ADD COLUMN "engine" text;--> statement-breakpoint
ALTER TABLE "history_entries" ADD COLUMN "retrieval_strategy" text;--> statement-breakpoint
ALTER TABLE "history_entries" ADD COLUMN "match_mode" text;--> statement-breakpoint
ALTER TABLE "history_entries" ADD COLUMN "recursion_depth" integer;--> statement-breakpoint
ALTER TABLE "koboldcpp_models" ADD COLUMN "kind" text DEFAULT 'text' NOT NULL;--> statement-breakpoint
ALTER TABLE "koboldcpp_models" ADD COLUMN "kind_source" text DEFAULT 'assumed' NOT NULL;--> statement-breakpoint
ALTER TABLE "koboldcpp_settings" ADD COLUMN "koboldcpp_image_models_dir" text;--> statement-breakpoint
ALTER TABLE "personas" ADD COLUMN "avatar_media_id" integer;--> statement-breakpoint
ALTER TABLE "sampling_configs" ADD COLUMN "shape" text DEFAULT 'core:shape/text-gen@1' NOT NULL;--> statement-breakpoint
ALTER TABLE "sampling_configs" ADD COLUMN "values" json DEFAULT '{}'::json NOT NULL;--> statement-breakpoint
ALTER TABLE "sampling_configs" ADD COLUMN "enabled" json DEFAULT '[]'::json NOT NULL;--> statement-breakpoint
ALTER TABLE "scenes" ADD COLUMN "session_id" integer;--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "active_embedding_connection_id" integer;--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "require_two_factor" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "recovery_key_hash" text;--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "scripts_enabled" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "pipelines_enabled" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "legacy_prompt_configs_visible" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "context_templates_migrated" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "default_language" text DEFAULT 'en' NOT NULL;--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "auto_translate_enabled" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "auto_translate_engine" text DEFAULT 'google' NOT NULL;--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "auto_translate_endpoint" text;--> statement-breakpoint
ALTER TABLE "user_settings" ADD COLUMN "background_media_id" integer;--> statement-breakpoint
ALTER TABLE "user_settings" ADD COLUMN "language" text;--> statement-breakpoint
ALTER TABLE "user_settings" ADD COLUMN "derived_media_cache_enabled" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "user_tokens" ADD COLUMN "mfa_verified_at" timestamp;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "last_login_at" timestamp;--> statement-breakpoint
ALTER TABLE "world_lore_entries" ADD COLUMN "retrieval_strategy" text;--> statement-breakpoint
ALTER TABLE "world_lore_entries" ADD COLUMN "match_mode" text;--> statement-breakpoint
ALTER TABLE "world_lore_entries" ADD COLUMN "recursion_depth" integer;--> statement-breakpoint
ALTER TABLE "account_invites" ADD CONSTRAINT "account_invites_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account_invites" ADD CONSTRAINT "account_invites_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "connection_defaults" ADD CONSTRAINT "connection_defaults_connection_id_connections_id_fk" FOREIGN KEY ("connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "connection_defaults" ADD CONSTRAINT "connection_defaults_sampling_config_id_sampling_configs_id_fk" FOREIGN KEY ("sampling_config_id") REFERENCES "public"."sampling_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "connection_scripts" ADD CONSTRAINT "connection_scripts_connection_id_connections_id_fk" FOREIGN KEY ("connection_id") REFERENCES "public"."connections"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "connection_scripts" ADD CONSTRAINT "connection_scripts_script_id_pipeline_scripts_id_fk" FOREIGN KEY ("script_id") REFERENCES "public"."pipeline_scripts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entry_annotations" ADD CONSTRAINT "entry_annotations_entry_id_lorebook_entries_id_fk" FOREIGN KEY ("entry_id") REFERENCES "public"."lorebook_entries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entry_annotations" ADD CONSTRAINT "entry_annotations_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entry_annotations" ADD CONSTRAINT "entry_annotations_persona_id_personas_id_fk" FOREIGN KEY ("persona_id") REFERENCES "public"."personas"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entry_annotations" ADD CONSTRAINT "entry_annotations_ref_entry_id_lorebook_entries_id_fk" FOREIGN KEY ("ref_entry_id") REFERENCES "public"."lorebook_entries"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lorebook_entries" ADD CONSTRAINT "lorebook_entries_lorebook_id_lorebooks_id_fk" FOREIGN KEY ("lorebook_id") REFERENCES "public"."lorebooks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lorebook_entries" ADD CONSTRAINT "lorebook_entries_anchor_binding_id_lorebook_bindings_id_fk" FOREIGN KEY ("anchor_binding_id") REFERENCES "public"."lorebook_bindings"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lorebook_entries" ADD CONSTRAINT "lorebook_entries_anchor_entry_id_lorebook_entries_id_fk" FOREIGN KEY ("anchor_entry_id") REFERENCES "public"."lorebook_entries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
-- MOVED (not generated in this position): drizzle-kit emits foreign keys
-- before indexes, but this composite FK references (type_id, version) on
-- pipeline_type_registry, which only a UNIQUE INDEX covers. Emitted in
-- generated order the migration fails outright with "no unique constraint
-- matching given keys". Re-run of db:generate will reproduce the bad order.
CREATE UNIQUE INDEX "pipeline_type_registry_type_version_idx" ON "pipeline_type_registry" USING btree ("type_id","version");
--> statement-breakpoint
ALTER TABLE "lorebook_entries" ADD CONSTRAINT "lorebook_entries_type_fk" FOREIGN KEY ("type_id","type_version") REFERENCES "public"."pipeline_type_registry"("type_id","version") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lorebook_entry_vectors" ADD CONSTRAINT "lorebook_entry_vectors_entry_id_lorebook_entries_id_fk" FOREIGN KEY ("entry_id") REFERENCES "public"."lorebook_entries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_annotations" ADD CONSTRAINT "message_annotations_message_id_messages_id_fk" FOREIGN KEY ("message_id") REFERENCES "public"."messages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_annotations" ADD CONSTRAINT "message_annotations_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_annotations" ADD CONSTRAINT "message_annotations_persona_id_personas_id_fk" FOREIGN KEY ("persona_id") REFERENCES "public"."personas"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_annotations" ADD CONSTRAINT "message_annotations_ref_entry_id_lorebook_entries_id_fk" FOREIGN KEY ("ref_entry_id") REFERENCES "public"."lorebook_entries"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_parts" ADD CONSTRAINT "message_parts_message_id_messages_id_fk" FOREIGN KEY ("message_id") REFERENCES "public"."messages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_persona_id_personas_id_fk" FOREIGN KEY ("persona_id") REFERENCES "public"."personas"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_blocks" ADD CONSTRAINT "pipeline_blocks_spec_version_id_pipeline_spec_versions_id_fk" FOREIGN KEY ("spec_version_id") REFERENCES "public"."pipeline_spec_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_config_notices" ADD CONSTRAINT "pipeline_config_notices_config_id_pipeline_configs_id_fk" FOREIGN KEY ("config_id") REFERENCES "public"."pipeline_configs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_config_selections" ADD CONSTRAINT "pipeline_config_selections_spec_id_pipeline_specs_id_fk" FOREIGN KEY ("spec_id") REFERENCES "public"."pipeline_specs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_config_selections" ADD CONSTRAINT "pipeline_config_selections_config_id_pipeline_configs_id_fk" FOREIGN KEY ("config_id") REFERENCES "public"."pipeline_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_config_selections" ADD CONSTRAINT "pipeline_config_selections_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_config_values" ADD CONSTRAINT "pipeline_config_values_config_id_pipeline_configs_id_fk" FOREIGN KEY ("config_id") REFERENCES "public"."pipeline_configs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_configs" ADD CONSTRAINT "pipeline_configs_spec_id_pipeline_specs_id_fk" FOREIGN KEY ("spec_id") REFERENCES "public"."pipeline_specs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_context_templates" ADD CONSTRAINT "pipeline_context_templates_created_for_spec_id_pipeline_specs_id_fk" FOREIGN KEY ("created_for_spec_id") REFERENCES "public"."pipeline_specs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_edges" ADD CONSTRAINT "pipeline_edges_spec_version_id_pipeline_spec_versions_id_fk" FOREIGN KEY ("spec_version_id") REFERENCES "public"."pipeline_spec_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_edges" ADD CONSTRAINT "pipeline_edges_from_node_id_pipeline_nodes_id_fk" FOREIGN KEY ("from_node_id") REFERENCES "public"."pipeline_nodes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_edges" ADD CONSTRAINT "pipeline_edges_to_node_id_pipeline_nodes_id_fk" FOREIGN KEY ("to_node_id") REFERENCES "public"."pipeline_nodes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_event_subscriptions" ADD CONSTRAINT "pipeline_event_subscriptions_spec_version_id_pipeline_spec_versions_id_fk" FOREIGN KEY ("spec_version_id") REFERENCES "public"."pipeline_spec_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_event_subscriptions" ADD CONSTRAINT "pipeline_event_subscriptions_preset_id_pipeline_presets_id_fk" FOREIGN KEY ("preset_id") REFERENCES "public"."pipeline_presets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_event_subscriptions" ADD CONSTRAINT "pipeline_event_subscriptions_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_function_bindings" ADD CONSTRAINT "pipeline_function_bindings_spec_id_pipeline_specs_id_fk" FOREIGN KEY ("spec_id") REFERENCES "public"."pipeline_specs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_function_bindings" ADD CONSTRAINT "pipeline_function_bindings_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_includes" ADD CONSTRAINT "pipeline_includes_spec_version_id_pipeline_spec_versions_id_fk" FOREIGN KEY ("spec_version_id") REFERENCES "public"."pipeline_spec_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_node_overrides" ADD CONSTRAINT "pipeline_node_overrides_spec_id_pipeline_specs_id_fk" FOREIGN KEY ("spec_id") REFERENCES "public"."pipeline_specs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_node_overrides" ADD CONSTRAINT "pipeline_node_overrides_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_node_rebinds" ADD CONSTRAINT "pipeline_node_rebinds_spec_id_pipeline_specs_id_fk" FOREIGN KEY ("spec_id") REFERENCES "public"."pipeline_specs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_node_rebinds" ADD CONSTRAINT "pipeline_node_rebinds_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_nodes" ADD CONSTRAINT "pipeline_nodes_spec_version_id_pipeline_spec_versions_id_fk" FOREIGN KEY ("spec_version_id") REFERENCES "public"."pipeline_spec_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_preset_values" ADD CONSTRAINT "pipeline_preset_values_preset_id_pipeline_presets_id_fk" FOREIGN KEY ("preset_id") REFERENCES "public"."pipeline_presets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_presets" ADD CONSTRAINT "pipeline_presets_spec_version_id_pipeline_spec_versions_id_fk" FOREIGN KEY ("spec_version_id") REFERENCES "public"."pipeline_spec_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_prompts" ADD CONSTRAINT "pipeline_prompts_created_for_spec_id_pipeline_specs_id_fk" FOREIGN KEY ("created_for_spec_id") REFERENCES "public"."pipeline_specs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_run_nodes" ADD CONSTRAINT "pipeline_run_nodes_run_id_pipeline_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."pipeline_runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_runs" ADD CONSTRAINT "pipeline_runs_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_runs" ADD CONSTRAINT "pipeline_runs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_runs" ADD CONSTRAINT "pipeline_runs_message_id_session_messages_id_fk" FOREIGN KEY ("message_id") REFERENCES "public"."session_messages"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_spec_versions" ADD CONSTRAINT "pipeline_spec_versions_spec_id_pipeline_specs_id_fk" FOREIGN KEY ("spec_id") REFERENCES "public"."pipeline_specs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plugin_rows" ADD CONSTRAINT "plugin_rows_plugin_id_plugins_plugin_id_fk" FOREIGN KEY ("plugin_id") REFERENCES "public"."plugins"("plugin_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "session_functions" ADD CONSTRAINT "session_functions_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_layout_presets" ADD CONSTRAINT "session_layout_presets_author_user_id_users_id_fk" FOREIGN KEY ("author_user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_panel_layouts" ADD CONSTRAINT "session_panel_layouts_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_panel_layouts" ADD CONSTRAINT "session_panel_layouts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_panel_layouts" ADD CONSTRAINT "session_panel_layouts_layout_preset_id_session_layout_presets_id_fk" FOREIGN KEY ("layout_preset_id") REFERENCES "public"."session_layout_presets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tunnels" ADD CONSTRAINT "tunnels_server_id_servers_id_fk" FOREIGN KEY ("server_id") REFERENCES "public"."servers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_totp" ADD CONSTRAINT "user_totp_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_totp_recovery_codes" ADD CONSTRAINT "user_totp_recovery_codes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "widget_styles" ADD CONSTRAINT "widget_styles_owner_user_id_users_id_fk" FOREIGN KEY ("owner_user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_invites_user_idx" ON "account_invites" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "connection_defaults_output_idx" ON "connection_defaults" USING btree ("output");--> statement-breakpoint
CREATE UNIQUE INDEX "connection_scripts_pair_idx" ON "connection_scripts" USING btree ("connection_id","script_id");--> statement-breakpoint
CREATE INDEX "connection_scripts_script_idx" ON "connection_scripts" USING btree ("script_id");--> statement-breakpoint
CREATE INDEX "entry_annotations_entity_idx" ON "entry_annotations" USING btree ("entity_key");--> statement-breakpoint
CREATE UNIQUE INDEX "files_user_hash_unique" ON "files" USING btree ("user_id","hash");--> statement-breakpoint
CREATE INDEX "files_character_idx" ON "files" USING btree ("character_id");--> statement-breakpoint
CREATE INDEX "files_persona_idx" ON "files" USING btree ("persona_id");--> statement-breakpoint
CREATE INDEX "files_session_idx" ON "files" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "files_message_idx" ON "files" USING btree ("message_id");--> statement-breakpoint
CREATE INDEX "lorebook_entries_book_type_idx" ON "lorebook_entries" USING btree ("lorebook_id","type_id");--> statement-breakpoint
CREATE INDEX "message_annotations_entity_idx" ON "message_annotations" USING btree ("entity_key");--> statement-breakpoint
CREATE UNIQUE INDEX "message_parts_addr_idx" ON "message_parts" USING btree ("message_id","step","revision","ordinal");--> statement-breakpoint
CREATE INDEX "messages_session_id_idx" ON "messages" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "messages_session_channel_idx" ON "messages" USING btree ("session_id","channel");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_blocks_version_block_idx" ON "pipeline_blocks" USING btree ("spec_version_id","block_id");--> statement-breakpoint
CREATE INDEX "pipeline_config_notices_config_idx" ON "pipeline_config_notices" USING btree ("config_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_config_selections_addr_idx" ON "pipeline_config_selections" USING btree ("spec_id","scope_kind","scope_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_config_values_addr_idx" ON "pipeline_config_values" USING btree ("config_id","node_key","slot","path");--> statement-breakpoint
CREATE INDEX "pipeline_config_values_config_idx" ON "pipeline_config_values" USING btree ("config_id");--> statement-breakpoint
CREATE INDEX "pipeline_configs_spec_idx" ON "pipeline_configs" USING btree ("spec_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_configs_spec_name_idx" ON "pipeline_configs" USING btree ("spec_id","name");--> statement-breakpoint
CREATE INDEX "pipeline_context_templates_node_type_idx" ON "pipeline_context_templates" USING btree ("node_type_id");--> statement-breakpoint
CREATE INDEX "pipeline_context_templates_spec_idx" ON "pipeline_context_templates" USING btree ("created_for_spec_id");--> statement-breakpoint
CREATE INDEX "pipeline_context_templates_pool_idx" ON "pipeline_context_templates" USING btree ("node_type_id","engine");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_context_templates_node_type_name_idx" ON "pipeline_context_templates" USING btree ("node_type_id","engine","name");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_context_templates_migrated_from_idx" ON "pipeline_context_templates" USING btree ("migrated_from_context_config_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_function_bindings_addr_idx" ON "pipeline_function_bindings" USING btree ("scope_kind","scope_id","genre_id","function_key");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_node_overrides_addr_idx" ON "pipeline_node_overrides" USING btree ("spec_id","scope_kind","scope_id","node_key","slot","path");--> statement-breakpoint
CREATE INDEX "pipeline_node_overrides_scope_idx" ON "pipeline_node_overrides" USING btree ("spec_id","scope_kind","scope_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_node_rebinds_addr_idx" ON "pipeline_node_rebinds" USING btree ("spec_id","scope_kind","scope_id","node_key");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_nodes_version_key_idx" ON "pipeline_nodes" USING btree ("spec_version_id","node_key");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_presets_version_slug_idx" ON "pipeline_presets" USING btree ("spec_version_id","slug");--> statement-breakpoint
CREATE INDEX "pipeline_prompts_pool_idx" ON "pipeline_prompts" USING btree ("node_type_id","slot");--> statement-breakpoint
CREATE INDEX "pipeline_prompts_spec_idx" ON "pipeline_prompts" USING btree ("created_for_spec_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_prompts_pool_name_idx" ON "pipeline_prompts" USING btree ("node_type_id","slot","name");--> statement-breakpoint
CREATE INDEX "pipeline_run_nodes_run_idx" ON "pipeline_run_nodes" USING btree ("run_id","seq");--> statement-breakpoint
CREATE INDEX "pipeline_runs_session_idx" ON "pipeline_runs" USING btree ("session_id","id");--> statement-breakpoint
CREATE INDEX "pipeline_runs_message_idx" ON "pipeline_runs" USING btree ("message_id");--> statement-breakpoint
CREATE INDEX "pipeline_scripts_type_idx" ON "pipeline_scripts" USING btree ("type_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_scripts_type_name_idx" ON "pipeline_scripts" USING btree ("type_id","name");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_spec_versions_spec_semver_idx" ON "pipeline_spec_versions" USING btree ("spec_id","semver");--> statement-breakpoint
CREATE INDEX "pipeline_variable_templates_variable_idx" ON "pipeline_variable_templates" USING btree ("variable_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_variable_templates_variable_name_idx" ON "pipeline_variable_templates" USING btree ("variable_id","engine","name");--> statement-breakpoint
CREATE UNIQUE INDEX "plugin_files_plugin_path_idx" ON "plugin_files" USING btree ("plugin_id","path");--> statement-breakpoint
CREATE INDEX "plugin_hook_invocations_plugin_idx" ON "plugin_hook_invocations" USING btree ("plugin_id","finished_at");--> statement-breakpoint
CREATE INDEX "plugin_hook_invocations_run_idx" ON "plugin_hook_invocations" USING btree ("run_id");--> statement-breakpoint
CREATE UNIQUE INDEX "plugin_rows_plugin_key_unique" ON "plugin_rows" USING btree ("plugin_id","key");--> statement-breakpoint
CREATE UNIQUE INDEX "session_functions_session_mode_fn_idx" ON "session_functions" USING btree ("session_id","genre_id","function_key");--> statement-breakpoint
CREATE INDEX "session_layout_presets_genre_idx" ON "session_layout_presets" USING btree ("genre_id");--> statement-breakpoint
CREATE INDEX "session_layout_presets_author_idx" ON "session_layout_presets" USING btree ("author_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "session_panel_layouts_user_session_idx" ON "session_panel_layouts" USING btree ("user_id","session_id");--> statement-breakpoint
CREATE INDEX "session_presets_genre_idx" ON "session_presets" USING btree ("genre_id");--> statement-breakpoint
CREATE UNIQUE INDEX "tunnels_one_enabled_per_server" ON "tunnels" USING btree ("server_id") WHERE "tunnels"."enabled";--> statement-breakpoint
CREATE UNIQUE INDEX "ui_translations_language_source_key_unique" ON "ui_translations" USING btree ("language","source_key");--> statement-breakpoint
CREATE INDEX "user_totp_recovery_codes_user_idx" ON "user_totp_recovery_codes" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "variants_file_variant_unique" ON "variants" USING btree ("file_id","variant");--> statement-breakpoint
CREATE INDEX "variants_file_idx" ON "variants" USING btree ("file_id");--> statement-breakpoint
CREATE INDEX "variants_cache_idx" ON "variants" USING btree ("cache");--> statement-breakpoint
CREATE INDEX "widget_styles_widget_idx" ON "widget_styles" USING btree ("widget_slug");--> statement-breakpoint
CREATE INDEX "widget_styles_owner_idx" ON "widget_styles" USING btree ("owner_user_id");--> statement-breakpoint
ALTER TABLE "session_characters" ADD CONSTRAINT "session_characters_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_characters" ADD CONSTRAINT "session_characters_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_guests" ADD CONSTRAINT "session_guests_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_guests" ADD CONSTRAINT "session_guests_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_lorebooks" ADD CONSTRAINT "session_lorebooks_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_lorebooks" ADD CONSTRAINT "session_lorebooks_lorebook_id_lorebooks_id_fk" FOREIGN KEY ("lorebook_id") REFERENCES "public"."lorebooks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_messages" ADD CONSTRAINT "session_messages_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_messages" ADD CONSTRAINT "session_messages_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_messages" ADD CONSTRAINT "session_messages_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_messages" ADD CONSTRAINT "session_messages_persona_id_personas_id_fk" FOREIGN KEY ("persona_id") REFERENCES "public"."personas"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_personas" ADD CONSTRAINT "session_personas_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_personas" ADD CONSTRAINT "session_personas_persona_id_personas_id_fk" FOREIGN KEY ("persona_id") REFERENCES "public"."personas"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_tags" ADD CONSTRAINT "session_tags_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_tags" ADD CONSTRAINT "session_tags_tag_id_tags_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_lorebook_id_lorebooks_id_fk" FOREIGN KEY ("lorebook_id") REFERENCES "public"."lorebooks"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_connection_id_connections_id_fk" FOREIGN KEY ("connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_sampling_config_id_sampling_configs_id_fk" FOREIGN KEY ("sampling_config_id") REFERENCES "public"."sampling_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_prompt_config_id_prompt_configs_id_fk" FOREIGN KEY ("prompt_config_id") REFERENCES "public"."prompt_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_narrator_prompt_config_id_narrator_prompt_configs_id_fk" FOREIGN KEY ("narrator_prompt_config_id") REFERENCES "public"."narrator_prompt_configs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lorebook_bindings" ADD CONSTRAINT "lorebook_bindings_history_entry_id_lorebook_entries_id_fk" FOREIGN KEY ("history_entry_id") REFERENCES "public"."lorebook_entries"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "narrative_relationships" ADD CONSTRAINT "narrative_relationships_history_entry_id_lorebook_entries_id_fk" FOREIGN KEY ("history_entry_id") REFERENCES "public"."lorebook_entries"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scenes" ADD CONSTRAINT "scenes_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scenes" ADD CONSTRAINT "scenes_history_entry_id_lorebook_entries_id_fk" FOREIGN KEY ("history_entry_id") REFERENCES "public"."lorebook_entries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_settings" ADD CONSTRAINT "system_settings_active_embedding_connection_id_connections_id_fk" FOREIGN KEY ("active_embedding_connection_id") REFERENCES "public"."connections"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "session_characters_pk" ON "session_characters" USING btree ("session_id","character_id");--> statement-breakpoint
CREATE INDEX "session_characters_character_id_idx" ON "session_characters" USING btree ("character_id");--> statement-breakpoint
CREATE UNIQUE INDEX "session_guests_pk" ON "session_guests" USING btree ("session_id","user_id");--> statement-breakpoint
CREATE INDEX "session_messages_session_id_idx" ON "session_messages" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "session_messages_session_channel_idx" ON "session_messages" USING btree ("session_id","channel");--> statement-breakpoint
CREATE UNIQUE INDEX "session_personas_pk" ON "session_personas" USING btree ("session_id","persona_id");--> statement-breakpoint
CREATE INDEX "session_personas_persona_id_idx" ON "session_personas" USING btree ("persona_id");--> statement-breakpoint
CREATE UNIQUE INDEX "session_tags_unique" ON "session_tags" USING btree ("session_id","tag_id");--> statement-breakpoint
CREATE INDEX "sessions_user_id_idx" ON "sessions" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "sampling_configs_modality_name_unique" ON "sampling_configs" USING btree (split_part(split_part("shape", '/', 2), '@', 1),lower(btrim("name")));--> statement-breakpoint
CREATE INDEX "scenes_session_id_idx" ON "scenes" USING btree ("session_id");--> statement-breakpoint
ALTER TABLE "characters" DROP COLUMN "avatar";--> statement-breakpoint
ALTER TABLE "characters" DROP COLUMN "assets";--> statement-breakpoint
ALTER TABLE "session_characters" DROP COLUMN "chat_id";--> statement-breakpoint
ALTER TABLE "session_guests" DROP COLUMN "chat_id";--> statement-breakpoint
ALTER TABLE "session_lorebooks" DROP COLUMN "chat_id";--> statement-breakpoint
ALTER TABLE "session_messages" DROP COLUMN "chat_id";--> statement-breakpoint
ALTER TABLE "session_personas" DROP COLUMN "chat_id";--> statement-breakpoint
ALTER TABLE "session_tags" DROP COLUMN "chat_id";--> statement-breakpoint
ALTER TABLE "sessions" DROP COLUMN "chat_type";--> statement-breakpoint
ALTER TABLE "personas" DROP COLUMN "avatar";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "temperature";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "temperature_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "top_p";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "top_p_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "top_k";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "top_k_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "repetition_penalty";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "repetition_penalty_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "frequency_penalty";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "frequency_penalty_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "presence_penalty";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "presence_penalty_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "response_tokens";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "response_tokens_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "response_tokens_unlocked";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "context_tokens";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "context_tokens_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "context_tokens_unlocked";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "seed";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "seed_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "min_p";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "min_p_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "typical_p";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "typical_p_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "mirostat";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "mirostat_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "mirostat_tau";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "mirostat_tau_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "mirostat_eta";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "mirostat_eta_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "xtc_probability";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "xtc_probability_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "xtc_threshold";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "xtc_threshold_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "dry_multiplier";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "dry_multiplier_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "dry_base";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "dry_base_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "dry_allowed_length";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "dry_allowed_length_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "dry_penalty_last_n";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "dry_penalty_last_n_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "dry_sequence_breakers";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "dry_sequence_breakers_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "dynatemp_range";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "dynatemp_range_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "dynatemp_exponent";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "dynatemp_exponent_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "tfs_z";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "tfs_z_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "repeat_last_n";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "repeat_last_n_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "penalize_newline";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "penalize_newline_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "logit_bias";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "logit_bias_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "stop";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "stop_enabled";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "max_tokens";--> statement-breakpoint
ALTER TABLE "sampling_configs" DROP COLUMN "max_tokens_enabled";--> statement-breakpoint
ALTER TABLE "scenes" DROP COLUMN "chat_id";--> statement-breakpoint
ALTER TABLE "system_settings" DROP COLUMN "default_connection_id";--> statement-breakpoint
ALTER TABLE "system_settings" DROP COLUMN "default_sampling_id";