CREATE TABLE "completion_templates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "completion_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"seed_key" text,
	"key" text NOT NULL,
	"name" text NOT NULL,
	"is_immutable" boolean DEFAULT false NOT NULL,
	"render_mode" text DEFAULT 'flat' NOT NULL,
	"roles" json DEFAULT '{}'::json NOT NULL,
	"fallback_role" json DEFAULT '{"prefix":"","suffix":""}'::json NOT NULL,
	"stop_strings" json DEFAULT '[]'::json NOT NULL,
	"is_selectable" boolean DEFAULT true NOT NULL,
	CONSTRAINT "completion_templates_seed_key_unique" UNIQUE("seed_key"),
	CONSTRAINT "completion_templates_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE INDEX "completion_templates_selectable_idx" ON "completion_templates" USING btree ("is_selectable");--> statement-breakpoint

--> statement-breakpoint
-- ─── DML, and it has to sit HERE rather than at the end of the file ─────────
--
-- The foreign key below is added LAST, after both statements in this section.
-- That ordering is the one hand-edit to the generated file and it is load
-- bearing twice over:
--
--   1. `completion_templates` is empty the moment it is created. The seed rows
--      are written by `db/defaults.ts` at BOOT, which is after migrations run —
--      so adding the key first would find no parent row for any of the
--      `prompt_format` values every existing connection already holds, and
--      `ON DELETE SET NULL` does not help: it governs deletes, not the
--      constraint's initial validation. The ADD CONSTRAINT would simply fail
--      and the upgrade would abort.
--   2. Even seeded, the key would reject the values that are in the column and
--      name no template — `''` from a cleared field, `'tekken'` from a format
--      that was never selectable, anything an older build wrote. Those are
--      nulled below, deliberately and visibly, rather than being discovered as
--      a failed upgrade on someone's install.
--
-- Appending DML under generated DDL is the established pattern here (0096);
-- the snapshot models schema only, so none of this appears in it.

INSERT INTO "completion_templates"
	("seed_key", "key", "name", "is_immutable", "render_mode", "roles", "fallback_role", "stop_strings", "is_selectable")
VALUES
	('completion-template-vicuna', 'vicuna', 'Vicuna (Default)', true, 'flat', '{"system":{"prefix":"### System:\n","suffix":"\n"},"user":{"prefix":"### User:\n","suffix":"\n"},"assistant":{"prefix":"### Assistant:\n","suffix":"\n"},"model":{"prefix":"### Model:\n","suffix":"\n"},"tool":{"prefix":"### Tool:\n","suffix":"\n"},"function":{"prefix":"### Function:\n","suffix":"\n"}}', '{"prefix":"### User:\n","suffix":"\n"}', '["</s>","system:","System:","user:","User:","assistant:","Assistant:"]', true),
	('completion-template-chatml', 'chatml', 'ChatML', true, 'flat', '{"system":{"prefix":"<|im_start|>system\n","suffix":"<|im_end|>\n"},"user":{"prefix":"<|im_start|>user\n","suffix":"<|im_end|>\n"},"assistant":{"prefix":"<|im_start|>assistant\n","suffix":"<|im_end|>\n"},"model":{"prefix":"<|im_start|>model\n","suffix":"<|im_end|>\n"},"tool":{"prefix":"<|im_start|>tool\n","suffix":"<|im_end|>\n"},"function":{"prefix":"<|im_start|>function\n","suffix":"<|im_end|>\n"}}', '{"prefix":"<|im_start|>user\n","suffix":"<|im_end|>\n"}', '["<|im_start|>","<|im_end|>"]', true),
	('completion-template-basic', 'basic', 'Basic / Legacy', true, 'flat', '{"system":{"prefix":"*** system\n","suffix":"\n\n"},"user":{"prefix":"*** user\n","suffix":"\n\n"},"assistant":{"prefix":"*** assistant\n","suffix":"\n\n"},"model":{"prefix":"*** model\n","suffix":"\n\n"},"tool":{"prefix":"*** tool\n","suffix":"\n\n"},"function":{"prefix":"*** function\n","suffix":"\n\n"}}', '{"prefix":"*** user\n","suffix":"\n\n"}', '["system:","System:","user:","User:","assistant:","Assistant:"]', true),
	('completion-template-openai', 'openai', 'OpenAI', true, 'flat', '{"system":{"prefix":"<|system|>\n","suffix":"\n"},"user":{"prefix":"<|user|>\n","suffix":"\n"},"assistant":{"prefix":"<|assistant|>\n","suffix":"\n"},"model":{"prefix":"<|model|>\n","suffix":"\n"},"tool":{"prefix":"<|tool|>\n","suffix":"\n"},"function":{"prefix":"<|function|>\n","suffix":"\n"}}', '{"prefix":"<|user|>\n","suffix":"\n"}', '["system:","System:","user:","User:","assistant:","Assistant:"]', true),
	('completion-template-llama2_inst', 'llama2_inst', 'LLaMA2/Mistral Instruct', true, 'flat', '{"system":{"prefix":"<s>[INST] <<SYS>>\n","suffix":"\n<</SYS>> [/INST]</s>\n"},"user":{"prefix":"<s>\n","suffix":"\n</s>\n"},"assistant":{"prefix":"<s>\n","suffix":"\n</s>\n"},"model":{"prefix":"<s>[INST] ","suffix":" [/INST]</s>\n"},"tool":{"prefix":"<s>[INST] ","suffix":" [/INST]</s>\n"},"function":{"prefix":"<s>[INST] ","suffix":" [/INST]</s>\n"}}', '{"prefix":"<s>[INST] ","suffix":" [/INST]</s>\n"}', '["</s>","User:","Assistant:","System:"]', true),
	('completion-template-claude', 'claude', 'Claude (Human/Assistant)', true, 'flat', '{"user":{"prefix":"Human: ","suffix":"\n"},"system":{"prefix":"\nAssistant: ","suffix":"\n"},"assistant":{"prefix":"\nAssistant: ","suffix":"\n"},"model":{"prefix":"\nAssistant: ","suffix":"\n"},"tool":{"prefix":"\nAssistant: ","suffix":"\n"},"function":{"prefix":"\nAssistant: ","suffix":"\n"}}', '{"prefix":"\nAssistant: ","suffix":"\n"}', '["system:","System:","user:","User:","assistant:","Assistant:"]', true),
	('completion-template-instruct', 'instruct', 'Instruct (Alpaca)', true, 'flat', '{"system":{"prefix":"### Instruction:\n","suffix":"\n### Response:\n"},"user":{"prefix":"### Instruction:\n","suffix":"\n### Response:\n"},"assistant":{"prefix":"### Instruction:\n","suffix":"\n### Response:\n"},"model":{"prefix":"### Instruction:\n","suffix":"\n### Response:\n"},"tool":{"prefix":"### Instruction:\n","suffix":"\n### Response:\n"},"function":{"prefix":"### Instruction:\n","suffix":"\n### Response:\n"}}', '{"prefix":"### Instruction:\n","suffix":"\n### Response:\n"}', '["system:","System:","user:","User:","assistant:","Assistant:"]', true),
	('completion-template-split_session', 'split_session', 'Split Session (internal)', true, 'role_array', '{"system":{"prefix":"","suffix":""},"user":{"prefix":"","suffix":""},"assistant":{"prefix":"","suffix":""},"model":{"prefix":"","suffix":""},"tool":{"prefix":"","suffix":""},"function":{"prefix":"","suffix":""}}', '{"prefix":"","suffix":""}', '["system:","System:","user:","User:","assistant:","Assistant:"]', false)
ON CONFLICT ("key") DO NOTHING;
--> statement-breakpoint
-- Every `prompt_format` that names no template becomes NULL — "no template
-- chosen", which is what `completionTemplateOf` already answers with the
-- default. The alternative was to leave the values and drop the foreign key,
-- which keeps a string that renders as the default anyway while giving up the
-- one thing the key buys: that deleting a template cannot strand the
-- connections pointing at it.
--
-- ⚠ `''` is the case to watch. It is not the same as NULL to a reader of this
-- column, but it was never a different THING — `promptFormatOf` has always
-- treated a cleared format as an absent one, and the column having no check
-- constraint is how the empty string got in. After this, cleared is spelled
-- NULL and the database enforces it.
UPDATE "connections"
SET "prompt_format" = NULL
WHERE "prompt_format" IS NOT NULL
  AND "prompt_format" NOT IN (SELECT "key" FROM "completion_templates");
--> statement-breakpoint
ALTER TABLE "connections" ADD CONSTRAINT "connections_prompt_format_completion_templates_key_fk" FOREIGN KEY ("prompt_format") REFERENCES "public"."completion_templates"("key") ON DELETE set null ON UPDATE no action;
