CREATE TABLE "pipeline_run_nodes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_run_nodes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"run_id" integer NOT NULL,
	"seq" integer NOT NULL,
	"node_key" text NOT NULL,
	"kind" text NOT NULL,
	"type_id" text NOT NULL,
	"result" text NOT NULL,
	"reason" text,
	"elapsed_ms" integer DEFAULT 0 NOT NULL,
	"tokens" integer,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pipeline_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"run_id" text NOT NULL,
	"spec_slug" text NOT NULL,
	"spec_version" text NOT NULL,
	"spec_version_id" integer,
	"chat_id" integer,
	"user_id" integer,
	"message_id" integer,
	"outcome" text NOT NULL,
	"halt_node_key" text,
	"halt_reason" text,
	"trigger_source" text NOT NULL,
	"seed" text NOT NULL,
	"is_preview" boolean DEFAULT false NOT NULL,
	"started_at" timestamp NOT NULL,
	"ended_at" timestamp NOT NULL,
	"elapsed_ms" integer DEFAULT 0 NOT NULL,
	"tokens_spent" integer DEFAULT 0 NOT NULL,
	"receipt" json NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_runs_run_id_unique" UNIQUE("run_id")
);
--> statement-breakpoint
ALTER TABLE "pipeline_run_nodes" ADD CONSTRAINT "pipeline_run_nodes_run_id_pipeline_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."pipeline_runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_runs" ADD CONSTRAINT "pipeline_runs_chat_id_chats_id_fk" FOREIGN KEY ("chat_id") REFERENCES "public"."chats"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_runs" ADD CONSTRAINT "pipeline_runs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_runs" ADD CONSTRAINT "pipeline_runs_message_id_chat_messages_id_fk" FOREIGN KEY ("message_id") REFERENCES "public"."chat_messages"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "pipeline_run_nodes_run_idx" ON "pipeline_run_nodes" USING btree ("run_id","seq");--> statement-breakpoint
CREATE INDEX "pipeline_runs_chat_idx" ON "pipeline_runs" USING btree ("chat_id","id");--> statement-breakpoint
CREATE INDEX "pipeline_runs_message_idx" ON "pipeline_runs" USING btree ("message_id");