CREATE TABLE "pipeline_config_selections" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_config_selections_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_id" integer NOT NULL,
	"scope_kind" text NOT NULL,
	"scope_id" integer DEFAULT 0 NOT NULL,
	"preset_slug" text NOT NULL,
	"updated_by" integer,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_config_selections_scope_check" CHECK ("pipeline_config_selections"."scope_kind" IN ('instance', 'user', 'chat'))
);
--> statement-breakpoint
CREATE TABLE "pipeline_node_overrides" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_node_overrides_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_id" integer NOT NULL,
	"scope_kind" text NOT NULL,
	"scope_id" integer DEFAULT 0 NOT NULL,
	"node_key" text NOT NULL,
	"slot" text NOT NULL,
	"path" text DEFAULT '' NOT NULL,
	"value" json,
	"updated_by" integer,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_node_overrides_scope_check" CHECK ("pipeline_node_overrides"."scope_kind" IN ('instance', 'user', 'chat'))
);
--> statement-breakpoint
ALTER TABLE "pipeline_config_selections" ADD CONSTRAINT "pipeline_config_selections_spec_id_pipeline_specs_id_fk" FOREIGN KEY ("spec_id") REFERENCES "public"."pipeline_specs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_config_selections" ADD CONSTRAINT "pipeline_config_selections_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_node_overrides" ADD CONSTRAINT "pipeline_node_overrides_spec_id_pipeline_specs_id_fk" FOREIGN KEY ("spec_id") REFERENCES "public"."pipeline_specs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_node_overrides" ADD CONSTRAINT "pipeline_node_overrides_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_config_selections_addr_idx" ON "pipeline_config_selections" USING btree ("spec_id","scope_kind","scope_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_node_overrides_addr_idx" ON "pipeline_node_overrides" USING btree ("spec_id","scope_kind","scope_id","node_key","slot","path");--> statement-breakpoint
CREATE INDEX "pipeline_node_overrides_scope_idx" ON "pipeline_node_overrides" USING btree ("spec_id","scope_kind","scope_id");--> statement-breakpoint
-- Re-materialize the type registry.
--
-- `pipeline_type_registry.slots` used to store `{"params": true, "prompts": true}`
-- — the slot *names*. It now stores the declarations, because 12 §2 has the UI
-- generate its forms from these rows rather than from the in-process descriptor
-- map, which does not exist for a plugin type core has not executed (F6).
--
-- The content hash covers slot declarations, so every existing row's hash is now
-- stale, and `syncTypeRegistry` refuses rather than reconciling — correctly: a
-- type whose stored content disagrees with the code is either a rewritten pin or
-- a bug, and it cannot tell which. Here it is neither. This table is a projection
-- of the running build, seeded at boot and referenced only by text pins, so
-- emptying it is a re-projection and not a data loss.
--
-- This is a one-time correction of the projection's own shape, not a pattern.
-- Clearing this table on an upgrade that had *not* changed the projection would
-- destroy the guard 02 §3 depends on.
DELETE FROM "pipeline_type_registry";
