CREATE TABLE "pipeline_config_values" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_config_values_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"config_id" integer NOT NULL,
	"node_key" text NOT NULL,
	"slot" text NOT NULL,
	"path" text DEFAULT '' NOT NULL,
	"value" json,
	"engine" text
);
--> statement-breakpoint
CREATE TABLE "pipeline_configs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_configs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_id" integer NOT NULL,
	"seed_key" text,
	"name" text NOT NULL,
	"is_immutable" boolean DEFAULT false NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_configs_seed_key_unique" UNIQUE("seed_key")
);
--> statement-breakpoint
ALTER TABLE "pipeline_config_values" ADD CONSTRAINT "pipeline_config_values_config_id_pipeline_configs_id_fk" FOREIGN KEY ("config_id") REFERENCES "public"."pipeline_configs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_configs" ADD CONSTRAINT "pipeline_configs_spec_id_pipeline_specs_id_fk" FOREIGN KEY ("spec_id") REFERENCES "public"."pipeline_specs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_config_values_addr_idx" ON "pipeline_config_values" USING btree ("config_id","node_key","slot","path");--> statement-breakpoint
CREATE INDEX "pipeline_config_values_config_idx" ON "pipeline_config_values" USING btree ("config_id");--> statement-breakpoint
CREATE INDEX "pipeline_configs_spec_idx" ON "pipeline_configs" USING btree ("spec_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_configs_spec_name_idx" ON "pipeline_configs" USING btree ("spec_id","name");