CREATE TABLE "pipeline_config_notices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_config_notices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"config_id" integer NOT NULL,
	"kind" text NOT NULL,
	"node_key" text NOT NULL,
	"slot" text NOT NULL,
	"path" text DEFAULT '' NOT NULL,
	"label" text,
	"previous_value" json,
	"spec_version_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"acknowledged_at" timestamp,
	CONSTRAINT "pipeline_config_notices_kind_check" CHECK ("pipeline_config_notices"."kind" IN ('culled', 'backfilled'))
);
--> statement-breakpoint
ALTER TABLE "pipeline_config_notices" ADD CONSTRAINT "pipeline_config_notices_config_id_pipeline_configs_id_fk" FOREIGN KEY ("config_id") REFERENCES "public"."pipeline_configs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "pipeline_config_notices_config_idx" ON "pipeline_config_notices" USING btree ("config_id");