CREATE TABLE "pipeline_prompts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_prompts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_id" integer NOT NULL,
	"seed_key" text,
	"name" text NOT NULL,
	"is_immutable" boolean DEFAULT false NOT NULL,
	"fields" json DEFAULT '{}'::json NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_prompts_seed_key_unique" UNIQUE("seed_key")
);
--> statement-breakpoint
ALTER TABLE "pipeline_prompts" ADD CONSTRAINT "pipeline_prompts_spec_id_pipeline_specs_id_fk" FOREIGN KEY ("spec_id") REFERENCES "public"."pipeline_specs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "pipeline_prompts_spec_idx" ON "pipeline_prompts" USING btree ("spec_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_prompts_spec_name_idx" ON "pipeline_prompts" USING btree ("spec_id","name");