CREATE TABLE "binding_suggestions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "binding_suggestions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lorebook_id" integer NOT NULL,
	"entity_key" text NOT NULL,
	"surface" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"occurrences" integer DEFAULT 0 NOT NULL,
	"source_count" integer DEFAULT 0 NOT NULL,
	"first_seen_at" timestamp DEFAULT now() NOT NULL,
	"last_seen_at" timestamp DEFAULT now() NOT NULL,
	"example_context" text DEFAULT '' NOT NULL,
	"example_source_kind" text DEFAULT '' NOT NULL,
	"example_source_id" integer,
	"resolved_binding_id" integer,
	"decided_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "binding_suggestions" ADD CONSTRAINT "binding_suggestions_lorebook_id_lorebooks_id_fk" FOREIGN KEY ("lorebook_id") REFERENCES "public"."lorebooks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "binding_suggestions" ADD CONSTRAINT "binding_suggestions_resolved_binding_id_lorebook_bindings_id_fk" FOREIGN KEY ("resolved_binding_id") REFERENCES "public"."lorebook_bindings"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "binding_suggestions_book_key_uq" ON "binding_suggestions" USING btree ("lorebook_id","entity_key");--> statement-breakpoint
CREATE INDEX "binding_suggestions_book_status_idx" ON "binding_suggestions" USING btree ("lorebook_id","status");