-- The scene summarizer stops asking a model who was in the scene.
--
-- Ruled 2026-09-08 (plan §2). The cast extraction is put **on ice**, not
-- deleted: `core:provider/extract-cast@1`, its shipped prompt and the
-- `extractsCast` branch in the catalog all stay exactly where they are. What
-- changes is that `core:spec/summarize-scene` no longer wires the `cast`
-- Provider into its document, so a scene summary costs one fewer LLM call and
-- proposes a cast nobody measured.
--
-- ── Why ────────────────────────────────────────────────────────────────────
--
-- The measured replacement for the *participant* half — the roster unioned with
-- speech-gated textual extraction — scored 100% precision at 88.5% recall from
-- the sender side and 96.2% recall from the roster side, with zero fabricated
-- people in any configuration, over 40,000 turns in ~661ms and no model at all.
-- Its failure profile is omission, categorically unlike the 24% fabrication that
-- got the acts layer rejected. Participants keep coming from where they already
-- came from on this path in the meantime: every distinct sender in the scene's
-- message span is made a participant by `sockets/scenes.ts` and
-- `sockets/summarize.ts` regardless of what any extraction said, and the graph
-- build keeps its own Pass 1 extraction for a scene with no stored cast at all.
--
-- The *mentioned* half is not coming back in this shape at all: it is derived
-- from `message_annotations` now — exactly (scene text × vocabulary), with the
-- freshness triple invalidating it — rather than asked of a model and stored a
-- second time at scene granularity.
--
-- ── ⚠ Why an SQL file is needed for a TypeScript edit ──────────────────────
--
-- The spec version does NOT move: the 0.6 pre-release froze SDK spec versions,
-- so the document change is an edit in place under `1.3.0`. Seeding matches on
-- `(slug, semver)` and, on a match, updates only the display name
-- (`boot/seed.ts` pass 1, and `bootstrap.ts`: "spec publishing is idempotent by
-- version"). So the edited document would reach NO database that has already
-- seeded — every developer machine and every upgrading install — and would be
-- invisible on a fresh test database, where the row does not exist and the edit
-- publishes normally. Deleting the version row is what makes boot republish it.
--
-- Precedent and terms: `0095_prompt_format_reprojection` and
-- `0100_narration_split_reprojection`, which did exactly this for the same pin.
-- `pipeline_nodes`, `pipeline_edges`, `pipeline_blocks`, `pipeline_includes`,
-- `pipeline_event_subscriptions` and `pipeline_presets` all cascade from
-- `pipeline_spec_versions`, so the old document goes cleanly. What is LOST with
-- it, stated rather than discovered: the author presets shipped with this
-- version, and any per-subscription `enabled` flag somebody had turned off.
-- `pipeline_configs` hangs off `pipeline_specs`, not off a version, so tuned
-- configurations survive — and `reconcileConfigs` re-runs against the
-- republished version on the same boot, which is what records a notice for the
-- `cast` node's connection/sampling/prompt declarations that the reshape culls.
-- `pipeline_specs.active_version_id` is not a foreign key; it dangles for
-- exactly as long as it takes boot to republish and move the pointer, in the
-- same startup that runs this file.
--
-- ⚠ Only `core:spec/summarize-scene` is deleted. `SUMMARIZE_VERSION` is shared
-- by all four summarize namespaces, so a delete keyed on the semver alone would
-- re-project world, character and history for no reason.
--
-- ⚠ No `pipeline_type_registry` row is deleted, and that is deliberate. No type
-- declaration moved — `core:provider/extract-cast@1` is untouched, which is what
-- makes this revivable — so deleting rows that did not change would throw away
-- nothing and prove nothing.
--
-- ⚠ This must not become a pattern (13 §12b). Once 0.6.0 ships, a changed type
-- or spec is a new version, never a rewrite of the row.
DELETE FROM "pipeline_spec_versions"
WHERE "id" IN (
	SELECT "v"."id"
	FROM "pipeline_spec_versions" "v"
	JOIN "pipeline_specs" "s" ON "s"."id" = "v"."spec_id"
	WHERE "s"."slug" = 'core:spec/summarize-scene' AND "v"."semver" = '1.3.0'
);
