CREATE TABLE "pipeline_variable_templates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_variable_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"variable_id" text NOT NULL,
	"engine" text,
	"name" text NOT NULL,
	"source" text DEFAULT '' NOT NULL,
	"seed_key" text,
	"is_immutable" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_variable_templates_seed_key_unique" UNIQUE("seed_key")
);
--> statement-breakpoint
CREATE INDEX "pipeline_variable_templates_variable_idx" ON "pipeline_variable_templates" USING btree ("variable_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_variable_templates_variable_name_idx" ON "pipeline_variable_templates" USING btree ("variable_id","name");--> statement-breakpoint
-- Written by hand, on the 0099/0106 precedent and just as deliberately narrow.
--
-- `core:task/build-template-context@1` gained a `variables` slot declaring which
-- context variable each of its outputs renders. That changes the type's content
-- hash, and a published version is frozen — so on any database that booted a
-- previous build, `syncTypeRegistry` would raise `TypeRegistryConflictError`,
-- `bootstrapPipelines` would catch it and return early, and **pipelines would
-- silently stop**: no specs seeded, no migration run, and nothing on screen
-- except a line on the diagnostics page.
--
-- Deleting the row lets boot re-project the current declaration. Safe only
-- because nothing outside this repo has pinned this version — the 0.6 line is
-- still in preview. Once 0.6.0 ships, a changed type is a new version, never a
-- rewrite of the row (13 §12b).
--
-- `registryHashes.test.ts` records the new hash in the same commit as this file.
-- That pairing is the point: the test is what makes a missing re-projection a
-- red suite instead of a support ticket.
DELETE FROM "pipeline_type_registry"
WHERE "type_id" = 'core:task/build-template-context'
AND "version" = 1;