-- A run's output becomes relational: `pipeline_runs.message_id` → `pipeline_run_artifacts`.
--
-- Ruled 2026-09-08: *"The schema is wrong if it only reflects one message. It's
-- possible that multiple messages might become a result of a pipeline. Messages
-- should be relational artifacts."*
--
-- ── What the single column could not say ───────────────────────────────────
--
-- `message_id` held at most one id, so every run that produced anything else
-- produced it invisibly:
--
--   * `core:consumer/seed-greetings` writes **N** messages. The column recorded
--     none of them — `writtenMessageId` read only the first committed
--     consumer's `output.ids.id`, and that consumer publishes `ids[]`.
--   * `core:provider/generate-image` writes N `files` and N `variants` through
--     `createMedia`, with the run id stored nowhere at all.
--   * `core:consumer/create-message` posts media parts beside its message.
--   * `core:consumer/create-lore-entry` writes a `lorebook_entries` row the run
--     was entirely invisible to.
--
-- ── ⚠ `entity_id` carries no foreign key, deliberately ─────────────────────
--
-- An artifact row is *evidence that this run made something*. Deleting the
-- thing afterwards must not delete the evidence — the same rule that keeps
-- `pipeline_runs.spec_version_id` FK-free ("a run happened; a spec being
-- retired later does not unhappen it") and that `files` follows for its own
-- provenance columns. A cascade here would let tidying a session silently
-- rewrite what the audit trail says happened.
--
-- `run_id` DOES cascade, because an artifact of a run that no longer exists is
-- not evidence of anything.
--
-- ── The backfill ───────────────────────────────────────────────────────────
--
-- Every row that had a message keeps it, as `('message', id, 'created')` at
-- seq 0. Runs with a null `message_id` produced nothing the old schema could
-- record and get no artifact row — which is exactly what `is_preview` already
-- says about them.
CREATE TABLE "pipeline_run_artifacts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_run_artifacts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"run_id" integer NOT NULL,
	"seq" integer NOT NULL,
	"kind" text NOT NULL,
	"entity_id" integer NOT NULL,
	"action" text NOT NULL,
	"node_key" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_run_artifacts_unique" UNIQUE("run_id","kind","entity_id","action")
);
--> statement-breakpoint
ALTER TABLE "pipeline_run_artifacts" ADD CONSTRAINT "pipeline_run_artifacts_run_id_pipeline_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."pipeline_runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "pipeline_run_artifacts_run_idx" ON "pipeline_run_artifacts" USING btree ("run_id","seq");--> statement-breakpoint
CREATE INDEX "pipeline_run_artifacts_entity_idx" ON "pipeline_run_artifacts" USING btree ("kind","entity_id");--> statement-breakpoint
INSERT INTO "pipeline_run_artifacts" ("run_id", "seq", "kind", "entity_id", "action")
SELECT "id", 0, 'message', "message_id", 'created'
FROM "pipeline_runs"
WHERE "message_id" IS NOT NULL;--> statement-breakpoint
ALTER TABLE "pipeline_runs" DROP CONSTRAINT "pipeline_runs_message_id_session_messages_id_fk";
--> statement-breakpoint
DROP INDEX "pipeline_runs_message_idx";--> statement-breakpoint
ALTER TABLE "pipeline_runs" DROP COLUMN "message_id";
