CREATE TABLE "pipeline_context_templates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_context_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"node_type_id" text NOT NULL,
	"created_for_spec_id" integer,
	"engine" text,
	"name" text NOT NULL,
	"source" text DEFAULT '' NOT NULL,
	"seed_key" text,
	"is_immutable" boolean DEFAULT false NOT NULL,
	"migrated_from_context_config_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_context_templates_seed_key_unique" UNIQUE("seed_key")
);
--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "context_templates_migrated" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "pipeline_context_templates" ADD CONSTRAINT "pipeline_context_templates_created_for_spec_id_pipeline_specs_id_fk" FOREIGN KEY ("created_for_spec_id") REFERENCES "public"."pipeline_specs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "pipeline_context_templates_node_type_idx" ON "pipeline_context_templates" USING btree ("node_type_id");--> statement-breakpoint
CREATE INDEX "pipeline_context_templates_spec_idx" ON "pipeline_context_templates" USING btree ("created_for_spec_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_context_templates_node_type_name_idx" ON "pipeline_context_templates" USING btree ("node_type_id","name");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_context_templates_migrated_from_idx" ON "pipeline_context_templates" USING btree ("migrated_from_context_config_id");