CREATE TABLE "connection_models" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "connection_models_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"connection_id" integer NOT NULL,
	"model" text NOT NULL,
	"name" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"capabilities" json DEFAULT '{}'::json NOT NULL,
	"context_window" integer,
	"prompt_format" text,
	"token_counter" text,
	"extra_json" json DEFAULT '{}'::json NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "connection_models_identifiers_check" CHECK ("connection_models"."model" <> '' AND "connection_models"."name" <> '')
);
--> statement-breakpoint
ALTER TABLE "connection_defaults" ADD COLUMN "connection_model_id" integer;--> statement-breakpoint
ALTER TABLE "connection_models" ADD CONSTRAINT "connection_models_connection_id_connections_id_fk" FOREIGN KEY ("connection_id") REFERENCES "public"."connections"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "connection_models" ADD CONSTRAINT "connection_models_prompt_format_completion_templates_key_fk" FOREIGN KEY ("prompt_format") REFERENCES "public"."completion_templates"("key") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "connection_models_one_default" ON "connection_models" USING btree ("connection_id") WHERE "connection_models"."is_default";--> statement-breakpoint
CREATE UNIQUE INDEX "connection_models_endpoint_model" ON "connection_models" USING btree ("connection_id","model");--> statement-breakpoint
ALTER TABLE "connection_defaults" ADD CONSTRAINT "connection_defaults_connection_model_id_connection_models_id_fk" FOREIGN KEY ("connection_model_id") REFERENCES "public"."connection_models"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
-- ===== 0114 BACKFILL =====
--
-- Every connection that named a model becomes an endpoint with exactly ONE
-- model on it: the one it already named, marked default, enabled.
--
-- ⚠ It copies the IDENTIFIER and nothing else. `prompt_format`,
-- `token_counter`, `context_window`, `capabilities` and `extra_json` all stay at
-- their defaults on the new row, and every one of those is read as "whatever the
-- endpoint says" — so the merged (endpoint, model) pair this produces is
-- byte-identical to the row it replaces, for every install, on the first request
-- after the upgrade. Copying the endpoint's settings DOWN would look like
-- thoroughness and would in fact pin them at upgrade time: editing the
-- endpoint's completion template would then stop reaching its own model,
-- silently, with the screen showing the new value and the wire carrying the old.
--
-- `name` is the identifier too. A person who has never renamed anything sees the
-- string they have always seen; the column exists so somebody running four
-- quantisations of one model can tell them apart by something other than a
-- filename suffix.
--
-- ⚠ `WHERE model <> ''` as well as NOT NULL, and both are load-bearing.
-- `connection_models_identifiers_check` refuses an empty identifier, so a row
-- whose model column was cleared by a form field would abort the entire
-- migration — for everybody, at boot, with an error naming a check constraint
-- rather than the connection that caused it. NULL and '' mean the same thing
-- here anyway: nobody finished setting this endpoint up, and inventing a model
-- row for it would make an unusable connection look configured in every picker.
--
-- `ON CONFLICT DO NOTHING` against the (connection_id, model) unique index, so a
-- replay — a restored backup applied over a partly-upgraded database — adds
-- nothing rather than failing. Without it the second run would hit the partial
-- unique index on `is_default` instead, which is a much worse sentence to read.
INSERT INTO "connection_models" (
	"connection_id", "model", "name", "is_default", "enabled", "sort_order"
)
SELECT "id", "model", "model", true, true, 0
FROM "connections"
WHERE "model" IS NOT NULL AND "model" <> ''
ON CONFLICT DO NOTHING;
