-- **A pipeline config stores deviations, not values** (ruled 2026-09-10), and
-- the last of the three slot-wiring shapes, which travels with it because both
-- land on the same three documents and splitting them would mean deleting the
-- same rows twice.
--
-- ── 1. The ruling, and where its data work actually happens ────────────────
--
-- `pipeline_config_values` has held one row per DECLARED ADDRESS per config
-- since configs existed: `ensureDefaultConfig` materialized every declaration
-- into the shipped default, and `reconcileConfigs` back-filled every new one
-- into every copy. Three consequences, all of them defects:
--
--   · **Provenance was unknowable.** A row said nothing about whether a person
--     chose the number in it or whether the install's first boot wrote it.
--     There is no provenance column, and adding one would only record what the
--     row's own EXISTENCE can say once the seeding half stops lying.
--   · **A corrected default reached nobody.** Every config already held a copy
--     of the old one. That is why `0102`, `0110` and `0111` each end with a
--     bespoke DELETE over this table: three hand-written sweeps for the same
--     structural reason, each found by hand after the fact.
--   · **"Back to defaults" had to be a write.** `clearOption` has deleted since
--     F20. Seeding was the half that kept re-materializing what it deleted.
--
-- So a row now exists only where the value DEPARTS from what the published
-- declaration says, and everything else resolves at the SDK resolver's `author`
-- layer — which the app populates for the first time in this change
-- (`config/world.ts`, one projection serving the executor, `stepConfig.ts` and
-- the graph builder alike).
--
-- ⚠ **There is deliberately no `DELETE FROM pipeline_config_values` here, and
-- that is a decision rather than an omission.** The sweep cannot be written in
-- SQL without re-implementing `config/panel/declarations.ts` in it, and a second
-- implementation of "what does this pipeline declare" is precisely the class of
-- disagreement this layer keeps closing. Three of the things it would have to
-- reproduce exist ONLY in code and appear in no column of any table:
--
--   · the synthesized `settings.review` (`authorDefault 'off'`, emitted for
--     every node whose registry row says `effects` is write or external) and
--     `settings.enabled` (`true`, for every `optional` node);
--   · a block's `settings.mode`, whose default is the block row's own `mode`;
--   · the rule that a slot wired to ANOTHER node (`__ref: 'slot'` with an
--     `ofNode`) is not this node's to configure and declares nothing at all.
--
-- A partial SQL sweep that got the `parameters` half from
-- `pipeline_type_registry.slots->…->'default'` and missed those three would be
-- worse than none: it would leave exactly the rows whose absence is hardest to
-- notice, while looking like the job was done.
--
-- **What does it instead:** `reconcileConfigs` (`config/named.ts`), which
-- `seedCoreSpecs` calls for every spec on EVERY boot — "Runs for present specs
-- as well as published ones, and that is the point" — including the boot that
-- applies this file. It holds the declarations already, so the sweep is a filter
-- over rows it has already read.
--
-- **Why not a one-shot behind a `system_settings` flag.** A flag exists to make
-- something happen once because happening twice would be wrong. Happening again
-- is not wrong here: `writeOption` can no longer create such a row, so on a
-- healthy install the sweep matches nothing, and the two ways one can still
-- appear are both things it SHOULD take — a database seeded by a build that
-- materialized everything, and a declared default that MOVED underneath a row
-- holding the old one. That second case is what `0102`, `0110` and `0111` each
-- swept by hand, and making it safe is the ruling's stated benefit. A flag would
-- buy the guarantee that the fourth such migration is still needed.
--
-- **Rows at an address the version no longer declares are NOT part of this.**
-- They are culled by `reconcileConfigs` already, with a notice naming what was
-- lost and what it held — that mechanism is untouched, and duplicating it here
-- would delete the row before the notice could be written from it. Confirmed
-- rather than added: `config/named.int.test.ts` pins both directions.
--
-- **Plugin and imported specs contribute no rows.** `ensureDefaultConfig` is
-- reached only through `reconcileConfigs`, which is called only from
-- `seedCoreSpecs` over `CORE_SPECS`, so a non-core spec has no configuration at
-- all today and therefore nothing materialized to sweep. Stated because a reader
-- checking this file's coverage will reasonably ask, and "there are none" is a
-- finding rather than a gap.
--
-- ── 2. The three published documents ───────────────────────────────────────
--
-- `core:provider/generate-text@1` declares `params.stopSequences`, and since the
-- stop-sequence ruling (2026-09-10) every piece of the path exists: the binding
-- reads `input?.params?.stopSequences`, `DispatchRequest` carries it, and
-- `BaseConnectionAdapter.withStops` sends it. Every piece except the spec half —
-- the three reply specs called `C.generateText.v1({…})` with no
-- `params: slot.params()`, so `resolveInput` never formed the key and the reader
-- saw `undefined` on every turn while the panel rendered the control and stored
-- what people typed into it. The catalog names the slot now
-- (`serene-pub-sdk/core-catalog/src/{respond,narrate,narrateCharacter}.ts`), and
-- `boot/paramsSlotWiring.test.ts` moves 9 → 6 with the three lines deleted.
--
-- ⚠ **Behaviour-preserving, and the declaration is what makes it so.**
-- `stopSequences` carries no default, so an install that never typed one
-- resolves `undefined` and sends exactly the stops it always did. What changes
-- is that an install that DID type one stops being ignored.
--
-- This is the half a fresh test database cannot see. The 0.6 pre-release froze
-- spec versions until 0.7.0, so `1.20.0`, `1.11.0` and `1.0.0` stay; seeding
-- matches on (slug, semver) and, on a match, updates only the display name
-- (`bootstrap.ts`: "spec publishing is idempotent by version"). The rewired
-- documents would therefore reach NO database that has already seeded — every
-- developer machine and every upgrading install — and would be invisible on a
-- fresh test database, where the rows do not exist and the edit publishes
-- normally. Deleting the version rows is what makes boot republish them.
--
-- Precedent and terms: 0095, 0100, 0102, 0106, 0110, 0111 and 0113 — the same
-- three pins, for the same structural reason each time (the reply-shaped specs
-- are the ones with a Provider whose slots keep turning out to be unwired).
-- `pipeline_nodes`, `pipeline_edges`, `pipeline_blocks`, `pipeline_includes`,
-- `pipeline_event_subscriptions` and `pipeline_presets` all cascade from
-- `pipeline_spec_versions`, so the old documents go cleanly. What is LOST with
-- them, stated rather than discovered: the author presets shipped with these
-- versions, and any per-subscription `enabled` flag somebody had turned off.
-- `pipeline_configs` hangs off `pipeline_specs`, not off a version, so tuned
-- configurations survive — and `reconcileConfigs` re-runs against the
-- republished versions on the same boot, which is also the boot that performs
-- statement 1's sweep. `pipeline_specs.active_version_id` is not a foreign key;
-- it dangles for exactly as long as it takes boot to republish and move the
-- pointer, in the same startup that runs this file.
--
-- No `pipeline_type_registry` statement, and its absence is checkable: a type's
-- content hash covers its declaration, and no declaration moved here — the three
-- edits are to DOCUMENTS. `boot/registryHashes.test.ts` records nothing in this
-- change, which is the evidence.
DELETE FROM "pipeline_spec_versions"
WHERE "id" IN (
	SELECT "v"."id"
	FROM "pipeline_spec_versions" "v"
	JOIN "pipeline_specs" "s" ON "s"."id" = "v"."spec_id"
	WHERE ("s"."slug" = 'core:spec/respond' AND "v"."semver" = '1.20.0')
	OR ("s"."slug" = 'core:spec/narrate' AND "v"."semver" = '1.11.0')
	OR ("s"."slug" = 'core:spec/narrate-character' AND "v"."semver" = '1.0.0')
);
