CREATE TABLE "session_preset_notices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_preset_notices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"preset_id" integer NOT NULL,
	"event" text NOT NULL,
	"bound_spec" text NOT NULL,
	"reason" text NOT NULL,
	"fallback_spec" text,
	"first_seen_at" timestamp DEFAULT now() NOT NULL,
	"last_seen_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "session_preset_notices_slot_uq" UNIQUE("preset_id","event")
);
--> statement-breakpoint
ALTER TABLE "session_preset_notices" ADD CONSTRAINT "session_preset_notices_preset_id_session_presets_id_fk" FOREIGN KEY ("preset_id") REFERENCES "public"."session_presets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "session_preset_notices_preset_idx" ON "session_preset_notices" USING btree ("preset_id");