-- **Specs and types become content-addressed** (ruling 2026-09-10).
--
-- A slug — `core:query/vector-search@1`, `core:spec/respond@1.20.0` — stops
-- being an identity and becomes an **indirection to a content hash**. The rows
-- are keyed by the hash; the slug points at whichever one is current. A boot
-- that publishes a changed declaration under an unchanged slug inserts a row and
-- moves the pointer, so an in-place edit reaches every install without a version
-- bump and **without a re-projection migration** — the thing 0095, 0100, 0102,
-- 0106, 0110, 0111, 0113 and 0115 each were, one per edit, each found by hand.
--
-- Existing receipts stay valid because they name a hash that still exists.
--
-- ── 1. Types: the registry row becomes the pointer ─────────────────────────
--
-- `pipeline_type_declarations` holds every declaration a slug has ever resolved
-- to, keyed by `content_hash`, with `material` being exactly what was hashed —
-- so the table verifies itself. `pipeline_type_registry` keeps one row per
-- `type_id@version` and its `content_hash` names the current one.
--
-- ⚠ **The registry table is deliberately NOT re-keyed by hash**, and the reason
-- is a foreign key: `lorebook_entries_type_fk` references
-- `pipeline_type_registry (type_id, version)`, which stops being unique the
-- moment a slug holds two rows. Re-pointing it at a new pointer table would also
-- turn twelve plain `SELECT … FROM pipeline_type_registry` readers — the config
-- panel, the genre list, the script list, connection defaults, sampling shapes —
-- into duplicate-row readers on upgraded installs **only**, since a fresh test
-- database has one row per slug and stays green. Nothing pins a *type* hash
-- (a spec node pins `type_id@version`, a receipt records a bare `typeId`), so
-- splitting the registry buys no integrity for that risk. The archive gives the
-- retention; the pointer column gives the indirection.
--
-- **No data statement seeds the archive, and that is deliberate.** The hash is a
-- JS digest of a stripped declaration, which SQL cannot compute — but the
-- registry row already carries the hash it was published under, and
-- `readTypeRegistry` reconstructs the declaration from that row losslessly
-- (`registrySync.int.test.ts` pins the round trip). So the first boot after this
-- adopts each existing row into the archive from the row itself, marked
-- `source = 'adopted'`. A row whose `content_hash` is NULL — possible only on an
-- install that predates the column — adopts nothing and is simply republished
-- from this build.
--
-- ── 2. Specs: the hash joins the key, `active_version_id` is the pointer ───
--
-- `pipeline_spec_versions` was unique on `(spec_id, semver)`, so an edited
-- document had nowhere to land but on top of the row a receipt already named —
-- which is why `saveDocument` deleted the prior row and why seeding, which
-- matched on the same pair, skipped the edit entirely on any install that had
-- booted. The unique index gains `canonical_hash`: an edit inserts a new row,
-- `pipeline_specs.active_version_id` moves to it, and the row it moved off is
-- marked `retired` so every `status = 'published'` reader still sees exactly one
-- row per slug.
--
-- No second pointer table: `active_version_id` has been the pointer since 02 §3,
-- and a second place for one fact is the failure this layer keeps closing.
--
-- ── 3. Receipts pin the document ───────────────────────────────────────────
--
-- `pipeline_runs.spec_hash` records the canonical hash the run resolved against,
-- so an explain surface can say whether the receipt still describes what the
-- slug resolves to today.
--
-- ⚠ **The backfill below gives existing rows the hash that is current at
-- migration time, which is not necessarily the one they ran.** Under the old
-- rules an edited document overwrote its version row in place, so the document
-- those runs used no longer exists to name; the honest options were this or
-- NULL, and NULL would make every historical receipt unattributable. The column
-- comment in `schema.ts` says the same thing, which is where a reader of the row
-- will look.
--
-- ── 4. Plugin-declared presets ─────────────────────────────────────────────
--
-- `session_presets.owner_plugin_id` and `withdrawn_at`. A plugin's `preset()`
-- declaration reached no row at all; it now projects one, disabled until an
-- administrator enables it. Disabling or uninstalling the plugin **marks**
-- rather than deletes — a session names its preset, and withdrawing one out from
-- under a live session is not something a checkbox should do. `enabled` stays
-- the administrator's decision so that switching an extension off and on again
-- does not silently un-approve its presets.

CREATE TABLE "pipeline_type_declarations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_type_declarations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type_id" text NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"kind" text NOT NULL,
	"content_hash" text NOT NULL,
	"material" json NOT NULL,
	"entry" json NOT NULL,
	"release" text,
	"source" text DEFAULT 'declared' NOT NULL,
	"first_seen_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
DROP INDEX "pipeline_spec_versions_spec_semver_idx";--> statement-breakpoint
ALTER TABLE "pipeline_runs" ADD COLUMN "spec_hash" text;--> statement-breakpoint
ALTER TABLE "session_presets" ADD COLUMN "owner_plugin_id" integer;--> statement-breakpoint
ALTER TABLE "session_presets" ADD COLUMN "withdrawn_at" timestamp;--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_type_declarations_hash_idx" ON "pipeline_type_declarations" USING btree ("type_id","version","content_hash");--> statement-breakpoint
CREATE INDEX "pipeline_type_declarations_slug_idx" ON "pipeline_type_declarations" USING btree ("type_id","version");--> statement-breakpoint
CREATE INDEX "session_presets_owner_idx" ON "session_presets" USING btree ("owner_plugin_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_spec_versions_spec_semver_idx" ON "pipeline_spec_versions" USING btree ("spec_id","semver","canonical_hash");
--> statement-breakpoint
-- The backfill described in §3. `active_version_id` first, then the newest row
-- for the pair — an install mid-upgrade can have neither, and a run whose slug
-- and semver match nothing keeps NULL rather than borrowing another spec's hash.
UPDATE "pipeline_runs" "r"
SET "spec_hash" = (
	SELECT "v"."canonical_hash"
	FROM "pipeline_spec_versions" "v"
	JOIN "pipeline_specs" "s" ON "s"."id" = "v"."spec_id"
	WHERE "s"."slug" = "r"."spec_slug" AND "v"."semver" = "r"."spec_version"
	ORDER BY ("v"."id" = "s"."active_version_id") DESC, "v"."id" DESC
	LIMIT 1
)
WHERE "spec_hash" IS NULL;
