CREATE TABLE "attribute_configs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attribute_configs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"owner_kind" text NOT NULL,
	"owner_id" integer NOT NULL,
	"slot_id" text NOT NULL,
	"config" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"session_id" integer,
	"valid_from_message_id" integer,
	"updated_by" text DEFAULT 'user' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "attribute_configs_owner_kind_check" CHECK ("attribute_configs"."owner_kind" IN ('card', 'cast_member', 'lorebook', 'session', 'session_cast'))
);
--> statement-breakpoint
CREATE TABLE "attribute_values" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attribute_values_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"owner_kind" text NOT NULL,
	"owner_id" integer NOT NULL,
	"slot_id" text NOT NULL,
	"value" jsonb NOT NULL,
	"session_id" integer,
	"valid_from_message_id" integer,
	"updated_by" text DEFAULT 'user' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "attribute_values_owner_kind_check" CHECK ("attribute_values"."owner_kind" IN ('card', 'cast_member', 'lorebook', 'session', 'session_cast'))
);
--> statement-breakpoint
CREATE TABLE "session_possessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_possessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" integer NOT NULL,
	"owner_kind" text NOT NULL,
	"owner_id" integer NOT NULL,
	"entry_id" integer NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"valid_from_message_id" integer,
	"updated_by" text DEFAULT 'user' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "session_possessions_owner_kind_check" CHECK ("session_possessions"."owner_kind" IN ('session_cast', 'session'))
);
--> statement-breakpoint
CREATE TABLE "state_proposals" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "state_proposals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" integer NOT NULL,
	"message_id" integer,
	"kind" text NOT NULL,
	"payload" jsonb NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"proposed_by" text DEFAULT '' NOT NULL,
	"decided_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "state_proposals_kind_check" CHECK ("state_proposals"."kind" IN ('value', 'possession')),
	CONSTRAINT "state_proposals_status_check" CHECK ("state_proposals"."status" IN ('pending', 'accepted', 'rejected'))
);
--> statement-breakpoint
ALTER TABLE "attribute_configs" ADD CONSTRAINT "attribute_configs_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attribute_configs" ADD CONSTRAINT "attribute_configs_valid_from_message_id_messages_id_fk" FOREIGN KEY ("valid_from_message_id") REFERENCES "public"."messages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attribute_values" ADD CONSTRAINT "attribute_values_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attribute_values" ADD CONSTRAINT "attribute_values_valid_from_message_id_messages_id_fk" FOREIGN KEY ("valid_from_message_id") REFERENCES "public"."messages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_possessions" ADD CONSTRAINT "session_possessions_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_possessions" ADD CONSTRAINT "session_possessions_entry_id_lorebook_entries_id_fk" FOREIGN KEY ("entry_id") REFERENCES "public"."lorebook_entries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_possessions" ADD CONSTRAINT "session_possessions_valid_from_message_id_messages_id_fk" FOREIGN KEY ("valid_from_message_id") REFERENCES "public"."messages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "state_proposals" ADD CONSTRAINT "state_proposals_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "state_proposals" ADD CONSTRAINT "state_proposals_message_id_messages_id_fk" FOREIGN KEY ("message_id") REFERENCES "public"."messages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "attribute_configs_owner_idx" ON "attribute_configs" USING btree ("owner_kind","owner_id","slot_id");--> statement-breakpoint
CREATE INDEX "attribute_configs_session_idx" ON "attribute_configs" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "attribute_values_owner_idx" ON "attribute_values" USING btree ("owner_kind","owner_id","slot_id");--> statement-breakpoint
CREATE INDEX "attribute_values_session_idx" ON "attribute_values" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "session_possessions_session_idx" ON "session_possessions" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "session_possessions_owner_idx" ON "session_possessions" USING btree ("session_id","owner_kind","owner_id");--> statement-breakpoint
CREATE INDEX "state_proposals_session_status_idx" ON "state_proposals" USING btree ("session_id","status");--> statement-breakpoint
CREATE INDEX "state_proposals_message_idx" ON "state_proposals" USING btree ("message_id");