-- User-authored scripts — the fourth paradigm's storage (18 §2).
--
-- The prompts-row pattern, keyed by script *type* rather than by spec: a text
-- transform is a statement about text, not about which pipeline runs it, so
-- one row may be attached anywhere its type is accepted. The type's contract
-- lives in `pipeline_type_registry` (kind = 'script', migration 0125); this
-- table holds only what a person authored — the source, the name, and the
-- declared variable I/O (18 §6a) that says what the script reads and what it
-- may rewrite.
--
-- No FK to the registry on purpose: registry rows are re-projected on boot and
-- keyed by (type_id, version) with their own lifecycle. A script whose type is
-- absent from the running build is data to keep and refuse at attach — the
-- unknown-type rule — not a row to cascade away.
CREATE TABLE "pipeline_scripts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_scripts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type_id" text NOT NULL,
	"seed_key" text,
	"name" text NOT NULL,
	"is_immutable" boolean DEFAULT false NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"source" text DEFAULT '' NOT NULL,
	"vars_in" json DEFAULT '[]'::json NOT NULL,
	"vars_out" json DEFAULT '[]'::json NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_scripts_seed_key_unique" UNIQUE("seed_key")
);
--> statement-breakpoint
CREATE INDEX "pipeline_scripts_type_idx" ON "pipeline_scripts" USING btree ("type_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_scripts_type_name_idx" ON "pipeline_scripts" USING btree ("type_id","name");
