-- Stop scripts on connections (18 §4b) — the rides-along join.
--
-- Model knowledge accumulates on the connection: a stop guard for an endpoint
-- that leaks template tokens attaches once and reaches every pipeline that
-- runs against it, core's and any extension's. Only `text/stop` rows may
-- attach — the entity layer refuses the rest, because entity attachment is
-- limited to what actually flows through the entity — and merging with a
-- pipeline's own chain needs no precedence rule because stop verdicts reduce
-- to the earliest index whatever their source (18 §5).
--
-- `script_id` cascades: the entity layer refuses deleting an attached script
-- first (naming the connection), so the cascade only fires on paths that
-- bypassed it, where a dangling attachment would be worse.
CREATE TABLE "connection_scripts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "connection_scripts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"connection_id" integer NOT NULL,
	"script_id" integer NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "connection_scripts" ADD CONSTRAINT "connection_scripts_connection_id_connections_id_fk" FOREIGN KEY ("connection_id") REFERENCES "public"."connections"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "connection_scripts" ADD CONSTRAINT "connection_scripts_script_id_pipeline_scripts_id_fk" FOREIGN KEY ("script_id") REFERENCES "public"."pipeline_scripts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "connection_scripts_pair_idx" ON "connection_scripts" USING btree ("connection_id","script_id");--> statement-breakpoint
CREATE INDEX "connection_scripts_script_idx" ON "connection_scripts" USING btree ("script_id");
