CREATE TABLE "character_folders" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "character_folders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "characters" ADD COLUMN "is_persona" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "characters" ADD COLUMN "is_default_persona" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "characters" ADD COLUMN "folder_id" integer;--> statement-breakpoint
ALTER TABLE "character_folders" ADD CONSTRAINT "character_folders_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "character_folders_user_id_idx" ON "character_folders" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "character_folders_user_name_unique" ON "character_folders" USING btree ("user_id","name");--> statement-breakpoint
ALTER TABLE "characters" ADD CONSTRAINT "characters_folder_id_character_folders_id_fk" FOREIGN KEY ("folder_id") REFERENCES "public"."character_folders"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "characters_default_persona_unique" ON "characters" USING btree ("user_id") WHERE "is_default_persona";--> statement-breakpoint
CREATE INDEX "characters_folder_id_idx" ON "characters" USING btree ("folder_id");