-- HAND-EDITED, and this is the whole of the edit: (1) the DATA MOVE block below
-- was INSERTED after the generated `ADD COLUMN` statements and before the
-- generated `ADD CONSTRAINT` statements; (2) ONE generated statement was moved
-- — `CREATE UNIQUE INDEX "pipeline_definition_registry_definition_version_idx"`
-- now precedes the `lorebook_entries_type_fk` foreign key that references those
-- two columns, because drizzle-kit emitted the FK first and Postgres refuses a
-- FK onto columns with no unique index yet (the same ordering defect 0133 met).
-- Nothing generated was changed or removed. (Generated by `npm run db:generate`
-- against a scratch data dir, answering drizzle-kit's twenty rename prompts as
-- renames.)
--
-- The one-shot rename (plans/30 §U3; 09-B B1 B2 B3 B5 B7 B8 B9; NOMENCLATURE
-- §4 §5 §12 §23 §25). One change, one migration, one hash republish:
--
--   · kinds  input · provider · consumer  →  inlet · oracle · outlet, and the
--     definition ids follow (`core:input/…` → `core:inlet/…`);
--   · clauses (was blocks)  async · map · route  →  gather · each · junction;
--   · `pipeline_type_registry` → `pipeline_definition_registry`, `type_id` →
--     `definition_id` everywhere a node definition is named; the archive too;
--   · `pipeline_event_subscriptions` dropped — nothing read it (R-4);
--   · genre events are core events by id (`core:event/message-respond@1`) on
--     the inlet lock and in preset bindings;
--   · triggers carry `venue`, not `kind`; `pick` and the taxonomy `zone` culled;
--   · the tool loop is keyed `tools`; the lore lanes and the embed pair have
--     one `params` owner each, with stored deviations folded to the owner.
--
-- Why the data sits where it does: the new CHECK constraints (`…_kind_check`)
-- are validated the moment they are added, so every `kind` value has to be
-- rewritten first; and the fold/rename writes read columns the `RENAME COLUMN`
-- statements above give their new names.
--
-- What this migration does NOT do, by rule:
--   · Receipts (`pipeline_runs`, `pipeline_run_nodes`) are never rewritten. A
--     receipt pins its hash and its id strings; `renamed_from` on the registry
--     resolves the old ids, and the version row it pinned stays under its old
--     `canonical_hash` (now marked `renamed_at`).
--   · `canonical_hash` is not recomputed here — SQL cannot hash a document.
--     The rewritten rows load to a document whose hash IS the one the new SDK
--     computes (the migration test asserts it), so the next boot publishes the
--     same content under that hash and moves the pointer once; the row this
--     migration touched retires and stays resolvable.
--   · `lorebook_entries.type_id` and `pipeline_scripts.type_id` keep their
--     names: *entry type* is not yet ruled to *kind*, and the script-kind
--     column was not named by the ruling.
--
ALTER TABLE "pipeline_event_subscriptions" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "pipeline_event_subscriptions" CASCADE;--> statement-breakpoint
ALTER TABLE "pipeline_blocks" RENAME TO "pipeline_clauses";--> statement-breakpoint
ALTER TABLE "pipeline_type_declarations" RENAME TO "pipeline_definition_declarations";--> statement-breakpoint
ALTER TABLE "pipeline_type_registry" RENAME TO "pipeline_definition_registry";--> statement-breakpoint
ALTER TABLE "pipeline_clauses" RENAME COLUMN "block_id" TO "clause_id";--> statement-breakpoint
ALTER TABLE "pipeline_clauses" RENAME COLUMN "parent_block_id" TO "parent_clause_id";--> statement-breakpoint
ALTER TABLE "pipeline_clauses" RENAME COLUMN "routes" TO "branches";--> statement-breakpoint
ALTER TABLE "pipeline_context_templates" RENAME COLUMN "node_type_id" TO "node_definition_id";--> statement-breakpoint
ALTER TABLE "pipeline_edges" RENAME COLUMN "from_block_id" TO "from_clause_id";--> statement-breakpoint
ALTER TABLE "pipeline_node_rebinds" RENAME COLUMN "type_id" TO "definition_id";--> statement-breakpoint
ALTER TABLE "pipeline_nodes" RENAME COLUMN "type_id" TO "definition_id";--> statement-breakpoint
ALTER TABLE "pipeline_nodes" RENAME COLUMN "type_version" TO "definition_version";--> statement-breakpoint
ALTER TABLE "pipeline_nodes" RENAME COLUMN "block_id" TO "clause_id";--> statement-breakpoint
ALTER TABLE "pipeline_nodes" RENAME COLUMN "block_kind" TO "clause_kind";--> statement-breakpoint
ALTER TABLE "pipeline_nodes" RENAME COLUMN "block_chain" TO "clause_chain";--> statement-breakpoint
ALTER TABLE "pipeline_prompts" RENAME COLUMN "node_type_id" TO "node_definition_id";--> statement-breakpoint
ALTER TABLE "pipeline_run_nodes" RENAME COLUMN "type_id" TO "definition_id";--> statement-breakpoint
ALTER TABLE "pipeline_definition_declarations" RENAME COLUMN "type_id" TO "definition_id";--> statement-breakpoint
ALTER TABLE "pipeline_definition_registry" RENAME COLUMN "type_id" TO "definition_id";--> statement-breakpoint
ALTER TABLE "pipeline_clauses" DROP CONSTRAINT "pipeline_blocks_kind_check";--> statement-breakpoint
ALTER TABLE "pipeline_clauses" DROP CONSTRAINT "pipeline_blocks_bounded_check";--> statement-breakpoint
ALTER TABLE "pipeline_edges" DROP CONSTRAINT "pipeline_edges_one_source_check";--> statement-breakpoint
ALTER TABLE "pipeline_nodes" DROP CONSTRAINT "pipeline_nodes_kind_check";--> statement-breakpoint
ALTER TABLE "lorebook_entries" DROP CONSTRAINT "lorebook_entries_type_fk";
--> statement-breakpoint
ALTER TABLE "pipeline_clauses" DROP CONSTRAINT "pipeline_blocks_spec_version_id_pipeline_spec_versions_id_fk";
--> statement-breakpoint
DROP INDEX "pipeline_blocks_version_block_idx";--> statement-breakpoint
DROP INDEX "pipeline_context_templates_node_type_idx";--> statement-breakpoint
DROP INDEX "pipeline_context_templates_node_type_name_idx";--> statement-breakpoint
DROP INDEX "pipeline_type_declarations_hash_idx";--> statement-breakpoint
DROP INDEX "pipeline_type_declarations_slug_idx";--> statement-breakpoint
DROP INDEX "pipeline_type_registry_type_version_idx";--> statement-breakpoint
DROP INDEX "pipeline_context_templates_pool_idx";--> statement-breakpoint
DROP INDEX "pipeline_prompts_pool_idx";--> statement-breakpoint
DROP INDEX "pipeline_prompts_pool_name_idx";--> statement-breakpoint
ALTER TABLE "pipeline_spec_versions" ADD COLUMN "renamed_at" timestamp;--> statement-breakpoint
ALTER TABLE "pipeline_definition_registry" ADD COLUMN "renamed_from" text;--> statement-breakpoint
ALTER TABLE "pipeline_definition_registry" ADD COLUMN "renamed_at" timestamp;--> statement-breakpoint
-- ═══════════════════════════════════════════════════════════════════════════
-- DATA MOVE (hand-written; see the header). Everything below rewrites rows the
-- statements above renamed the columns of, and everything must be done before
-- the CHECK constraints further down are added — a CHECK is validated on ADD.
-- ═══════════════════════════════════════════════════════════════════════════

-- 1 · Node kinds (R-13): input → inlet, provider → oracle, consumer → outlet.
UPDATE "pipeline_nodes" SET "kind" = CASE "kind"
	WHEN 'input' THEN 'inlet' WHEN 'provider' THEN 'oracle' WHEN 'consumer' THEN 'outlet' ELSE "kind" END
WHERE "kind" IN ('input', 'provider', 'consumer');--> statement-breakpoint

-- 2 · Definition ids follow the kind (01 §3a). The bare slug on node rows and
-- the registry; the full pin (`…@N`) on rebinds. `replace` is safe: `:input/`
-- can only be the kind segment of an `ns:kind/name` id.
UPDATE "pipeline_nodes" SET "definition_id" = replace(replace(replace("definition_id", ':input/', ':inlet/'), ':provider/', ':oracle/'), ':consumer/', ':outlet/')
WHERE "definition_id" LIKE '%:input/%' OR "definition_id" LIKE '%:provider/%' OR "definition_id" LIKE '%:consumer/%';--> statement-breakpoint
UPDATE "pipeline_node_rebinds" SET "definition_id" = replace(replace(replace("definition_id", ':input/', ':inlet/'), ':provider/', ':oracle/'), ':consumer/', ':outlet/')
WHERE "definition_id" LIKE '%:input/%' OR "definition_id" LIKE '%:provider/%' OR "definition_id" LIKE '%:consumer/%';--> statement-breakpoint
UPDATE "pipeline_prompts" SET "node_definition_id" = replace(replace(replace("node_definition_id", ':input/', ':inlet/'), ':provider/', ':oracle/'), ':consumer/', ':outlet/')
WHERE "node_definition_id" LIKE '%:input/%' OR "node_definition_id" LIKE '%:provider/%' OR "node_definition_id" LIKE '%:consumer/%';--> statement-breakpoint
UPDATE "pipeline_context_templates" SET "node_definition_id" = replace(replace(replace("node_definition_id", ':input/', ':inlet/'), ':provider/', ':oracle/'), ':consumer/', ':outlet/')
WHERE "node_definition_id" LIKE '%:input/%' OR "node_definition_id" LIKE '%:provider/%' OR "node_definition_id" LIKE '%:consumer/%';--> statement-breakpoint
-- A shipped prompt's idempotence key embeds its pool's definition id
-- (`pipeline-prompt:core:oracle/summarize-batch:prompts:…`); left as it was,
-- the next boot would find no row under the new key and insert a twin into a
-- pool that already holds the name.
UPDATE "pipeline_prompts" SET "seed_key" = replace(replace(replace("seed_key", ':input/', ':inlet/'), ':provider/', ':oracle/'), ':consumer/', ':outlet/')
WHERE "seed_key" LIKE '%:input/%' OR "seed_key" LIKE '%:provider/%' OR "seed_key" LIKE '%:consumer/%';--> statement-breakpoint

-- 3 · The registry: superseded-by-rename. `renamed_from` keeps the old slug so a
-- receipt's pinned id string still resolves, and the run inspector can say
-- *renamed*, not *changed*. The archive's `definition_id` follows; its
-- `material` is NOT touched, so re-hashing it still yields `content_hash`.
UPDATE "pipeline_definition_registry" SET "renamed_from" = "definition_id", "renamed_at" = CURRENT_TIMESTAMP
WHERE "definition_id" LIKE '%:input/%' OR "definition_id" LIKE '%:provider/%' OR "definition_id" LIKE '%:consumer/%';--> statement-breakpoint
UPDATE "pipeline_definition_registry" SET "definition_id" = replace(replace(replace("definition_id", ':input/', ':inlet/'), ':provider/', ':oracle/'), ':consumer/', ':outlet/')
WHERE "renamed_at" IS NOT NULL;--> statement-breakpoint
UPDATE "pipeline_definition_declarations" SET "definition_id" = replace(replace(replace("definition_id", ':input/', ':inlet/'), ':provider/', ':oracle/'), ':consumer/', ':outlet/')
WHERE "definition_id" LIKE '%:input/%' OR "definition_id" LIKE '%:provider/%' OR "definition_id" LIKE '%:consumer/%';--> statement-breakpoint
-- The registry row's `kind` column is the reader's projection of the same
-- word §1 rewrote on every node row, and it must agree with them from the
-- moment the migration ends — not from the first boot's hash move, which is
-- what would otherwise heal it. The archive's `kind` COLUMN follows for the
-- same reason `definition_id` did: an attribute in the reader's vocabulary,
-- not the key. The archive's `material.kind` stays `input`/`provider`/
-- `consumer` — it is what was hashed, and the archive is self-verifying only
-- while re-hashing `material` yields `content_hash`.
UPDATE "pipeline_definition_registry" SET "kind" = CASE "kind"
	WHEN 'input' THEN 'inlet' WHEN 'provider' THEN 'oracle' WHEN 'consumer' THEN 'outlet' ELSE "kind" END
WHERE "kind" IN ('input', 'provider', 'consumer');--> statement-breakpoint
UPDATE "pipeline_definition_declarations" SET "kind" = CASE "kind"
	WHEN 'input' THEN 'inlet' WHEN 'provider' THEN 'oracle' WHEN 'consumer' THEN 'outlet' ELSE "kind" END
WHERE "kind" IN ('input', 'provider', 'consumer');--> statement-breakpoint
-- The culled inlet (R-4): `core:input/message-created@1` had no spec and no
-- emitter, so no node row and no receipt pins it. The two statements above
-- already renamed its registry row (to `core:inlet/message-created`, with
-- `renamed_from` set) and its archive row; the registry row is deleted here,
-- by the old slug it still carries, and the archive row is left where the
-- rename put it — under `core:inlet/message-created`, material untouched.
DELETE FROM "pipeline_definition_registry" WHERE "renamed_from" = 'core:input/message-created';--> statement-breakpoint

-- 4 · Clause kinds (R-14): async → gather, map → each, route → junction.
UPDATE "pipeline_clauses" SET "kind" = CASE "kind"
	WHEN 'async' THEN 'gather' WHEN 'map' THEN 'each' WHEN 'route' THEN 'junction' ELSE "kind" END
WHERE "kind" IN ('async', 'map', 'route');--> statement-breakpoint
UPDATE "pipeline_nodes" SET "clause_kind" = CASE "clause_kind"
	WHEN 'async' THEN 'gather' WHEN 'map' THEN 'each' WHEN 'route' THEN 'junction' ELSE "clause_kind" END
WHERE "clause_kind" IN ('async', 'map', 'route');--> statement-breakpoint

-- 5 · The tool loop's clause is keyed `tools`, not `agent` (NOMENCLATURE §4).
-- Scoped to the one spec that has it. Node keys, clause ids, the data/slot
-- references inside config JSON, the loop predicate, and every config row,
-- notice, override and author-preset value addressed by those keys.
--
-- First the QUERY node that was keyed `tools` moves to `available`: nodes and
-- clauses share one address space, and `$.tools` has to name exactly one
-- thing. Done before the clause takes the name, while `"node":"tools"` in a
-- data reference can only mean the query.
UPDATE "pipeline_nodes" SET
	"node_key" = 'available',
	"config" = replace("config"::text, '"node":"tools"', '"node":"available"')::json
WHERE "node_key" = 'tools' AND "spec_version_id" IN (SELECT v."id" FROM "pipeline_spec_versions" v JOIN "pipeline_specs" s ON s."id" = v."spec_id" WHERE s."slug" = 'core:spec/tool-loop');--> statement-breakpoint
UPDATE "pipeline_nodes" SET
	"config" = replace("config"::text, '"node":"tools"', '"node":"available"')::json
WHERE "config"::text LIKE '%"node":"tools"%' AND "spec_version_id" IN (SELECT v."id" FROM "pipeline_spec_versions" v JOIN "pipeline_specs" s ON s."id" = v."spec_id" WHERE s."slug" = 'core:spec/tool-loop');--> statement-breakpoint
UPDATE "pipeline_preset_values" SET "node_key" = 'available'
WHERE "node_key" = 'tools' AND "preset_id" IN (SELECT p."id" FROM "pipeline_presets" p JOIN "pipeline_spec_versions" v ON v."id" = p."spec_version_id" JOIN "pipeline_specs" s ON s."id" = v."spec_id" WHERE s."slug" = 'core:spec/tool-loop');--> statement-breakpoint
UPDATE "pipeline_config_values" SET "node_key" = 'available'
WHERE "node_key" = 'tools' AND "config_id" IN (SELECT c."id" FROM "pipeline_configs" c JOIN "pipeline_specs" s ON s."id" = c."spec_id" WHERE s."slug" = 'core:spec/tool-loop');--> statement-breakpoint
UPDATE "pipeline_config_notices" SET "node_key" = 'available'
WHERE "node_key" = 'tools' AND "config_id" IN (SELECT c."id" FROM "pipeline_configs" c JOIN "pipeline_specs" s ON s."id" = c."spec_id" WHERE s."slug" = 'core:spec/tool-loop');--> statement-breakpoint
UPDATE "pipeline_node_overrides" SET "node_key" = 'available'
WHERE "node_key" = 'tools' AND "spec_id" IN (SELECT "id" FROM "pipeline_specs" WHERE "slug" = 'core:spec/tool-loop');--> statement-breakpoint
-- Then the clause, and everything keyed under it.
UPDATE "pipeline_nodes" SET
	"node_key" = regexp_replace("node_key", '^agent\.', 'tools.'),
	"clause_id" = CASE WHEN "clause_id" = 'agent' THEN 'tools' ELSE regexp_replace("clause_id", '^agent\.', 'tools.') END,
	"config" = replace(replace("config"::text, '"agent.item.', '"tools.item.'), '"node":"agent"', '"node":"tools"')::json,
	"resolved_refs" = CASE WHEN "resolved_refs" IS NULL THEN NULL ELSE replace("resolved_refs"::text, '"agent.item.', '"tools.item.')::json END
WHERE "spec_version_id" IN (SELECT v."id" FROM "pipeline_spec_versions" v JOIN "pipeline_specs" s ON s."id" = v."spec_id" WHERE s."slug" = 'core:spec/tool-loop');--> statement-breakpoint
UPDATE "pipeline_clauses" SET
	"clause_id" = CASE WHEN "clause_id" = 'agent' THEN 'tools' ELSE regexp_replace("clause_id", '^agent\.', 'tools.') END,
	"parent_clause_id" = CASE WHEN "parent_clause_id" = 'agent' THEN 'tools' ELSE regexp_replace("parent_clause_id", '^agent\.', 'tools.') END,
	"repeat_while" = CASE WHEN "repeat_while" IS NULL THEN NULL ELSE replace(replace("repeat_while"::text, '"agent.item.', '"tools.item.'), '"node":"agent"', '"node":"tools"')::json END,
	"over_ref" = CASE WHEN "over_ref" IS NULL THEN NULL ELSE replace(replace("over_ref"::text, '"agent.item.', '"tools.item.'), '"node":"agent"', '"node":"tools"')::json END,
	"on_ref" = CASE WHEN "on_ref" IS NULL THEN NULL ELSE replace(replace("on_ref"::text, '"agent.item.', '"tools.item.'), '"node":"agent"', '"node":"tools"')::json END
WHERE "spec_version_id" IN (SELECT v."id" FROM "pipeline_spec_versions" v JOIN "pipeline_specs" s ON s."id" = v."spec_id" WHERE s."slug" = 'core:spec/tool-loop');--> statement-breakpoint
UPDATE "pipeline_edges" SET "from_clause_id" = CASE WHEN "from_clause_id" = 'agent' THEN 'tools' ELSE regexp_replace("from_clause_id", '^agent\.', 'tools.') END
WHERE "from_clause_id" IS NOT NULL AND "spec_version_id" IN (SELECT v."id" FROM "pipeline_spec_versions" v JOIN "pipeline_specs" s ON s."id" = v."spec_id" WHERE s."slug" = 'core:spec/tool-loop');--> statement-breakpoint
UPDATE "pipeline_preset_values" SET "node_key" = regexp_replace("node_key", '^agent\.', 'tools.')
WHERE "node_key" LIKE 'agent.%' AND "preset_id" IN (SELECT p."id" FROM "pipeline_presets" p JOIN "pipeline_spec_versions" v ON v."id" = p."spec_version_id" JOIN "pipeline_specs" s ON s."id" = v."spec_id" WHERE s."slug" = 'core:spec/tool-loop');--> statement-breakpoint
UPDATE "pipeline_config_values" SET "node_key" = regexp_replace("node_key", '^agent\.', 'tools.')
WHERE "node_key" LIKE 'agent.%' AND "config_id" IN (SELECT c."id" FROM "pipeline_configs" c JOIN "pipeline_specs" s ON s."id" = c."spec_id" WHERE s."slug" = 'core:spec/tool-loop');--> statement-breakpoint
UPDATE "pipeline_config_notices" SET "node_key" = regexp_replace("node_key", '^agent\.', 'tools.')
WHERE "node_key" LIKE 'agent.%' AND "config_id" IN (SELECT c."id" FROM "pipeline_configs" c JOIN "pipeline_specs" s ON s."id" = c."spec_id" WHERE s."slug" = 'core:spec/tool-loop');--> statement-breakpoint
UPDATE "pipeline_node_overrides" SET "node_key" = regexp_replace("node_key", '^agent\.', 'tools.')
WHERE "node_key" LIKE 'agent.%' AND "spec_id" IN (SELECT "id" FROM "pipeline_specs" WHERE "slug" = 'core:spec/tool-loop');--> statement-breakpoint

-- 6 · Triggers say `venue`, not `kind` (button → composer, menu → message);
-- `pick` and the taxonomy `zone` are culled (R-15 minimal shape, 09-B B9).
UPDATE "pipeline_spec_versions" SET "contributes" = (
	jsonb_set("contributes"::jsonb, '{triggers}', COALESCE((
		SELECT jsonb_agg((t - 'kind' - 'pick') || jsonb_build_object('venue',
			CASE t->>'kind' WHEN 'button' THEN 'composer' WHEN 'menu' THEN 'message' ELSE COALESCE(t->>'venue', 'composer') END))
		FROM jsonb_array_elements("contributes"::jsonb->'triggers') t
	), '[]'::jsonb))
)::json
WHERE "contributes" IS NOT NULL AND ("contributes"::jsonb ? 'triggers');--> statement-breakpoint
UPDATE "pipeline_spec_versions" SET "taxonomy" = ("taxonomy"::jsonb - 'zone')::json
WHERE "taxonomy" IS NOT NULL AND ("taxonomy"::jsonb ? 'zone');--> statement-breakpoint

-- 7 · One event registry (R-4): the inlet lock and the preset bindings are
-- keyed by event id, `core:event/<name>@1`, not by the bare genre-event name.
UPDATE "pipeline_spec_versions" SET "input_event" = 'core:event/' || "input_event" || '@1'
WHERE "input_event" IS NOT NULL AND "input_event" NOT LIKE 'core:event/%';--> statement-breakpoint
-- The genre declaration a create pipeline carries names its event surface by
-- the same keys (`genre.events`), and it is hashed with the document.
UPDATE "pipeline_spec_versions" SET "genre" = jsonb_set("genre"::jsonb, '{events}', (
	SELECT jsonb_object_agg(CASE WHEN k LIKE 'core:event/%' THEN k ELSE 'core:event/' || k || '@1' END, v)
	FROM jsonb_each("genre"::jsonb->'events') AS e(k, v)
))::json
WHERE "genre" IS NOT NULL AND ("genre"::jsonb ? 'events') AND EXISTS (SELECT 1 FROM jsonb_object_keys("genre"::jsonb->'events') k WHERE k NOT LIKE 'core:event/%');--> statement-breakpoint
UPDATE "session_presets" SET "bindings" = (
	SELECT jsonb_object_agg(CASE WHEN k LIKE 'core:event/%' THEN k ELSE 'core:event/' || k || '@1' END, v)
	FROM jsonb_each("bindings"::jsonb) AS e(k, v)
)::json
WHERE "bindings" IS NOT NULL AND "bindings"::text <> '{}' AND EXISTS (SELECT 1 FROM jsonb_object_keys("bindings"::jsonb) k WHERE k NOT LIKE 'core:event/%');--> statement-breakpoint

-- 8 · One params owner per setting (R-7 P2). First the DOCUMENTS: the two loser
-- lore lanes and the loser embed node now read the owner's params through a
-- slot reference (`slot.params({ node: 'gather.worldLore.read' })`), which the
-- compiler records on the node config and in `resolved_refs`. Rewritten here
-- so the stored rows load to the document the new catalog compiles.
UPDATE "pipeline_nodes" SET
	"config" = jsonb_set("config"::jsonb, '{params,ofNode}', '"gather.worldLore.read"')::json,
	"resolved_refs" = (COALESCE("resolved_refs"::jsonb, '{}'::jsonb) || '{"params":"gather.worldLore.read"}'::jsonb)::json
WHERE "node_key" IN ('gather.characterLore.read', 'gather.historyEntries.read')
	AND "config"::jsonb->'params'->>'__ref' = 'slot' AND ("config"::jsonb->'params'->>'ofNode') IS NULL;--> statement-breakpoint
UPDATE "pipeline_nodes" SET
	"config" = jsonb_set("config"::jsonb, '{params,ofNode}', '"semantic.arm.embed"')::json,
	"resolved_refs" = (COALESCE("resolved_refs"::jsonb, '{}'::jsonb) || '{"params":"semantic.arm.embed"}'::jsonb)::json
WHERE "node_key" = 'names.arm.embed'
	AND "config"::jsonb->'params'->>'__ref' = 'slot' AND ("config"::jsonb->'params'->>'ofNode') IS NULL;--> statement-breakpoint
-- Then the STORED VALUES: deviations stored at the two loser lore lanes fold
-- into `gather.worldLore.read`, and the loser embed node into
-- `semantic.arm.embed` — in `pipeline_config_values` (a configuration's rows)
-- AND in `pipeline_node_overrides` (a session's rows, always `session` scope):
-- the loser node resolves its `params` through `ofNode` to the owner from now
-- on, so a row left at the loser's address would be read by nothing.
--
-- Two rules, both recorded as `pipeline_config_notices` rows because a fold
-- changes what a person sees and gets (NOMENCLATURE §6):
--   · where the owner already holds a row at that path the owner's wins and
--     the loser becomes a `culled` notice carrying its value;
--   · every row that MOVES becomes a `backfilled` notice on the owner's
--     address whose label says old address → new address and the value,
--     because a person who tuned only character lore's `scanDepth` now has
--     all three lanes at that number, and nothing else would say so.
-- A session's notices attach to the configuration the session resolves
-- through — its selection where it made one, else the pipeline's shipped
-- default — since a notice needs a configuration to be shown under.
-- Losers are folded one at a time so two losers at one path cannot both try
-- to land on the owner: the second collides with the first's moved row.
-- 8a · Configuration rows.
-- gather.characterLore.read → gather.worldLore.read
INSERT INTO "pipeline_config_notices" ("config_id", "kind", "node_key", "slot", "path", "label", "previous_value")
SELECT l."config_id", 'culled', l."node_key", l."slot", l."path",
	l."node_key" || '/' || l."path" || ' — folded into gather.worldLore.read, which already held ' || o."value"::text || ' (one owner per setting, R-7 P2)', l."value"
FROM "pipeline_config_values" l JOIN "pipeline_config_values" o
	ON o."config_id" = l."config_id" AND o."node_key" = 'gather.worldLore.read' AND o."slot" = l."slot" AND o."path" = l."path"
WHERE l."node_key" = 'gather.characterLore.read' AND l."slot" = 'params';--> statement-breakpoint
DELETE FROM "pipeline_config_values" l USING "pipeline_config_values" o
WHERE o."config_id" = l."config_id" AND o."node_key" = 'gather.worldLore.read' AND o."slot" = l."slot" AND o."path" = l."path"
	AND l."node_key" = 'gather.characterLore.read' AND l."slot" = 'params';--> statement-breakpoint
INSERT INTO "pipeline_config_notices" ("config_id", "kind", "node_key", "slot", "path", "label", "previous_value")
SELECT l."config_id", 'backfilled', 'gather.worldLore.read', l."slot", l."path",
	l."node_key" || '/' || l."path" || ' → gather.worldLore.read/' || l."path" || ' — one setting now governs world lore, character lore and history (was ' || l."value"::text || ')', l."value"
FROM "pipeline_config_values" l
WHERE l."node_key" = 'gather.characterLore.read' AND l."slot" = 'params';--> statement-breakpoint
UPDATE "pipeline_config_values" SET "node_key" = 'gather.worldLore.read' WHERE "node_key" = 'gather.characterLore.read' AND "slot" = 'params';--> statement-breakpoint
-- gather.historyEntries.read → gather.worldLore.read
INSERT INTO "pipeline_config_notices" ("config_id", "kind", "node_key", "slot", "path", "label", "previous_value")
SELECT l."config_id", 'culled', l."node_key", l."slot", l."path",
	l."node_key" || '/' || l."path" || ' — folded into gather.worldLore.read, which already held ' || o."value"::text || ' (one owner per setting, R-7 P2)', l."value"
FROM "pipeline_config_values" l JOIN "pipeline_config_values" o
	ON o."config_id" = l."config_id" AND o."node_key" = 'gather.worldLore.read' AND o."slot" = l."slot" AND o."path" = l."path"
WHERE l."node_key" = 'gather.historyEntries.read' AND l."slot" = 'params';--> statement-breakpoint
DELETE FROM "pipeline_config_values" l USING "pipeline_config_values" o
WHERE o."config_id" = l."config_id" AND o."node_key" = 'gather.worldLore.read' AND o."slot" = l."slot" AND o."path" = l."path"
	AND l."node_key" = 'gather.historyEntries.read' AND l."slot" = 'params';--> statement-breakpoint
INSERT INTO "pipeline_config_notices" ("config_id", "kind", "node_key", "slot", "path", "label", "previous_value")
SELECT l."config_id", 'backfilled', 'gather.worldLore.read', l."slot", l."path",
	l."node_key" || '/' || l."path" || ' → gather.worldLore.read/' || l."path" || ' — one setting now governs world lore, character lore and history (was ' || l."value"::text || ')', l."value"
FROM "pipeline_config_values" l
WHERE l."node_key" = 'gather.historyEntries.read' AND l."slot" = 'params';--> statement-breakpoint
UPDATE "pipeline_config_values" SET "node_key" = 'gather.worldLore.read' WHERE "node_key" = 'gather.historyEntries.read' AND "slot" = 'params';--> statement-breakpoint
-- names.arm.embed → semantic.arm.embed
INSERT INTO "pipeline_config_notices" ("config_id", "kind", "node_key", "slot", "path", "label", "previous_value")
SELECT l."config_id", 'culled', l."node_key", l."slot", l."path",
	l."node_key" || '/' || l."path" || ' — folded into semantic.arm.embed, which already held ' || o."value"::text || ' (one owner per setting, R-7 P2)', l."value"
FROM "pipeline_config_values" l JOIN "pipeline_config_values" o
	ON o."config_id" = l."config_id" AND o."node_key" = 'semantic.arm.embed' AND o."slot" = l."slot" AND o."path" = l."path"
WHERE l."node_key" = 'names.arm.embed' AND l."slot" = 'params';--> statement-breakpoint
DELETE FROM "pipeline_config_values" l USING "pipeline_config_values" o
WHERE o."config_id" = l."config_id" AND o."node_key" = 'semantic.arm.embed' AND o."slot" = l."slot" AND o."path" = l."path"
	AND l."node_key" = 'names.arm.embed' AND l."slot" = 'params';--> statement-breakpoint
INSERT INTO "pipeline_config_notices" ("config_id", "kind", "node_key", "slot", "path", "label", "previous_value")
SELECT l."config_id", 'backfilled', 'semantic.arm.embed', l."slot", l."path",
	l."node_key" || '/' || l."path" || ' → semantic.arm.embed/' || l."path" || ' — one switch now governs both embed steps (was ' || l."value"::text || ')', l."value"
FROM "pipeline_config_values" l
WHERE l."node_key" = 'names.arm.embed' AND l."slot" = 'params';--> statement-breakpoint
UPDATE "pipeline_config_values" SET "node_key" = 'semantic.arm.embed' WHERE "node_key" = 'names.arm.embed' AND "slot" = 'params';--> statement-breakpoint
-- 8b · Session overrides (W3 of the U3 review).
-- gather.characterLore.read → gather.worldLore.read
INSERT INTO "pipeline_config_notices" ("config_id", "kind", "node_key", "slot", "path", "label", "previous_value")
SELECT c."id", 'culled', l."node_key", l."slot", l."path",
	'session ' || l."scope_id"::text || ' · ' || l."node_key" || '/' || l."path" || ' — folded into gather.worldLore.read, which already held ' || o."value"::text || ' (one owner per setting, R-7 P2)', l."value"
FROM "pipeline_node_overrides" l JOIN "pipeline_node_overrides" o
	ON o."spec_id" = l."spec_id" AND o."scope_kind" = l."scope_kind" AND o."scope_id" = l."scope_id" AND o."node_key" = 'gather.worldLore.read' AND o."slot" = l."slot" AND o."path" = l."path"
	JOIN "pipeline_configs" c ON c."id" = COALESCE(
		(SELECT s."config_id" FROM "pipeline_config_selections" s WHERE s."spec_id" = l."spec_id" AND s."scope_kind" = l."scope_kind" AND s."scope_id" = l."scope_id" AND s."config_id" IS NOT NULL ORDER BY s."id" LIMIT 1),
		(SELECT s."config_id" FROM "pipeline_config_selections" s WHERE s."spec_id" = l."spec_id" AND s."scope_kind" = 'instance' AND s."scope_id" = 0 AND s."config_id" IS NOT NULL LIMIT 1),
		-- the preset-carried config layer is not modelled here
		(SELECT d."id" FROM "pipeline_configs" d WHERE d."spec_id" = l."spec_id" AND d."seed_key" = 'pipeline-default:' || (SELECT "slug" FROM "pipeline_specs" WHERE "id" = l."spec_id") LIMIT 1))
WHERE l."node_key" = 'gather.characterLore.read' AND l."slot" = 'params';--> statement-breakpoint
DELETE FROM "pipeline_node_overrides" l USING "pipeline_node_overrides" o
WHERE o."spec_id" = l."spec_id" AND o."scope_kind" = l."scope_kind" AND o."scope_id" = l."scope_id" AND o."node_key" = 'gather.worldLore.read' AND o."slot" = l."slot" AND o."path" = l."path"
	AND l."node_key" = 'gather.characterLore.read' AND l."slot" = 'params';--> statement-breakpoint
INSERT INTO "pipeline_config_notices" ("config_id", "kind", "node_key", "slot", "path", "label", "previous_value")
SELECT c."id", 'backfilled', 'gather.worldLore.read', l."slot", l."path",
	'session ' || l."scope_id"::text || ' · ' || l."node_key" || '/' || l."path" || ' → gather.worldLore.read/' || l."path" || ' — one setting now governs world lore, character lore and history (was ' || l."value"::text || ')', l."value"
FROM "pipeline_node_overrides" l
	JOIN "pipeline_configs" c ON c."id" = COALESCE(
		(SELECT s."config_id" FROM "pipeline_config_selections" s WHERE s."spec_id" = l."spec_id" AND s."scope_kind" = l."scope_kind" AND s."scope_id" = l."scope_id" AND s."config_id" IS NOT NULL ORDER BY s."id" LIMIT 1),
		(SELECT s."config_id" FROM "pipeline_config_selections" s WHERE s."spec_id" = l."spec_id" AND s."scope_kind" = 'instance' AND s."scope_id" = 0 AND s."config_id" IS NOT NULL LIMIT 1),
		-- the preset-carried config layer is not modelled here
		(SELECT d."id" FROM "pipeline_configs" d WHERE d."spec_id" = l."spec_id" AND d."seed_key" = 'pipeline-default:' || (SELECT "slug" FROM "pipeline_specs" WHERE "id" = l."spec_id") LIMIT 1))
WHERE l."node_key" = 'gather.characterLore.read' AND l."slot" = 'params';--> statement-breakpoint
UPDATE "pipeline_node_overrides" SET "node_key" = 'gather.worldLore.read' WHERE "node_key" = 'gather.characterLore.read' AND "slot" = 'params';--> statement-breakpoint
-- gather.historyEntries.read → gather.worldLore.read
INSERT INTO "pipeline_config_notices" ("config_id", "kind", "node_key", "slot", "path", "label", "previous_value")
SELECT c."id", 'culled', l."node_key", l."slot", l."path",
	'session ' || l."scope_id"::text || ' · ' || l."node_key" || '/' || l."path" || ' — folded into gather.worldLore.read, which already held ' || o."value"::text || ' (one owner per setting, R-7 P2)', l."value"
FROM "pipeline_node_overrides" l JOIN "pipeline_node_overrides" o
	ON o."spec_id" = l."spec_id" AND o."scope_kind" = l."scope_kind" AND o."scope_id" = l."scope_id" AND o."node_key" = 'gather.worldLore.read' AND o."slot" = l."slot" AND o."path" = l."path"
	JOIN "pipeline_configs" c ON c."id" = COALESCE(
		(SELECT s."config_id" FROM "pipeline_config_selections" s WHERE s."spec_id" = l."spec_id" AND s."scope_kind" = l."scope_kind" AND s."scope_id" = l."scope_id" AND s."config_id" IS NOT NULL ORDER BY s."id" LIMIT 1),
		(SELECT s."config_id" FROM "pipeline_config_selections" s WHERE s."spec_id" = l."spec_id" AND s."scope_kind" = 'instance' AND s."scope_id" = 0 AND s."config_id" IS NOT NULL LIMIT 1),
		-- the preset-carried config layer is not modelled here
		(SELECT d."id" FROM "pipeline_configs" d WHERE d."spec_id" = l."spec_id" AND d."seed_key" = 'pipeline-default:' || (SELECT "slug" FROM "pipeline_specs" WHERE "id" = l."spec_id") LIMIT 1))
WHERE l."node_key" = 'gather.historyEntries.read' AND l."slot" = 'params';--> statement-breakpoint
DELETE FROM "pipeline_node_overrides" l USING "pipeline_node_overrides" o
WHERE o."spec_id" = l."spec_id" AND o."scope_kind" = l."scope_kind" AND o."scope_id" = l."scope_id" AND o."node_key" = 'gather.worldLore.read' AND o."slot" = l."slot" AND o."path" = l."path"
	AND l."node_key" = 'gather.historyEntries.read' AND l."slot" = 'params';--> statement-breakpoint
INSERT INTO "pipeline_config_notices" ("config_id", "kind", "node_key", "slot", "path", "label", "previous_value")
SELECT c."id", 'backfilled', 'gather.worldLore.read', l."slot", l."path",
	'session ' || l."scope_id"::text || ' · ' || l."node_key" || '/' || l."path" || ' → gather.worldLore.read/' || l."path" || ' — one setting now governs world lore, character lore and history (was ' || l."value"::text || ')', l."value"
FROM "pipeline_node_overrides" l
	JOIN "pipeline_configs" c ON c."id" = COALESCE(
		(SELECT s."config_id" FROM "pipeline_config_selections" s WHERE s."spec_id" = l."spec_id" AND s."scope_kind" = l."scope_kind" AND s."scope_id" = l."scope_id" AND s."config_id" IS NOT NULL ORDER BY s."id" LIMIT 1),
		(SELECT s."config_id" FROM "pipeline_config_selections" s WHERE s."spec_id" = l."spec_id" AND s."scope_kind" = 'instance' AND s."scope_id" = 0 AND s."config_id" IS NOT NULL LIMIT 1),
		-- the preset-carried config layer is not modelled here
		(SELECT d."id" FROM "pipeline_configs" d WHERE d."spec_id" = l."spec_id" AND d."seed_key" = 'pipeline-default:' || (SELECT "slug" FROM "pipeline_specs" WHERE "id" = l."spec_id") LIMIT 1))
WHERE l."node_key" = 'gather.historyEntries.read' AND l."slot" = 'params';--> statement-breakpoint
UPDATE "pipeline_node_overrides" SET "node_key" = 'gather.worldLore.read' WHERE "node_key" = 'gather.historyEntries.read' AND "slot" = 'params';--> statement-breakpoint
-- names.arm.embed → semantic.arm.embed
INSERT INTO "pipeline_config_notices" ("config_id", "kind", "node_key", "slot", "path", "label", "previous_value")
SELECT c."id", 'culled', l."node_key", l."slot", l."path",
	'session ' || l."scope_id"::text || ' · ' || l."node_key" || '/' || l."path" || ' — folded into semantic.arm.embed, which already held ' || o."value"::text || ' (one owner per setting, R-7 P2)', l."value"
FROM "pipeline_node_overrides" l JOIN "pipeline_node_overrides" o
	ON o."spec_id" = l."spec_id" AND o."scope_kind" = l."scope_kind" AND o."scope_id" = l."scope_id" AND o."node_key" = 'semantic.arm.embed' AND o."slot" = l."slot" AND o."path" = l."path"
	JOIN "pipeline_configs" c ON c."id" = COALESCE(
		(SELECT s."config_id" FROM "pipeline_config_selections" s WHERE s."spec_id" = l."spec_id" AND s."scope_kind" = l."scope_kind" AND s."scope_id" = l."scope_id" AND s."config_id" IS NOT NULL ORDER BY s."id" LIMIT 1),
		(SELECT s."config_id" FROM "pipeline_config_selections" s WHERE s."spec_id" = l."spec_id" AND s."scope_kind" = 'instance' AND s."scope_id" = 0 AND s."config_id" IS NOT NULL LIMIT 1),
		-- the preset-carried config layer is not modelled here
		(SELECT d."id" FROM "pipeline_configs" d WHERE d."spec_id" = l."spec_id" AND d."seed_key" = 'pipeline-default:' || (SELECT "slug" FROM "pipeline_specs" WHERE "id" = l."spec_id") LIMIT 1))
WHERE l."node_key" = 'names.arm.embed' AND l."slot" = 'params';--> statement-breakpoint
DELETE FROM "pipeline_node_overrides" l USING "pipeline_node_overrides" o
WHERE o."spec_id" = l."spec_id" AND o."scope_kind" = l."scope_kind" AND o."scope_id" = l."scope_id" AND o."node_key" = 'semantic.arm.embed' AND o."slot" = l."slot" AND o."path" = l."path"
	AND l."node_key" = 'names.arm.embed' AND l."slot" = 'params';--> statement-breakpoint
INSERT INTO "pipeline_config_notices" ("config_id", "kind", "node_key", "slot", "path", "label", "previous_value")
SELECT c."id", 'backfilled', 'semantic.arm.embed', l."slot", l."path",
	'session ' || l."scope_id"::text || ' · ' || l."node_key" || '/' || l."path" || ' → semantic.arm.embed/' || l."path" || ' — one switch now governs both embed steps (was ' || l."value"::text || ')', l."value"
FROM "pipeline_node_overrides" l
	JOIN "pipeline_configs" c ON c."id" = COALESCE(
		(SELECT s."config_id" FROM "pipeline_config_selections" s WHERE s."spec_id" = l."spec_id" AND s."scope_kind" = l."scope_kind" AND s."scope_id" = l."scope_id" AND s."config_id" IS NOT NULL ORDER BY s."id" LIMIT 1),
		(SELECT s."config_id" FROM "pipeline_config_selections" s WHERE s."spec_id" = l."spec_id" AND s."scope_kind" = 'instance' AND s."scope_id" = 0 AND s."config_id" IS NOT NULL LIMIT 1),
		-- the preset-carried config layer is not modelled here
		(SELECT d."id" FROM "pipeline_configs" d WHERE d."spec_id" = l."spec_id" AND d."seed_key" = 'pipeline-default:' || (SELECT "slug" FROM "pipeline_specs" WHERE "id" = l."spec_id") LIMIT 1))
WHERE l."node_key" = 'names.arm.embed' AND l."slot" = 'params';--> statement-breakpoint
UPDATE "pipeline_node_overrides" SET "node_key" = 'semantic.arm.embed' WHERE "node_key" = 'names.arm.embed' AND "slot" = 'params';--> statement-breakpoint

-- 9 · Every stored version was rewritten in place and keeps its pre-rename
-- `canonical_hash`; mark the ACTIVE one per pipeline so the boot's republish
-- reads as *renamed*. Only the active one: a row an edit had already retired
-- was superseded by that edit, and the inspector's *renamed* mark on a
-- receipt pinned to it would say the document had not changed when it had.
UPDATE "pipeline_spec_versions" SET "renamed_at" = CURRENT_TIMESTAMP
WHERE "id" IN (SELECT "active_version_id" FROM "pipeline_specs" WHERE "active_version_id" IS NOT NULL);--> statement-breakpoint
-- ═══════════════════════════════════════════════════════════════════════════
-- end of DATA MOVE — the generated statements resume
-- ═══════════════════════════════════════════════════════════════════════════
-- (moved up from below: the foreign key two lines down needs this unique index to exist first)
CREATE UNIQUE INDEX "pipeline_definition_registry_definition_version_idx" ON "pipeline_definition_registry" USING btree ("definition_id","version");--> statement-breakpoint
ALTER TABLE "lorebook_entries" ADD CONSTRAINT "lorebook_entries_type_fk" FOREIGN KEY ("type_id","type_version") REFERENCES "public"."pipeline_definition_registry"("definition_id","version") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_clauses" ADD CONSTRAINT "pipeline_clauses_spec_version_id_pipeline_spec_versions_id_fk" FOREIGN KEY ("spec_version_id") REFERENCES "public"."pipeline_spec_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_clauses_version_clause_idx" ON "pipeline_clauses" USING btree ("spec_version_id","clause_id");--> statement-breakpoint
CREATE INDEX "pipeline_context_templates_node_definition_idx" ON "pipeline_context_templates" USING btree ("node_definition_id");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_context_templates_node_definition_name_idx" ON "pipeline_context_templates" USING btree ("node_definition_id","engine","name");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_definition_declarations_hash_idx" ON "pipeline_definition_declarations" USING btree ("definition_id","version","content_hash");--> statement-breakpoint
CREATE INDEX "pipeline_definition_declarations_slug_idx" ON "pipeline_definition_declarations" USING btree ("definition_id","version");--> statement-breakpoint
CREATE INDEX "pipeline_context_templates_pool_idx" ON "pipeline_context_templates" USING btree ("node_definition_id","engine");--> statement-breakpoint
CREATE INDEX "pipeline_prompts_pool_idx" ON "pipeline_prompts" USING btree ("node_definition_id","slot");--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_prompts_pool_name_idx" ON "pipeline_prompts" USING btree ("node_definition_id","slot","name");--> statement-breakpoint
ALTER TABLE "pipeline_clauses" ADD CONSTRAINT "pipeline_clauses_kind_check" CHECK ("pipeline_clauses"."kind" IN ('gather', 'each', 'loop', 'junction'));--> statement-breakpoint
ALTER TABLE "pipeline_clauses" ADD CONSTRAINT "pipeline_clauses_bounded_check" CHECK ("pipeline_clauses"."kind" IN ('gather', 'junction') OR "pipeline_clauses"."max" IS NOT NULL);--> statement-breakpoint
ALTER TABLE "pipeline_edges" ADD CONSTRAINT "pipeline_edges_one_source_check" CHECK (("pipeline_edges"."from_node_id" IS NULL) <> ("pipeline_edges"."from_clause_id" IS NULL));--> statement-breakpoint
ALTER TABLE "pipeline_nodes" ADD CONSTRAINT "pipeline_nodes_kind_check" CHECK ("pipeline_nodes"."kind" IN ('inlet', 'query', 'task', 'oracle', 'outlet'));