-- Chat presets (19 §7, U-C6): the mode-scoped bundle of the user's stack.
--
-- Presets select; they never contain. `selections` holds references —
-- pipeline-config ids keyed by spec slug — plus seed values for the mode's
-- declared fields. Applying writes chat-scope pipeline_config_selections
-- rows; removing deletes exactly those (reset-is-delete). `applied_preset_id`
-- on chats is how removal knows what to un-select; SET NULL so deleting a
-- preset strands no chat.
CREATE TABLE "chat_presets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chat_presets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text,
	"mode_id" text DEFAULT 'core:input/user-message@1' NOT NULL,
	"selections" json DEFAULT '{}'::json NOT NULL,
	"created_by" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint
ALTER TABLE "chat_presets" ADD CONSTRAINT "chat_presets_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "chat_presets_mode_name_idx" ON "chat_presets" USING btree ("mode_id","name");--> statement-breakpoint
ALTER TABLE "chats" ADD COLUMN "applied_preset_id" integer;--> statement-breakpoint
ALTER TABLE "chats" ADD CONSTRAINT "chats_applied_preset_id_chat_presets_id_fk" FOREIGN KEY ("applied_preset_id") REFERENCES "public"."chat_presets"("id") ON DELETE set null ON UPDATE no action;
