CREATE TABLE "session_changes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_changes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" integer NOT NULL,
	"event" text NOT NULL,
	"message_id" integer,
	"payload" jsonb NOT NULL,
	"run_id" text,
	"at" timestamp DEFAULT now() NOT NULL,
	"consumed_by_run_id" text
);
--> statement-breakpoint
ALTER TABLE "session_messages" ADD COLUMN "generation_outcome" text;--> statement-breakpoint
ALTER TABLE "session_changes" ADD CONSTRAINT "session_changes_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "session_changes_session_unconsumed_idx" ON "session_changes" USING btree ("session_id","consumed_by_run_id","id");