-- The two rebinding seams (19 §3, §5).
--
-- pipeline_function_bindings: "same key, several contributors → the binding
-- selects" — a scope's choice of which spec serves a function for chats of a
-- mode. Resolution chat > user > instance, then the default rule; eligibility
-- is re-checked at read, so a stale row falls through instead of routing
-- wrong. Spec FK cascades: a deleted spec's bindings vanish and the scope
-- inherits again.
--
-- pipeline_node_rebinds: "the chat scope may swap it" — a scope's
-- substitution of which type fills a node position (the next-speaker
-- strategy swap is the first use). Applied at document load, guarded by
-- shape compatibility; the pin is text because the registry re-projects
-- pre-1.0 and a rebind must survive that the way spec pins do.
CREATE TABLE "pipeline_function_bindings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_function_bindings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scope_kind" text NOT NULL,
	"scope_id" integer DEFAULT 0 NOT NULL,
	"mode_id" text NOT NULL,
	"function_key" text NOT NULL,
	"spec_id" integer NOT NULL,
	"updated_by" integer,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_function_bindings_scope_check" CHECK ("pipeline_function_bindings"."scope_kind" IN ('instance', 'user', 'chat'))
);--> statement-breakpoint
ALTER TABLE "pipeline_function_bindings" ADD CONSTRAINT "pipeline_function_bindings_spec_id_pipeline_specs_id_fk" FOREIGN KEY ("spec_id") REFERENCES "public"."pipeline_specs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_function_bindings" ADD CONSTRAINT "pipeline_function_bindings_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_function_bindings_addr_idx" ON "pipeline_function_bindings" USING btree ("scope_kind","scope_id","mode_id","function_key");--> statement-breakpoint
CREATE TABLE "pipeline_node_rebinds" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_node_rebinds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_id" integer NOT NULL,
	"scope_kind" text NOT NULL,
	"scope_id" integer DEFAULT 0 NOT NULL,
	"node_key" text NOT NULL,
	"type_id" text NOT NULL,
	"updated_by" integer,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pipeline_node_rebinds_scope_check" CHECK ("pipeline_node_rebinds"."scope_kind" IN ('instance', 'user', 'chat'))
);--> statement-breakpoint
ALTER TABLE "pipeline_node_rebinds" ADD CONSTRAINT "pipeline_node_rebinds_spec_id_pipeline_specs_id_fk" FOREIGN KEY ("spec_id") REFERENCES "public"."pipeline_specs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_node_rebinds" ADD CONSTRAINT "pipeline_node_rebinds_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_node_rebinds_addr_idx" ON "pipeline_node_rebinds" USING btree ("spec_id","scope_kind","scope_id","node_key");
