-- Which of a mode's functions a chat actually has (19 §3).
--
-- §3 rules that a contribution from the mode owner's own namespace is a
-- *companion* — present by default, toggleable — and a foreign one is an
-- *attachment*, per-user opt-in. Both halves were design until now: every chat
-- of a mode rendered every trigger contributed to it, and `triggerFunction`
-- fired any of them, with nothing anywhere able to say otherwise.
--
-- Rows are exceptions. One exists only where a choice differs from the default
-- for that function, and returning a function to its default deletes the row —
-- reset-is-delete, as everywhere else. A chat with no rows behaves exactly as
-- it did before this table, and a companion arriving in a later update reaches
-- every chat that never expressed an opinion.
--
-- Keyed by the full mode id because the choice was made about *this mode's*
-- function. Mode upgrades move along the same bare type (19 §6), so a version
-- that retires a function leaves no stale row deciding anything.
CREATE TABLE "chat_functions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"chat_id" integer NOT NULL,
	"mode_id" text NOT NULL,
	"function_key" text NOT NULL,
	"enabled" boolean NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "chat_functions" ADD CONSTRAINT "chat_functions_chat_id_chats_id_fk"
	FOREIGN KEY ("chat_id") REFERENCES "public"."chats"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE UNIQUE INDEX "chat_functions_chat_mode_fn_idx"
	ON "chat_functions" ("chat_id","mode_id","function_key");
