CREATE TABLE "seen_actions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "seen_actions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"action_key" text NOT NULL,
	"seen_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "seen_actions" ADD CONSTRAINT "seen_actions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "seen_actions_user_action_idx" ON "seen_actions" USING btree ("user_id","action_key");--> statement-breakpoint
-- A preset's included set is keyed by action identity (`<spec slug>#<key>`;
-- U5c review W-A, ruled 2026-09-16). Rows written before that carried bare
-- function keys (`narrate`). The two writers were `sessionPresets:update`
-- (session_presets) and `pipelines:setPresetActions` (the legacy squat on
-- pipeline_configs), so both columns are rewritten: each bare key becomes
-- the identity of the ONE action declaring that function for that genre —
-- a published active version, of ANY namespace (third pass, W4+W2): an
-- attachment an admin included was valid when they included it, and losing
-- it silently would be worse than keeping it. A key no action declares, or
-- that several declare (`HAVING count(*) = 1` — never a first-by-id pick,
-- which would prefer a `core:` declarer over a plugin genre's own), is left
-- bare: the read-side fallback (`presetIncludes`) still answers for it by
-- the same sole-declarer rule, one release, and the boot notice in
-- `seedSessionPresets` lists it. Identities already in the list, and
-- anything else, pass through untouched, so re-running this is a no-op.
-- `coalesce(…, '[]')`: `json_agg` over no rows is NULL, and NULL here means
-- "no opinion — companion defaults", which is the opposite of a curated
-- empty set; `[]` must survive as `[]`.
UPDATE "session_presets" p
SET "included_actions" = (
	SELECT coalesce(json_agg(
		CASE
			WHEN e.v LIKE '%#%' THEN e.v
			ELSE coalesce(c.identity, e.v)
		END
		ORDER BY e.ord
	), '[]'::json)
	FROM json_array_elements_text(p."included_actions") WITH ORDINALITY AS e(v, ord)
	LEFT JOIN LATERAL (
		-- One group per bare key; a row only when exactly one action declares
		-- it, so min() over that one row is its identity.
		SELECT min(s."slug" || '#' || coalesce(a.value->>'key', a.value->>'function')) AS identity
		FROM "pipeline_specs" s
		JOIN "pipeline_spec_versions" v
			ON v."id" = s."active_version_id" AND v."status" = 'published'
		CROSS JOIN LATERAL (
			SELECT value FROM json_array_elements(coalesce(v."contributes"->'actions', '[]'::json))
			UNION ALL
			SELECT value FROM json_array_elements(coalesce(v."contributes"->'triggers', '[]'::json))
		) AS a(value)
		WHERE a.value->>'function' = e.v
			AND coalesce(a.value->>'genre', a.value->>'mode') = p."genre_id"
		HAVING count(*) = 1
	) c ON true
)
WHERE json_typeof(p."included_actions") = 'array';--> statement-breakpoint
UPDATE "pipeline_configs" pc
SET "included_actions" = (
	SELECT coalesce(json_agg(
		CASE
			WHEN e.v LIKE '%#%' THEN e.v
			ELSE coalesce(c.identity, e.v)
		END
		ORDER BY e.ord
	), '[]'::json)
	FROM json_array_elements_text(pc."included_actions") WITH ORDINALITY AS e(v, ord)
	LEFT JOIN LATERAL (
		SELECT min(s."slug" || '#' || coalesce(a.value->>'key', a.value->>'function')) AS identity
		FROM "pipeline_specs" s
		JOIN "pipeline_spec_versions" v
			ON v."id" = s."active_version_id" AND v."status" = 'published'
		CROSS JOIN LATERAL (
			SELECT value FROM json_array_elements(coalesce(v."contributes"->'actions', '[]'::json))
			UNION ALL
			SELECT value FROM json_array_elements(coalesce(v."contributes"->'triggers', '[]'::json))
		) AS a(value)
		WHERE a.value->>'function' = e.v
			AND coalesce(a.value->>'genre', a.value->>'mode') = g."genre_id"
		HAVING count(*) = 1
	) c ON true
)
FROM (
	-- The genre a configuration's pipeline serves: its active version's input
	-- lock (24 §4). A pipeline serving no genre has no declarer to name.
	SELECT cfg."id" AS config_id, ver."input_genre" AS genre_id
	FROM "pipeline_configs" cfg
	JOIN "pipeline_specs" ps ON ps."id" = cfg."spec_id"
	JOIN "pipeline_spec_versions" ver ON ver."id" = ps."active_version_id"
	WHERE ver."input_genre" IS NOT NULL
) g
WHERE g.config_id = pc."id"
	AND json_typeof(pc."included_actions") = 'array';
