CREATE TABLE "user_layout_defaults" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_layout_defaults_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"genre_id" text NOT NULL,
	"layout_preset_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "user_layout_defaults" ADD CONSTRAINT "user_layout_defaults_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_layout_defaults" ADD CONSTRAINT "user_layout_defaults_layout_preset_id_session_layout_presets_id_fk" FOREIGN KEY ("layout_preset_id") REFERENCES "public"."session_layout_presets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "user_layout_defaults_user_genre_idx" ON "user_layout_defaults" USING btree ("user_id","genre_id");