-- Plugins / extensions (behind the SP_PLUGINS_ENABLED gate).
--
-- Two tables land together: `plugins` is the installed set the RuntimeManager
-- dispatches against (bundle + hash + certified backends + the active-backend
-- dial + the compiled manifest of hooks/components/pipelines/permissions), and
-- `plugin_hook_invocations` is the observability log. The log's identity is
-- denormalized (name + hash, no FK) so a row outlives the plugin's uninstall,
-- and it carries a soft `run_id` link so pipeline logs reference hook timing
-- here rather than duplicating it. Hand-written like every migration since 0112
-- — the drizzle-kit snapshot froze there and the recent renames are raw SQL.
CREATE TABLE "plugins" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plugins_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"plugin_id" text NOT NULL,
	"name" text NOT NULL,
	"version" text DEFAULT '0.0.0' NOT NULL,
	"bundle_source" text NOT NULL,
	"bundle_hash" text NOT NULL,
	"backends" json DEFAULT '["quickjs"]'::json NOT NULL,
	"backend" text DEFAULT 'quickjs' NOT NULL,
	"sequential" boolean DEFAULT false NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"manifest" json DEFAULT '{}'::json NOT NULL,
	"installed_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "plugins_plugin_id_unique" UNIQUE("plugin_id"),
	CONSTRAINT "plugins_backend_check" CHECK ("backend" IN ('quickjs', 'ses'))
);
--> statement-breakpoint
CREATE TABLE "plugin_hook_invocations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plugin_hook_invocations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"plugin_id" text NOT NULL,
	"plugin_name" text NOT NULL,
	"bundle_hash" text NOT NULL,
	"hook_name" text NOT NULL,
	"backend" text NOT NULL,
	"mode" text NOT NULL,
	"triggered_by" text,
	"run_id" text,
	"queued_at" timestamp NOT NULL,
	"started_at" timestamp NOT NULL,
	"finished_at" timestamp NOT NULL,
	"duration_ms" integer NOT NULL,
	"ok" boolean NOT NULL,
	"outcome" text NOT NULL,
	"reason" text
);
--> statement-breakpoint
CREATE INDEX "plugin_hook_invocations_plugin_idx" ON "plugin_hook_invocations" USING btree ("plugin_id","finished_at");--> statement-breakpoint
CREATE INDEX "plugin_hook_invocations_run_idx" ON "plugin_hook_invocations" USING btree ("run_id");
