CREATE TABLE "attribute_declarations" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" integer,
	"origin" text DEFAULT 'stored' NOT NULL,
	"props" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"retired_at" timestamp,
	"last_seen_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "attribute_declarations_origin_check" CHECK ("attribute_declarations"."origin" IN ('stored', 'code', 'plugin'))
);
--> statement-breakpoint
CREATE TABLE "attribute_sheets" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" integer,
	"origin" text DEFAULT 'stored' NOT NULL,
	"props" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"retired_at" timestamp,
	"last_seen_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "attribute_sheets_origin_check" CHECK ("attribute_sheets"."origin" IN ('stored', 'code', 'plugin'))
);
--> statement-breakpoint
CREATE TABLE "owner_sheets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "owner_sheets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"owner_kind" text NOT NULL,
	"owner_id" integer NOT NULL,
	"sheet_id" text NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "owner_sheets_owner_kind_check" CHECK ("owner_sheets"."owner_kind" IN ('card', 'cast_member', 'lorebook', 'session', 'session_cast'))
);
--> statement-breakpoint
ALTER TABLE "attribute_configs" ADD COLUMN "branch_id" integer;--> statement-breakpoint
ALTER TABLE "attribute_configs" ADD COLUMN "history_entry_id" integer;--> statement-breakpoint
ALTER TABLE "attribute_configs" ADD COLUMN "scene_id" integer;--> statement-breakpoint
ALTER TABLE "attribute_configs" ADD COLUMN "source_session_id" integer;--> statement-breakpoint
ALTER TABLE "attribute_configs" ADD COLUMN "source_message_id" integer;--> statement-breakpoint
ALTER TABLE "attribute_configs" ADD COLUMN "note" text;--> statement-breakpoint
ALTER TABLE "attribute_values" ADD COLUMN "branch_id" integer;--> statement-breakpoint
ALTER TABLE "attribute_values" ADD COLUMN "history_entry_id" integer;--> statement-breakpoint
ALTER TABLE "attribute_values" ADD COLUMN "scene_id" integer;--> statement-breakpoint
ALTER TABLE "attribute_values" ADD COLUMN "source_session_id" integer;--> statement-breakpoint
ALTER TABLE "attribute_values" ADD COLUMN "source_message_id" integer;--> statement-breakpoint
ALTER TABLE "attribute_values" ADD COLUMN "note" text;--> statement-breakpoint
ALTER TABLE "session_possessions" ADD COLUMN "branch_id" integer;--> statement-breakpoint
ALTER TABLE "session_possessions" ADD COLUMN "history_entry_id" integer;--> statement-breakpoint
ALTER TABLE "session_possessions" ADD COLUMN "scene_id" integer;--> statement-breakpoint
ALTER TABLE "session_possessions" ADD COLUMN "source_session_id" integer;--> statement-breakpoint
ALTER TABLE "session_possessions" ADD COLUMN "source_message_id" integer;--> statement-breakpoint
ALTER TABLE "attribute_declarations" ADD CONSTRAINT "attribute_declarations_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attribute_sheets" ADD CONSTRAINT "attribute_sheets_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "owner_sheets" ADD CONSTRAINT "owner_sheets_sheet_id_attribute_sheets_id_fk" FOREIGN KEY ("sheet_id") REFERENCES "public"."attribute_sheets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "attribute_declarations_origin_idx" ON "attribute_declarations" USING btree ("origin");--> statement-breakpoint
CREATE INDEX "attribute_declarations_user_idx" ON "attribute_declarations" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "attribute_sheets_origin_idx" ON "attribute_sheets" USING btree ("origin");--> statement-breakpoint
CREATE INDEX "attribute_sheets_user_idx" ON "attribute_sheets" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "owner_sheets_owner_idx" ON "owner_sheets" USING btree ("owner_kind","owner_id","position");--> statement-breakpoint
CREATE UNIQUE INDEX "owner_sheets_owner_sheet_uq" ON "owner_sheets" USING btree ("owner_kind","owner_id","sheet_id");--> statement-breakpoint
ALTER TABLE "attribute_configs" ADD CONSTRAINT "attribute_configs_history_entry_id_lorebook_entries_id_fk" FOREIGN KEY ("history_entry_id") REFERENCES "public"."lorebook_entries"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attribute_configs" ADD CONSTRAINT "attribute_configs_scene_id_scenes_id_fk" FOREIGN KEY ("scene_id") REFERENCES "public"."scenes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attribute_values" ADD CONSTRAINT "attribute_values_history_entry_id_lorebook_entries_id_fk" FOREIGN KEY ("history_entry_id") REFERENCES "public"."lorebook_entries"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attribute_values" ADD CONSTRAINT "attribute_values_scene_id_scenes_id_fk" FOREIGN KEY ("scene_id") REFERENCES "public"."scenes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_possessions" ADD CONSTRAINT "session_possessions_history_entry_id_lorebook_entries_id_fk" FOREIGN KEY ("history_entry_id") REFERENCES "public"."lorebook_entries"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_possessions" ADD CONSTRAINT "session_possessions_scene_id_scenes_id_fk" FOREIGN KEY ("scene_id") REFERENCES "public"."scenes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "attribute_configs_moment_idx" ON "attribute_configs" USING btree ("owner_kind","owner_id","history_entry_id");--> statement-breakpoint
CREATE INDEX "attribute_values_moment_idx" ON "attribute_values" USING btree ("owner_kind","owner_id","history_entry_id");--> statement-breakpoint
CREATE INDEX "session_possessions_moment_idx" ON "session_possessions" USING btree ("owner_kind","owner_id","history_entry_id");
