-- The message model (20 §1, ruled 2026-08-26): messages are folders of typed
-- parts addressed by (step, revision, ordinal). `session_messages` becomes a
-- legacy mirror maintained by the message store until every reader migrates.
-- The DATA migration is boot-time TypeScript (idempotent, 0.5-migrate
-- precedent) because exploding `metadata.swipes` JSON into part rows belongs
-- in tested code, not hand-rolled SQL.
CREATE TABLE "messages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"session_id" integer NOT NULL REFERENCES "sessions"("id") ON DELETE CASCADE,
	"channel" text NOT NULL DEFAULT 'main',
	"kind" text NOT NULL DEFAULT 'core:chat',
	-- Nullable, NO default: written '1.0' by every creating code path. The
	-- null/value split is the upgrade hook (ruled 2026-08-26).
	"version" text,
	"user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
	"character_id" integer REFERENCES "characters"("id") ON DELETE SET NULL,
	"persona_id" integer REFERENCES "personas"("id") ON DELETE SET NULL,
	"speaker_label" text,
	"role" text NOT NULL,
	"status" text NOT NULL DEFAULT 'settled',
	"error" json,
	"active_revisions" json NOT NULL DEFAULT '{"0":0}',
	"extras" json NOT NULL DEFAULT '{}',
	"is_hidden" boolean NOT NULL DEFAULT false,
	"is_edited" boolean NOT NULL DEFAULT false,
	"debug_meta" json,
	"queue_item_id" text,
	"created_at" timestamp NOT NULL DEFAULT now(),
	"updated_at" timestamp NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX "messages_session_id_idx" ON "messages" ("session_id");
--> statement-breakpoint
CREATE INDEX "messages_session_channel_idx" ON "messages" ("session_id", "channel");
--> statement-breakpoint

CREATE TABLE "message_parts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"message_id" integer NOT NULL REFERENCES "messages"("id") ON DELETE CASCADE,
	"step" integer NOT NULL DEFAULT 0,
	"revision" integer NOT NULL DEFAULT 0,
	"ordinal" integer NOT NULL DEFAULT 0,
	"type" text NOT NULL,
	"content" text,
	"data" json
);
--> statement-breakpoint
CREATE UNIQUE INDEX "message_parts_addr_idx"
	ON "message_parts" ("message_id", "step", "revision", "ordinal");
--> statement-breakpoint

CREATE TABLE "session_assets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"session_id" integer NOT NULL REFERENCES "sessions"("id") ON DELETE CASCADE,
	"hash" text NOT NULL,
	"mime" text NOT NULL,
	"bytes" integer NOT NULL,
	"path" text NOT NULL,
	"created_by" integer REFERENCES "users"("id") ON DELETE SET NULL,
	"created_at" timestamp NOT NULL DEFAULT now()
);
--> statement-breakpoint

-- Connection modalities (20 §14): the connections table represents any kind
-- of model endpoint; a provider node's declared shape filters the picker and
-- the binding refuses a mismatch (F17). Every existing row is a text model.
ALTER TABLE "connections" ADD COLUMN "modality" text NOT NULL DEFAULT 'text-gen';
--> statement-breakpoint

-- The one active embedding connection, site-wide. Populated when the
-- vectorization endpoint config migrates into connections (phase 1b data
-- migration); null until then.
ALTER TABLE "system_settings" ADD COLUMN "active_embedding_connection_id" integer
	REFERENCES "connections"("id") ON DELETE SET NULL;
