-- A plugin's client-side files (20 §12): what its frame surfaces load. Served
-- under a grant-composed CSP, mounted only inside opaque-origin sandboxes.
CREATE TABLE "plugin_files" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"plugin_id" text NOT NULL,
	"path" text NOT NULL,
	"mime" text NOT NULL,
	"content" text NOT NULL,
	"hash" text NOT NULL,
	"bytes" integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "plugin_files_plugin_path_idx" ON "plugin_files" ("plugin_id", "path");
