-- HAND-EDITED, and this is the whole of the edit: the DATA MOVE block below was
-- INSERTED before the one generated statement (the DROP COLUMN). Generated by
-- `drizzle-kit generate` against a scratch data dir; nothing generated was
-- changed or removed.
--
-- The socket pre-pick retired (plans/19 §5 U-C5, closed 2026-09-21): who
-- speaks next is decided by the respond spec's `speaker` node, pinned to
-- `core:task/turn-round-robin@1`, and a session's choice is its rebind of that
-- node (`pipeline_node_rebinds`, scope `session`) — the same row the Turn order
-- control has written since U-C4. `sessions.group_reply_strategy` was the
-- pre-pick's vocabulary and dies with it (NOMENCLATURE §23):
--
--   · `ordered`   → nothing: round robin is the spec's own pin now;
--   · `manual`    → a rebind to `core:task/turn-manual@1`;
--   · `userSplit` → a rebind to `core:task/turn-user-split@1`.
--
-- Only sessions whose replies run `core:spec/respond` carry a row: the guide
-- and writing-room genres never read the column, and the adventure family
-- seats no speaker node. A fresh install has no sessions and no spec row yet,
-- and the join is empty either way. A rebind the control already wrote wins
-- (`ON CONFLICT DO NOTHING`): the person's later choice is not overwritten by
-- the column's earlier one.
INSERT INTO "pipeline_node_rebinds" ("spec_id", "scope_kind", "scope_id", "node_key", "definition_id", "updated_by", "updated_at")
SELECT
	ps."id",
	'session',
	s."id",
	'speaker',
	CASE s."group_reply_strategy"
		WHEN 'manual' THEN 'core:task/turn-manual@1'
		WHEN 'userSplit' THEN 'core:task/turn-user-split@1'
	END,
	s."user_id",
	now()
FROM "sessions" s
JOIN "pipeline_specs" ps ON ps."slug" = 'core:spec/respond'
WHERE s."group_reply_strategy" IN ('manual', 'userSplit')
	AND s."genre_id" IN ('core:genre/chat', 'core:spec/create-chat', 'core:inlet/user-message@1')
ON CONFLICT ("spec_id", "scope_kind", "scope_id", "node_key") DO NOTHING;--> statement-breakpoint
ALTER TABLE "sessions" DROP COLUMN "group_reply_strategy";
