-- Per-user, per-session surface-grid layout (21 §10). Availability is
-- declaration (recomputed, never stored); only activation + placement live
-- here. No row → the client derives defaults from the mode's declared panels.
CREATE TABLE "session_panel_layouts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"session_id" integer NOT NULL REFERENCES "sessions"("id") ON DELETE CASCADE,
	"user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
	"layout" json NOT NULL DEFAULT '{}'::json,
	"created_at" timestamp NOT NULL DEFAULT now(),
	"updated_at" timestamp NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE UNIQUE INDEX "session_panel_layouts_user_session_idx" ON "session_panel_layouts" ("user_id", "session_id");
