-- Session presets (23 §9): the bundle a person chooses to start a session —
-- type (create spec), optional primary variant, config selections, action
-- curation. Plus per-type availability administration, and the session's
-- record of the preset it was born from.
CREATE TABLE "session_presets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"seed_key" text UNIQUE,
	"name" text NOT NULL,
	"description" text,
	"type_slug" text NOT NULL,
	"primary_slug" text,
	"config_selections" json NOT NULL DEFAULT '{}'::json,
	"included_actions" json,
	"defaults" json,
	"enabled" boolean NOT NULL DEFAULT true,
	"is_default" boolean NOT NULL DEFAULT false,
	"is_immutable" boolean NOT NULL DEFAULT false,
	"created_at" timestamp NOT NULL DEFAULT now(),
	"updated_at" timestamp NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX "session_presets_type_idx" ON "session_presets" ("type_slug");
--> statement-breakpoint
CREATE TABLE "session_type_settings" (
	"type_slug" text PRIMARY KEY,
	"enabled" boolean NOT NULL DEFAULT true,
	"default_preset_id" integer,
	"updated_at" timestamp NOT NULL DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "preset_id" integer;
