CREATE TABLE "character_amendments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "character_amendments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"character_id" integer NOT NULL,
	"lorebook_id" integer,
	"branch_id" integer,
	"year" integer NOT NULL,
	"month" integer,
	"day" integer,
	"fields" json DEFAULT '{}'::json NOT NULL,
	"history_entry_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "character_amendments_date_check" CHECK (("character_amendments"."month" IS NOT NULL OR "character_amendments"."day" IS NULL)),
	CONSTRAINT "character_amendments_branch_book_check" CHECK (("character_amendments"."branch_id" IS NULL OR "character_amendments"."lorebook_id" IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "entry_amendments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "entry_amendments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lorebook_id" integer NOT NULL,
	"entry_id" integer NOT NULL,
	"branch_id" integer,
	"year" integer NOT NULL,
	"month" integer,
	"day" integer,
	"fields" json DEFAULT '{}'::json NOT NULL,
	"history_entry_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "entry_amendments_date_check" CHECK (("entry_amendments"."month" IS NOT NULL OR "entry_amendments"."day" IS NULL))
);
--> statement-breakpoint
CREATE TABLE "lorebook_branches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lorebook_branches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lorebook_id" integer NOT NULL,
	"name" text NOT NULL,
	"forked_from_branch_id" integer,
	"fork_year" integer,
	"fork_month" integer,
	"fork_day" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "lorebook_branches_name_check" CHECK (lower("lorebook_branches"."name") <> 'main' AND "lorebook_branches"."name" <> '')
);
--> statement-breakpoint
ALTER TABLE "character_amendments" ADD CONSTRAINT "character_amendments_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "character_amendments" ADD CONSTRAINT "character_amendments_lorebook_id_lorebooks_id_fk" FOREIGN KEY ("lorebook_id") REFERENCES "public"."lorebooks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "character_amendments" ADD CONSTRAINT "character_amendments_branch_id_lorebook_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."lorebook_branches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "character_amendments" ADD CONSTRAINT "character_amendments_history_entry_id_lorebook_entries_id_fk" FOREIGN KEY ("history_entry_id") REFERENCES "public"."lorebook_entries"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entry_amendments" ADD CONSTRAINT "entry_amendments_lorebook_id_lorebooks_id_fk" FOREIGN KEY ("lorebook_id") REFERENCES "public"."lorebooks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entry_amendments" ADD CONSTRAINT "entry_amendments_entry_id_lorebook_entries_id_fk" FOREIGN KEY ("entry_id") REFERENCES "public"."lorebook_entries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entry_amendments" ADD CONSTRAINT "entry_amendments_branch_id_lorebook_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."lorebook_branches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entry_amendments" ADD CONSTRAINT "entry_amendments_history_entry_id_lorebook_entries_id_fk" FOREIGN KEY ("history_entry_id") REFERENCES "public"."lorebook_entries"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lorebook_branches" ADD CONSTRAINT "lorebook_branches_lorebook_id_lorebooks_id_fk" FOREIGN KEY ("lorebook_id") REFERENCES "public"."lorebooks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lorebook_branches" ADD CONSTRAINT "lorebook_branches_forked_from_branch_id_lorebook_branches_id_fk" FOREIGN KEY ("forked_from_branch_id") REFERENCES "public"."lorebook_branches"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "character_amendments_character_date_idx" ON "character_amendments" USING btree ("character_id","year","month","day");--> statement-breakpoint
CREATE INDEX "character_amendments_book_idx" ON "character_amendments" USING btree ("lorebook_id");--> statement-breakpoint
CREATE INDEX "entry_amendments_book_idx" ON "entry_amendments" USING btree ("lorebook_id");--> statement-breakpoint
CREATE INDEX "entry_amendments_entry_date_idx" ON "entry_amendments" USING btree ("entry_id","year","month","day");--> statement-breakpoint
CREATE UNIQUE INDEX "lorebook_branches_book_name" ON "lorebook_branches" USING btree ("lorebook_id","name");