-- Remote access, phase A (26 §2–§3): the `servers` anchor and the `tunnels`
-- row. `servers` is deliberately thin — an instance-level identity for
-- non-model-provider settings, not a home for Ollama/KoboldCPP. The seeded
-- `local` row is written by db/defaults.ts sync(), matched on slug rather than
-- a hardcoded id.
CREATE TABLE "servers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"slug" text NOT NULL UNIQUE,
	"name" text NOT NULL,
	"is_seeded" boolean NOT NULL DEFAULT false,
	"created_at" timestamp NOT NULL DEFAULT now()
);
--> statement-breakpoint
-- Its own table, never a row shape under `connections` (26 §3). A connection
-- credential gates what a model says; a tunnel credential gates whether this
-- instance is reachable from the public internet. `provider` and `status` stay
-- open text rather than pg enums so adding a provider later is a data change,
-- not a migration.
CREATE TABLE "tunnels" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"server_id" integer NOT NULL REFERENCES "servers"("id") ON DELETE CASCADE,
	"provider" text NOT NULL,
	"mode" text NOT NULL,
	"credential" json,
	"hostname" text,
	"enabled" boolean NOT NULL DEFAULT false,
	"auto_start" boolean NOT NULL DEFAULT false,
	"status" text NOT NULL DEFAULT 'stopped',
	"last_error" text,
	"ttl_seconds" integer,
	"expires_at" timestamp,
	"started_at" timestamp,
	"stopped_at" timestamp,
	"created_at" timestamp NOT NULL DEFAULT now(),
	"updated_at" timestamp NOT NULL DEFAULT now()
);
--> statement-breakpoint
-- At most one enabled tunnel per server. Partial, so any number of disabled
-- rows coexist; the failure it prevents is physical — two tunnel processes
-- fighting over the same local port.
CREATE UNIQUE INDEX "tunnels_one_enabled_per_server" ON "tunnels" ("server_id") WHERE "enabled";
