CREATE TABLE "cast_amendments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cast_amendments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lorebook_binding_id" integer NOT NULL,
	"lorebook_id" integer NOT NULL,
	"branch_id" integer,
	"year" integer NOT NULL,
	"month" integer,
	"day" integer,
	"fields" json DEFAULT '{}'::json NOT NULL,
	"history_entry_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "cast_amendments_date_check" CHECK (("cast_amendments"."month" IS NOT NULL OR "cast_amendments"."day" IS NULL))
);
--> statement-breakpoint
ALTER TABLE "cast_amendments" ADD CONSTRAINT "cast_amendments_lorebook_binding_id_lorebook_bindings_id_fk" FOREIGN KEY ("lorebook_binding_id") REFERENCES "public"."lorebook_bindings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cast_amendments" ADD CONSTRAINT "cast_amendments_lorebook_id_lorebooks_id_fk" FOREIGN KEY ("lorebook_id") REFERENCES "public"."lorebooks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cast_amendments" ADD CONSTRAINT "cast_amendments_branch_id_lorebook_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."lorebook_branches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cast_amendments" ADD CONSTRAINT "cast_amendments_history_entry_id_lorebook_entries_id_fk" FOREIGN KEY ("history_entry_id") REFERENCES "public"."lorebook_entries"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "cast_amendments_member_date_idx" ON "cast_amendments" USING btree ("lorebook_binding_id","year","month","day");--> statement-breakpoint
CREATE INDEX "cast_amendments_book_idx" ON "cast_amendments" USING btree ("lorebook_id");