CREATE TABLE "ranking_decisions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ranking_decisions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ranking_id" integer NOT NULL,
	"subject_kind" text NOT NULL,
	"subject_id" text NOT NULL,
	"included" boolean NOT NULL,
	"reason" text NOT NULL,
	"score" real,
	"rank" integer,
	"tokens" integer,
	"why" text,
	"detail" jsonb
);
--> statement-breakpoint
CREATE TABLE "ranking_subject_stats" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ranking_subject_stats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" integer NOT NULL,
	"subject_kind" text NOT NULL,
	"subject_id" text NOT NULL,
	"times_judged" integer DEFAULT 0 NOT NULL,
	"times_included" integer DEFAULT 0 NOT NULL,
	"last_ranking_id" integer,
	"last_judged_at" timestamp,
	"last_included_at" timestamp,
	"last_included" boolean,
	"last_reason" text,
	"last_rank" integer,
	"last_score" real
);
--> statement-breakpoint
CREATE TABLE "rankings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rankings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"run_id" integer NOT NULL,
	"node_key" text NOT NULL,
	"definition_id" text NOT NULL,
	"session_id" integer,
	"speaker_ref" text,
	"user_id" integer,
	"candidates_judged" integer DEFAULT 0 NOT NULL,
	"decisions_stored" integer DEFAULT 0 NOT NULL,
	"budget_total" integer,
	"detail" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "ranking_retention" integer DEFAULT 200 NOT NULL;--> statement-breakpoint
ALTER TABLE "ranking_decisions" ADD CONSTRAINT "ranking_decisions_ranking_id_rankings_id_fk" FOREIGN KEY ("ranking_id") REFERENCES "public"."rankings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rankings" ADD CONSTRAINT "rankings_run_id_pipeline_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."pipeline_runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ranking_decisions_ranking_idx" ON "ranking_decisions" USING btree ("ranking_id");--> statement-breakpoint
CREATE INDEX "ranking_decisions_subject_idx" ON "ranking_decisions" USING btree ("subject_kind","subject_id","ranking_id");--> statement-breakpoint
CREATE UNIQUE INDEX "ranking_subject_stats_unique" ON "ranking_subject_stats" USING btree ("session_id","subject_kind","subject_id");--> statement-breakpoint
CREATE INDEX "rankings_session_idx" ON "rankings" USING btree ("session_id","id");--> statement-breakpoint
CREATE INDEX "rankings_run_idx" ON "rankings" USING btree ("run_id");