-- Two-factor authentication (26 §10) and the environment-driven break-glass
-- reset (26 §10, tier 3).
--
-- `enabled_at` is nullable on purpose: a secret exists from the moment it is
-- generated, but the factor only takes effect once the user has proved they can
-- produce a code from it. Enrolling before that verification would lock a user
-- out using a secret they never successfully scanned.
CREATE TABLE "user_totp" (
	"user_id" integer PRIMARY KEY REFERENCES "users"("id") ON DELETE CASCADE,
	"secret" json NOT NULL,
	"enabled_at" timestamp,
	"last_used_step" integer,
	"created_at" timestamp NOT NULL DEFAULT now()
);
--> statement-breakpoint
-- Rows survive use rather than being deleted, so "how many are left" stays
-- answerable and a consumed code can never silently become valid again.
CREATE TABLE "user_totp_recovery_codes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
	"code_hash" text NOT NULL,
	"used_at" timestamp,
	"created_at" timestamp NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX "user_totp_recovery_codes_user_idx" ON "user_totp_recovery_codes" ("user_id");
--> statement-breakpoint
-- NULL = this session has not cleared the second factor. A timestamp rather
-- than a boolean so step-up re-auth ("verified within the last N minutes") can
-- be added later without a schema change.
ALTER TABLE "user_tokens" ADD COLUMN "mfa_verified_at" timestamp;
--> statement-breakpoint
-- The whole one-time-use mechanism for SERENE_PUB_RECOVERY_KEY: a key whose
-- hash differs from this is applied and recorded; one that matches has already
-- been used and is ignored.
ALTER TABLE "system_settings" ADD COLUMN "recovery_key_hash" text;
