-- Widget styles (PLAN 25, ruled 2026-08-30): the skins a session widget wears.
-- ONE table for both the presets a widget ships (source='system', seeded and
-- pruned by the boot reconciler, owner null) and the styles users create
-- (source='user', owner set). `slug` is the stable, reseed-safe target a saved
-- layout pins with its id+slug reference; the reconciler matches system rows on
-- it, never on a numeric id (the codified seed rule), and every write it makes
-- is scoped source='system' so a user row is never touched. `source` and
-- `visibility` stay open text with CHECKs rather than pg enums so adding a value
-- later is a data change, not a migration. Pre-release, these squash.
CREATE TABLE "widget_styles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"slug" text NOT NULL UNIQUE,
	"widget_slug" text NOT NULL,
	"source" text NOT NULL DEFAULT 'user',
	"owner_user_id" integer REFERENCES "users"("id") ON DELETE CASCADE,
	"visibility" text NOT NULL DEFAULT 'private',
	"title" text NOT NULL,
	"css" text NOT NULL DEFAULT '',
	"vars" json NOT NULL DEFAULT '{}'::json,
	"seeded_by_version" text,
	"created_at" timestamp NOT NULL DEFAULT now(),
	"updated_at" timestamp NOT NULL DEFAULT now(),
	CONSTRAINT "widget_styles_source_check" CHECK ("source" IN ('system', 'user')),
	CONSTRAINT "widget_styles_visibility_check" CHECK ("visibility" IN ('system', 'private', 'shared'))
);
--> statement-breakpoint
CREATE INDEX "widget_styles_widget_idx" ON "widget_styles" ("widget_slug");
--> statement-breakpoint
CREATE INDEX "widget_styles_owner_idx" ON "widget_styles" ("owner_user_id");
