-- Account provisioning (27 §3–§5): one-time invites, a site-wide two-factor
-- requirement, and the last-login stamp that gates promotion to admin.
CREATE TABLE "account_invites" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"token_hash" text NOT NULL UNIQUE,
	"kind" text NOT NULL,
	"user_id" integer REFERENCES "users"("id") ON DELETE CASCADE,
	"created_by" integer REFERENCES "users"("id") ON DELETE SET NULL,
	"expires_at" timestamp NOT NULL,
	"used_at" timestamp,
	"revoked_at" timestamp,
	"created_at" timestamp NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX "account_invites_user_idx" ON "account_invites" ("user_id");
--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "require_two_factor" boolean NOT NULL DEFAULT false;
--> statement-breakpoint
-- NULL = never signed in. An account cannot be promoted to admin until this is
-- set: a freshly created or invited account is an unproven claim about who
-- holds it.
ALTER TABLE "users" ADD COLUMN "last_login_at" timestamp;
--> statement-breakpoint
-- Existing accounts predate the stamp and have demonstrably been used, so they
-- are backfilled rather than being locked out of admin promotion.
UPDATE "users" SET "last_login_at" = now() WHERE "last_login_at" IS NULL;
