-- Media as a first-class table (28). Every uploaded or imported blob in the
-- instance lands here; roles stay on the parents that own them.
--
-- Deliberately WITHOUT foreign keys on the provenance columns (28 §2, ruled):
-- deleting a character must leave its media behind, still stamped with that
-- character's id, so an orphan stays groupable and attributable. Cascade would
-- turn those files into an unattributable pile on disk.
CREATE TABLE "media" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"user_id" integer NOT NULL,
	"character_id" integer,
	"persona_id" integer,
	"session_id" integer,
	"message_id" integer,
	"visibility" text NOT NULL DEFAULT 'scoped',
	"hash" text NOT NULL,
	"mime" text NOT NULL,
	"bytes" integer NOT NULL,
	"kind" text NOT NULL,
	"path" text NOT NULL,
	"filename" text,
	"width" integer,
	"height" integer,
	"parent_media_id" integer,
	"variant" text,
	"position" integer NOT NULL DEFAULT 0,
	"created_at" timestamp NOT NULL DEFAULT now()
);
--> statement-breakpoint
-- Dedupe is per-user, not per-instance. `variant` is part of the key so an
-- original and a derivative can share a hash without colliding.
CREATE UNIQUE INDEX "media_user_hash_variant_unique" ON "media" ("user_id","hash","variant");
--> statement-breakpoint
CREATE INDEX "media_character_idx" ON "media" ("character_id");
--> statement-breakpoint
CREATE INDEX "media_persona_idx" ON "media" ("persona_id");
--> statement-breakpoint
CREATE INDEX "media_session_idx" ON "media" ("session_id");
--> statement-breakpoint
CREATE INDEX "media_message_idx" ON "media" ("message_id");
--> statement-breakpoint
CREATE INDEX "media_parent_idx" ON "media" ("parent_media_id");
--> statement-breakpoint
-- Role pointers. Plain integers for the same reason the provenance columns are:
-- a real FK needs an ON DELETE action, and both are wrong here — RESTRICT would
-- block the cleanup tool, SET NULL is excluded by ruling.
ALTER TABLE "characters" ADD COLUMN "avatar_media_id" integer;
--> statement-breakpoint
ALTER TABLE "personas" ADD COLUMN "avatar_media_id" integer;
--> statement-breakpoint
-- On user_settings, not users: an uploaded background is a per-user display
-- preference and that is where the existing background columns live.
ALTER TABLE "user_settings" ADD COLUMN "background_media_id" integer;
