CREATE TABLE "cast_presences" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cast_presences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lorebook_binding_id" integer NOT NULL,
	"lorebook_id" integer NOT NULL,
	"branch_id" integer,
	"personal_position" integer NOT NULL,
	"from_year" integer NOT NULL,
	"from_month" integer,
	"from_day" integer,
	"until_year" integer,
	"until_month" integer,
	"until_day" integer,
	"note" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "cast_presences_from_check" CHECK (("cast_presences"."from_month" IS NOT NULL OR "cast_presences"."from_day" IS NULL)),
	CONSTRAINT "cast_presences_until_check" CHECK (("cast_presences"."until_month" IS NOT NULL OR "cast_presences"."until_day" IS NULL)),
	CONSTRAINT "cast_presences_until_year_check" CHECK (("cast_presences"."until_year" IS NOT NULL OR ("cast_presences"."until_month" IS NULL AND "cast_presences"."until_day" IS NULL)))
);
--> statement-breakpoint
ALTER TABLE "cast_amendments" ADD COLUMN "personal_position" integer;--> statement-breakpoint
ALTER TABLE "cast_presences" ADD CONSTRAINT "cast_presences_lorebook_binding_id_lorebook_bindings_id_fk" FOREIGN KEY ("lorebook_binding_id") REFERENCES "public"."lorebook_bindings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cast_presences" ADD CONSTRAINT "cast_presences_lorebook_id_lorebooks_id_fk" FOREIGN KEY ("lorebook_id") REFERENCES "public"."lorebooks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cast_presences" ADD CONSTRAINT "cast_presences_branch_id_lorebook_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."lorebook_branches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "cast_presences_member_idx" ON "cast_presences" USING btree ("lorebook_binding_id");--> statement-breakpoint
CREATE INDEX "cast_presences_book_idx" ON "cast_presences" USING btree ("lorebook_id");