CREATE TABLE "sprite_sets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sprite_sets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"character_id" integer NOT NULL,
	"name" text NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sprites" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sprites_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sprite_set_id" integer NOT NULL,
	"label" text NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"file_id" integer,
	"source" text DEFAULT 'upload' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "sprite_sets" ADD CONSTRAINT "sprite_sets_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sprites" ADD CONSTRAINT "sprites_sprite_set_id_sprite_sets_id_fk" FOREIGN KEY ("sprite_set_id") REFERENCES "public"."sprite_sets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sprites" ADD CONSTRAINT "sprites_file_id_files_id_fk" FOREIGN KEY ("file_id") REFERENCES "public"."files"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "sprite_sets_character_name_idx" ON "sprite_sets" USING btree ("character_id","name");--> statement-breakpoint
CREATE UNIQUE INDEX "sprite_sets_one_default_idx" ON "sprite_sets" USING btree ("character_id") WHERE "sprite_sets"."is_default";--> statement-breakpoint
CREATE UNIQUE INDEX "sprites_set_label_position_idx" ON "sprites" USING btree ("sprite_set_id","label","position");--> statement-breakpoint
CREATE INDEX "sprites_file_idx" ON "sprites" USING btree ("file_id");