-- Saved layout presets (PLAN 25 redesign, ruled 2026-08-30). Two parts:
--   1. session_layout_presets — the reusable layout DEFINITIONS, scoped to a
--      session type (genre_id). author_user_id NULL = a system/default preset
--      seeded per genre (seed_key matches it, never a numeric id — the seed
--      rule); set = a user-authored preset.
--   2. session_panel_layouts gains the user's ACTIVE selection: layout_preset_id
--      (which preset is applied; NULL = genre default; SET NULL on preset delete
--      so a user's row survives) and layout_settings (per-widget arbitrary config
--      the preset shouldn't carry, e.g. a background-image ref).
-- Pre-release, these squash.
CREATE TABLE "session_layout_presets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"seed_key" text UNIQUE,
	"genre_id" text NOT NULL,
	"author_user_id" integer REFERENCES "users"("id") ON DELETE CASCADE,
	"name" text NOT NULL,
	"layout" json NOT NULL DEFAULT '{}'::json,
	"created_at" timestamp NOT NULL DEFAULT now(),
	"updated_at" timestamp NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX "session_layout_presets_genre_idx" ON "session_layout_presets" ("genre_id");
--> statement-breakpoint
CREATE INDEX "session_layout_presets_author_idx" ON "session_layout_presets" ("author_user_id");
--> statement-breakpoint
ALTER TABLE "session_panel_layouts" ADD COLUMN "layout_preset_id" integer REFERENCES "session_layout_presets"("id") ON DELETE SET NULL;
--> statement-breakpoint
ALTER TABLE "session_panel_layouts" ADD COLUMN "layout_settings" json NOT NULL DEFAULT '{}'::json;
