CREATE TABLE "session_attribute_picks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_attribute_picks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" integer NOT NULL,
	"slot_id" text NOT NULL,
	"enabled" boolean NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "world_attributes" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "session_attribute_picks" ADD CONSTRAINT "session_attribute_picks_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "session_attribute_picks_session_slot_uq" ON "session_attribute_picks" USING btree ("session_id","slot_id");