CREATE TABLE "plugin_user_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plugin_user_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"plugin_id" text NOT NULL,
	"user_id" integer NOT NULL,
	"settings" json DEFAULT '{}'::json NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "plugin_user_settings" ADD CONSTRAINT "plugin_user_settings_plugin_id_plugins_plugin_id_fk" FOREIGN KEY ("plugin_id") REFERENCES "public"."plugins"("plugin_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "plugin_user_settings" ADD CONSTRAINT "plugin_user_settings_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "plugin_user_settings_plugin_user_unique" ON "plugin_user_settings" USING btree ("plugin_id","user_id");