-- ⚠ NO BACKFILL, AND THAT IS THE DECISION RATHER THAN AN OVERSIGHT.
--
-- Prompts are re-keyed from the spec to the (node type, slot) pool. Every
-- shipped row in the old table is a BUNDLE — the scene summarizer's single row
-- carries four fields belonging to four different node types — so there is no
-- row-to-row mapping to write even in principle: one row becomes four, in four
-- pools, with four new seed keys. The catalog now authors them in that shape
-- and the seed writes it on the next boot. Prod-to-prod carry-forward is a
-- separate problem, taken up later against real installs.
--
-- So do not "fix" this by adding an INSERT ... SELECT from a temp copy. There
-- is no column here that could hold the answer: which of a bundle's fields
-- belongs to which pool is a fact about the node type's declaration, which
-- lives in the registry and not in this table.
--
-- Safe to drop outright: nothing in the schema holds a foreign key INTO
-- pipeline_prompts — a config value stores the id as bare json, deliberately.
DROP TABLE IF EXISTS "pipeline_prompts" CASCADE;--> statement-breakpoint

CREATE TABLE "pipeline_prompts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	-- The pool, unversioned. Which fields a slot declares is a property of the
	-- VERSION and is checked at selection; fragmenting the pool on every
	-- @1 -> @2 would strand every prompt a user ever wrote.
	"node_type_id" text NOT NULL,
	-- The pool's second half. A type may declare more than one prompts slot
	-- with different field sets, and a prompt missing a field renders a blank —
	-- which reads as the model ignoring an instruction, not as a bad pick.
	"slot" text NOT NULL,
	-- Grouping only, never a permission, and `set null` rather than cascade:
	-- deleting a pipeline must not delete somebody's prompt.
	"created_for_spec_id" integer REFERENCES "pipeline_specs"("id") ON DELETE set null,
	-- Spec slugs whose shipped config starts on this row. A list because one
	-- pool now serves four summarize specs and the scene/history drafting
	-- prompt is ONE row belonging to two of them.
	"default_for_specs" json DEFAULT '[]'::json NOT NULL,
	-- ⚠ The spelling of these keys CHANGES (they used to embed the spec slug).
	-- seedPrompts.ts says it never may, because existing installs match rows
	-- they already wrote. That rule protects rows that exist; this statement
	-- leaves none, so the old spelling protects nothing. Deliberate, once —
	-- and the DROP above is half of the same decision. Separate them (a squash
	-- that keeps the CREATE and loses the DROP) and every install silently
	-- re-seeds 30 duplicates beside 20 orphans.
	"seed_key" text,
	"name" text NOT NULL,
	"is_immutable" boolean DEFAULT false NOT NULL,
	"fields" json DEFAULT '{}'::json NOT NULL,
	-- Text for a field the slot no longer declares. Left in `fields` it is
	-- invisible — the panel renders one box per DECLARED field — so a prompt
	-- someone spent an afternoon on becomes unfindable rather than merely
	-- unused. On the ROW so a duplicate carries it somewhere it fits again.
	"archived_fields" json DEFAULT '{}'::json NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint
-- Named rather than an inline `text UNIQUE`, which Postgres would auto-name
-- `..._seed_key_key`. Every other seeded table spells it `..._seed_key_unique`
-- (0092), and it is the name a person reads in the violation message when a
-- seed pass tries to write a key twice.
ALTER TABLE "pipeline_prompts" ADD CONSTRAINT "pipeline_prompts_seed_key_unique" UNIQUE("seed_key");--> statement-breakpoint
CREATE INDEX "pipeline_prompts_pool_idx" ON "pipeline_prompts" ("node_type_id","slot");--> statement-breakpoint
CREATE INDEX "pipeline_prompts_spec_idx" ON "pipeline_prompts" ("created_for_spec_id");--> statement-breakpoint
-- Was (spec_id, name). Two pipelines now share a pool, so `copyName` must
-- scope its taken-names query by pool too, or the second "Roleplay (copy)"
-- violates this index and surfaces as a raw constraint error.
CREATE UNIQUE INDEX "pipeline_prompts_pool_name_idx" ON "pipeline_prompts" ("node_type_id","slot","name");--> statement-breakpoint

-- The references that named the rows just dropped. Deleted rather than left
-- dangling: `resolvePromptFields` returns {} for a missing id, which pushes
-- nothing and lets the world floor take over — a selection that stores cleanly
-- and does nothing, on the very screen that shows it selected. `reconcileConfigs`
-- back-fills these from `refDefaults` on the next boot. A no-op on a fresh
-- install; it exists for the dev instances this is being built on.
DELETE FROM "pipeline_config_values"  WHERE "slot" = 'prompts';--> statement-breakpoint
DELETE FROM "pipeline_node_overrides" WHERE "slot" = 'prompts';--> statement-breakpoint

-- The engine becomes load-bearing, so it stops being nullable. NULL has always
-- MEANT core's engine (renderers.ts falls back to it) and core registers
-- exactly one renderer, so these UPDATEs state a fact rather than guess one.
-- They are a DDL prerequisite — the ALTER fails on an existing NULL — not a
-- data migration. No-ops on a fresh install.
UPDATE "pipeline_context_templates"  SET "engine" = 'core:template/handlebars@1' WHERE "engine" IS NULL;--> statement-breakpoint
UPDATE "pipeline_variable_templates" SET "engine" = 'core:template/handlebars@1' WHERE "engine" IS NULL;--> statement-breakpoint
ALTER TABLE "pipeline_context_templates"  ALTER COLUMN "engine" SET DEFAULT 'core:template/handlebars@1';--> statement-breakpoint
ALTER TABLE "pipeline_context_templates"  ALTER COLUMN "engine" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "pipeline_variable_templates" ALTER COLUMN "engine" SET DEFAULT 'core:template/handlebars@1';--> statement-breakpoint
ALTER TABLE "pipeline_variable_templates" ALTER COLUMN "engine" SET NOT NULL;--> statement-breakpoint

-- "Default" once per language, which is what a person expects. A Jinja
-- template can no longer be selected into a Handlebars slot — today it can, it
-- stores cleanly, and it renders as a prompt full of raw {% %} markup.
DROP INDEX IF EXISTS "pipeline_context_templates_node_type_name_idx";--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_context_templates_node_type_name_idx" ON "pipeline_context_templates" ("node_type_id","engine","name");--> statement-breakpoint
CREATE INDEX "pipeline_context_templates_pool_idx" ON "pipeline_context_templates" ("node_type_id","engine");--> statement-breakpoint
DROP INDEX IF EXISTS "pipeline_variable_templates_variable_name_idx";--> statement-breakpoint
CREATE UNIQUE INDEX "pipeline_variable_templates_variable_name_idx" ON "pipeline_variable_templates" ("variable_id","engine","name");--> statement-breakpoint

-- The slot's declared engine, denormalized onto a value row, read by nobody.
-- `engineFor` (named.ts:73) tests `decl.control === "template"`, a control
-- string `declsForSlot` never emits, so this column has been NULL on every row
-- ever written. The engine now travels on the template ROW and reaches the
-- world from there.
ALTER TABLE "pipeline_config_values" DROP COLUMN "engine";
