-- Split `media` into `files` (the logical entity and its metadata) and
-- `variants` (the bytes on disk).
--
-- One `media` row per representation could not answer the question a render
-- site actually asks. Building a payload needed the original row AND a second
-- query for its thumbnail row; a thumbnail had to leave all four provenance
-- columns NULL so `mediaFor(character)` would not return it; and visibility had
-- to be written twice to keep a derivative in step. All three were symptoms of
-- one table doing two jobs.
--
-- ⚠ THERE IS NO BACKFILL, AND THAT IS A RULING RATHER THAN AN OVERSIGHT.
--
-- Test instances are recreated; prod-to-prod migration of an existing library
-- is a later, separate problem and will need its own upgrade with its own file
-- walk — the blobs on disk have to be re-stamped as `original` variants and
-- given display pointers, which is a filesystem pass and not something an
-- INSERT ... SELECT can stand in for. Dropping is the clearest honest statement
-- of that: a fresh install gets correct tables, and an existing install is told
-- plainly that its rows are gone rather than being left with a half-translated
-- library whose images render as broken.
--
-- Note the consequence for a 0.5-era instance: the 0166 data upgrade still runs
-- and still populates `media` inside 0166's own transaction, and this migration
-- then drops the result. That is the same ruling, applied to the only path that
-- could have produced rows.
--
-- CASCADE because 0166's role pointers (`characters.avatar_media_id` and
-- friends) are plain integers by ruling and hold no constraint into this table;
-- CASCADE here only takes the table's own indexes with it. Those pointers
-- survive as dangling ids, which is exactly what the no-FK ruling asks for.
DROP TABLE IF EXISTS "media" CASCADE;
--> statement-breakpoint
CREATE TABLE "files" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"uuid" uuid NOT NULL DEFAULT (gen_random_uuid ()),
	-- Cache token. Bumped only when an EXISTING variant's bytes change, or when
	-- `display_variant_id` moves. Deriving a new variant does not bump; culling
	-- one does not bump. The handler never validates the value it is sent —
	-- rejecting a stale `r` turns a stale image into a broken one.
	"rev" integer NOT NULL DEFAULT 0,
	-- Which variant a bare `/media/{uuid}` serves. A stored pointer, because a
	-- request-time size comparison would change what an already-cached
	-- immutable URL serves without changing the URL. May point at the original:
	-- a web-safe upload IS its own display form and no second copy exists.
	--
	-- No FK, and not only by the ruling above: `variants.file_id` points back,
	-- so constraints in both directions would make the first insert of either
	-- row impossible without deferring one. `cullVariant` is what keeps this
	-- pointing at a row that exists.
	"display_variant_id" integer,
	-- Denormalised from the pointed-at variant, written in the same statement.
	-- A payload must be one row.
	"display_mime" text,
	"display_bytes" integer,
	-- Provenance, and deliberately WITHOUT foreign keys (28 §2, ruled):
	-- deleting a character must leave its files behind, still stamped with that
	-- character's id, so an orphan stays groupable and attributable. A VARIANT
	-- HAS NONE OF THESE, which is what makes it structurally unreachable by a
	-- provenance query and retires the old NULL-all-four trick.
	"user_id" integer NOT NULL,
	"character_id" integer,
	"persona_id" integer,
	"session_id" integer,
	"message_id" integer,
	"visibility" text NOT NULL DEFAULT 'scoped',
	"kind" text NOT NULL,
	-- sha256 of the ORIGINAL bytes. File identity; what a re-upload matches on.
	-- Each variant carries its own hash for its own bytes: identity and an ETag
	-- are different questions, so the duplication is deliberate.
	"hash" text NOT NULL,
	"filename" text,
	"width" integer,
	"height" integer,
	-- Non-null is the signal that a time dimension exists, which is what makes
	-- a silent flatten detectable. Milliseconds; the SDK's MediaRef is seconds.
	"duration_ms" integer,
	"position" integer NOT NULL DEFAULT 0,
	"meta" json,
	"created_at" timestamp NOT NULL DEFAULT now(),
	CONSTRAINT "files_visibility_check" CHECK ("visibility" IN ('scoped', 'private'))
);
--> statement-breakpoint
CREATE TABLE "variants" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"file_id" integer NOT NULL,
	"variant" text NOT NULL,
	"mime" text NOT NULL,
	"bytes" integer NOT NULL,
	"path" text NOT NULL,
	"hash" text NOT NULL,
	"width" integer,
	"height" integer,
	-- The bytes the user or the backend gave us. Irreplaceable once culled.
	"is_original" boolean NOT NULL DEFAULT false,
	-- Safe to cull because it can be re-derived. FALSE on an original, and FALSE
	-- on a converted display form — the display form is not a cache entry, it is
	-- the default representation, and the cache sweep must never touch it.
	--
	-- The invariant that keeps this from destroying user data is enforced in
	-- `cullVariant`, not in the UI: never cull the last surviving representation
	-- of a file, and never cull the display target without another
	-- full-fidelity row to re-point at. "Cull originals" and "cull cache" are
	-- two clicks in either order, and only a per-call check holds for both.
	"cache" boolean NOT NULL DEFAULT false,
	-- Only `full` rows compete for the display pointer. Without this, adding one
	-- lossy transcode later would make "serve the smallest" ship degraded images
	-- to everybody, and it would look like a caching bug.
	"fidelity" text NOT NULL DEFAULT 'full',
	"created_at" timestamp NOT NULL DEFAULT now(),
	-- The variant name reaches a path builder, so it is closed here as well as
	-- validated at the route. A CHECK rather than a pg enum so adding a value
	-- later is a data change; same reasoning as `widget_styles.source`.
	CONSTRAINT "variants_variant_check" CHECK ("variant" IN ('original', 'display', 'thumb')),
	CONSTRAINT "variants_fidelity_check" CHECK ("fidelity" IN ('full', 'reduced'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX "files_uuid_unique" ON "files" ("uuid");
--> statement-breakpoint
-- Dedupe is per-user, not per-instance: instance-wide would make one user's
-- upload observable to another by hash timing. No `variant` in the key any
-- more — a variant is not a file.
CREATE UNIQUE INDEX "files_user_hash_unique" ON "files" ("user_id","hash");
--> statement-breakpoint
CREATE INDEX "files_character_idx" ON "files" ("character_id");
--> statement-breakpoint
CREATE INDEX "files_persona_idx" ON "files" ("persona_id");
--> statement-breakpoint
CREATE INDEX "files_session_idx" ON "files" ("session_id");
--> statement-breakpoint
CREATE INDEX "files_message_idx" ON "files" ("message_id");
--> statement-breakpoint
-- One row per (file, variant). This is the cross-process backstop that makes
-- concurrent derivation safe; the in-process single-flight map is what stops
-- both requests paying for the encode in the first place.
CREATE UNIQUE INDEX "variants_file_variant_unique" ON "variants" ("file_id","variant");
--> statement-breakpoint
CREATE INDEX "variants_file_idx" ON "variants" ("file_id");
--> statement-breakpoint
CREATE INDEX "variants_cache_idx" ON "variants" ("cache");
--> statement-breakpoint
-- Off means never keep a derived form on disk. The display form is not a
-- derived form for this purpose and is never culled by the cache sweep.
ALTER TABLE "user_settings" ADD COLUMN "derived_media_cache_enabled" boolean NOT NULL DEFAULT true;
