CREATE TABLE "admin_logbook" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_logbook_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"actor_user_id" integer,
	"actor_name" text NOT NULL,
	"event" text NOT NULL,
	"object_type" text NOT NULL,
	"object_id" text,
	"object_label" text DEFAULT '' NOT NULL,
	"action" text NOT NULL,
	"summary" text NOT NULL,
	"changes" jsonb DEFAULT '[]'::jsonb NOT NULL,
	CONSTRAINT "admin_logbook_action_check" CHECK ("admin_logbook"."action" IN ('add', 'change', 'delete', 'other'))
);
--> statement-breakpoint
CREATE INDEX "admin_logbook_created_idx" ON "admin_logbook" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "admin_logbook_object_idx" ON "admin_logbook" USING btree ("object_type","object_id");--> statement-breakpoint
CREATE INDEX "admin_logbook_actor_idx" ON "admin_logbook" USING btree ("actor_user_id");