CREATE TABLE "notifications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"kind" text NOT NULL,
	"regarding" text NOT NULL,
	"level" text NOT NULL,
	"href" text NOT NULL,
	"vars" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"raised_at" timestamp DEFAULT now() NOT NULL,
	"last_raised_at" timestamp DEFAULT now() NOT NULL,
	"read_at" timestamp,
	"cleared_at" timestamp,
	"cleared_how" text,
	CONSTRAINT "notifications_level_check" CHECK ("notifications"."level" IN ('error', 'attention', 'info')),
	CONSTRAINT "notifications_cleared_how_check" CHECK ("notifications"."cleared_how" IS NULL OR "notifications"."cleared_how" IN ('viewed', 'acted', 'superseded', 'dismissed', 'lapsed'))
);
--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "notifications_open_regarding_idx" ON "notifications" USING btree ("user_id","regarding") WHERE "cleared_at" IS NULL;--> statement-breakpoint
CREATE INDEX "notifications_user_idx" ON "notifications" USING btree ("user_id","cleared_at","last_raised_at");--> statement-breakpoint
CREATE INDEX "notifications_cleared_idx" ON "notifications" USING btree ("cleared_at");