-- 0190_lorebook_integrity — lorebook-area FK indexes, clock/fork CHECKs, and
-- the attribute rows' branch FK (lane W3-schema, 2026-09-28).
--
-- HAND-ADDED REPAIR ahead of the generated DDL below. Every statement is a
-- no-op on well-formed data; each exists so a CHECK or FK cannot fail the
-- migration (and with it every boot) on a row written before it existed.
--
-- 1. Stat rows pointing at a branch that no longer exists. Deleted, not
--    re-filed to main: a branch-only fact on main reads on every line, and the
--    new FK's ON DELETE CASCADE is what would have removed them anyway.
DELETE FROM "attribute_values" v WHERE v."branch_id" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "lorebook_branches" b WHERE b."id" = v."branch_id");
--> statement-breakpoint
DELETE FROM "attribute_configs" c WHERE c."branch_id" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "lorebook_branches" b WHERE b."id" = c."branch_id");
--> statement-breakpoint
-- 2. Story clocks normalised to what `clockColumns` (state/storyTime.ts)
--    stores: no year is no clock; a day needs a month; an hour outside 0-23 is
--    dropped with its minute; a minute needs an hour, and one out of range is
--    0 (the minute `clockColumns` stores for an hour given alone).
UPDATE "lorebooks" SET "story_clock_month" = NULL, "story_clock_day" = NULL, "story_clock_hour" = NULL, "story_clock_minute" = NULL WHERE "story_clock_year" IS NULL AND ("story_clock_month" IS NOT NULL OR "story_clock_day" IS NOT NULL OR "story_clock_hour" IS NOT NULL OR "story_clock_minute" IS NOT NULL);
--> statement-breakpoint
UPDATE "lorebooks" SET "story_clock_day" = NULL WHERE "story_clock_month" IS NULL AND "story_clock_day" IS NOT NULL;
--> statement-breakpoint
UPDATE "lorebooks" SET "story_clock_hour" = NULL, "story_clock_minute" = NULL WHERE "story_clock_hour" IS NOT NULL AND "story_clock_hour" NOT BETWEEN 0 AND 23;
--> statement-breakpoint
UPDATE "lorebooks" SET "story_clock_minute" = NULL WHERE "story_clock_minute" IS NOT NULL AND "story_clock_hour" IS NULL;
--> statement-breakpoint
UPDATE "lorebooks" SET "story_clock_minute" = 0 WHERE "story_clock_minute" IS NOT NULL AND "story_clock_minute" NOT BETWEEN 0 AND 59;
--> statement-breakpoint
UPDATE "lorebook_branches" SET "story_clock_month" = NULL, "story_clock_day" = NULL, "story_clock_hour" = NULL, "story_clock_minute" = NULL WHERE "story_clock_year" IS NULL AND ("story_clock_month" IS NOT NULL OR "story_clock_day" IS NOT NULL OR "story_clock_hour" IS NOT NULL OR "story_clock_minute" IS NOT NULL);
--> statement-breakpoint
UPDATE "lorebook_branches" SET "story_clock_day" = NULL WHERE "story_clock_month" IS NULL AND "story_clock_day" IS NOT NULL;
--> statement-breakpoint
UPDATE "lorebook_branches" SET "story_clock_hour" = NULL, "story_clock_minute" = NULL WHERE "story_clock_hour" IS NOT NULL AND "story_clock_hour" NOT BETWEEN 0 AND 23;
--> statement-breakpoint
UPDATE "lorebook_branches" SET "story_clock_minute" = NULL WHERE "story_clock_minute" IS NOT NULL AND "story_clock_hour" IS NULL;
--> statement-breakpoint
UPDATE "lorebook_branches" SET "story_clock_minute" = 0 WHERE "story_clock_minute" IS NOT NULL AND "story_clock_minute" NOT BETWEEN 0 AND 59;
--> statement-breakpoint
UPDATE "sessions" SET "story_clock_month" = NULL, "story_clock_day" = NULL, "story_clock_hour" = NULL, "story_clock_minute" = NULL WHERE "story_clock_year" IS NULL AND ("story_clock_month" IS NOT NULL OR "story_clock_day" IS NOT NULL OR "story_clock_hour" IS NOT NULL OR "story_clock_minute" IS NOT NULL);
--> statement-breakpoint
UPDATE "sessions" SET "story_clock_day" = NULL WHERE "story_clock_month" IS NULL AND "story_clock_day" IS NOT NULL;
--> statement-breakpoint
UPDATE "sessions" SET "story_clock_hour" = NULL, "story_clock_minute" = NULL WHERE "story_clock_hour" IS NOT NULL AND "story_clock_hour" NOT BETWEEN 0 AND 23;
--> statement-breakpoint
UPDATE "sessions" SET "story_clock_minute" = NULL WHERE "story_clock_minute" IS NOT NULL AND "story_clock_hour" IS NULL;
--> statement-breakpoint
UPDATE "sessions" SET "story_clock_minute" = 0 WHERE "story_clock_minute" IS NOT NULL AND "story_clock_minute" NOT BETWEEN 0 AND 59;
--> statement-breakpoint
-- 3. Fork dates narrowed left to right, all-or-nothing on the year.
UPDATE "lorebook_branches" SET "fork_month" = NULL, "fork_day" = NULL WHERE "fork_year" IS NULL AND ("fork_month" IS NOT NULL OR "fork_day" IS NOT NULL);
--> statement-breakpoint
UPDATE "lorebook_branches" SET "fork_day" = NULL WHERE "fork_month" IS NULL AND "fork_day" IS NOT NULL;
--> statement-breakpoint
-- Generated by drizzle-kit from here down.
ALTER TABLE "attribute_configs" ADD CONSTRAINT "attribute_configs_branch_id_lorebook_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."lorebook_branches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attribute_values" ADD CONSTRAINT "attribute_values_branch_id_lorebook_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "public"."lorebook_branches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "attribute_configs_branch_id_idx" ON "attribute_configs" USING btree ("branch_id") WHERE "attribute_configs"."branch_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "attribute_values_branch_id_idx" ON "attribute_values" USING btree ("branch_id") WHERE "attribute_values"."branch_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "cast_amendments_branch_id_idx" ON "cast_amendments" USING btree ("branch_id") WHERE "cast_amendments"."branch_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "cast_amendments_history_entry_id_idx" ON "cast_amendments" USING btree ("history_entry_id") WHERE "cast_amendments"."history_entry_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "cast_presences_branch_id_idx" ON "cast_presences" USING btree ("branch_id") WHERE "cast_presences"."branch_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "entry_amendments_branch_id_idx" ON "entry_amendments" USING btree ("branch_id") WHERE "entry_amendments"."branch_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "entry_amendments_history_entry_id_idx" ON "entry_amendments" USING btree ("history_entry_id") WHERE "entry_amendments"."history_entry_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "lorebook_entries_branch_id_idx" ON "lorebook_entries" USING btree ("branch_id") WHERE "lorebook_entries"."branch_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "lorebook_entries_anchor_entry_id_idx" ON "lorebook_entries" USING btree ("anchor_entry_id") WHERE "lorebook_entries"."anchor_entry_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "lorebook_entries_anchor_binding_id_idx" ON "lorebook_entries" USING btree ("anchor_binding_id") WHERE "lorebook_entries"."anchor_binding_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "narrative_relationships_branch_id_idx" ON "narrative_relationships" USING btree ("branch_id") WHERE "narrative_relationships"."branch_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "scenes_branch_id_idx" ON "scenes" USING btree ("branch_id") WHERE "scenes"."branch_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "sessions_lorebook_branch_id_idx" ON "sessions" USING btree ("lorebook_branch_id") WHERE "sessions"."lorebook_branch_id" IS NOT NULL;--> statement-breakpoint
ALTER TABLE "lorebook_branches" ADD CONSTRAINT "lorebook_branches_fork_check" CHECK (("lorebook_branches"."fork_month" IS NOT NULL OR "lorebook_branches"."fork_day" IS NULL));--> statement-breakpoint
ALTER TABLE "lorebook_branches" ADD CONSTRAINT "lorebook_branches_fork_year_check" CHECK (("lorebook_branches"."fork_year" IS NOT NULL OR ("lorebook_branches"."fork_month" IS NULL AND "lorebook_branches"."fork_day" IS NULL)));--> statement-breakpoint
ALTER TABLE "lorebook_branches" ADD CONSTRAINT "lorebook_branches_story_clock_day_check" CHECK (("lorebook_branches"."story_clock_month" IS NOT NULL OR "lorebook_branches"."story_clock_day" IS NULL));--> statement-breakpoint
ALTER TABLE "lorebook_branches" ADD CONSTRAINT "lorebook_branches_story_clock_year_check" CHECK (("lorebook_branches"."story_clock_year" IS NOT NULL OR ("lorebook_branches"."story_clock_month" IS NULL AND "lorebook_branches"."story_clock_hour" IS NULL)));--> statement-breakpoint
ALTER TABLE "lorebook_branches" ADD CONSTRAINT "lorebook_branches_story_clock_hour_check" CHECK (("lorebook_branches"."story_clock_hour" IS NULL OR "lorebook_branches"."story_clock_hour" BETWEEN 0 AND 23));--> statement-breakpoint
ALTER TABLE "lorebook_branches" ADD CONSTRAINT "lorebook_branches_story_clock_minute_check" CHECK (("lorebook_branches"."story_clock_minute" IS NULL OR ("lorebook_branches"."story_clock_hour" IS NOT NULL AND "lorebook_branches"."story_clock_minute" BETWEEN 0 AND 59)));--> statement-breakpoint
ALTER TABLE "lorebooks" ADD CONSTRAINT "lorebooks_story_clock_day_check" CHECK (("lorebooks"."story_clock_month" IS NOT NULL OR "lorebooks"."story_clock_day" IS NULL));--> statement-breakpoint
ALTER TABLE "lorebooks" ADD CONSTRAINT "lorebooks_story_clock_year_check" CHECK (("lorebooks"."story_clock_year" IS NOT NULL OR ("lorebooks"."story_clock_month" IS NULL AND "lorebooks"."story_clock_hour" IS NULL)));--> statement-breakpoint
ALTER TABLE "lorebooks" ADD CONSTRAINT "lorebooks_story_clock_hour_check" CHECK (("lorebooks"."story_clock_hour" IS NULL OR "lorebooks"."story_clock_hour" BETWEEN 0 AND 23));--> statement-breakpoint
ALTER TABLE "lorebooks" ADD CONSTRAINT "lorebooks_story_clock_minute_check" CHECK (("lorebooks"."story_clock_minute" IS NULL OR ("lorebooks"."story_clock_hour" IS NOT NULL AND "lorebooks"."story_clock_minute" BETWEEN 0 AND 59)));--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_story_clock_day_check" CHECK (("sessions"."story_clock_month" IS NOT NULL OR "sessions"."story_clock_day" IS NULL));--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_story_clock_year_check" CHECK (("sessions"."story_clock_year" IS NOT NULL OR ("sessions"."story_clock_month" IS NULL AND "sessions"."story_clock_hour" IS NULL)));--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_story_clock_hour_check" CHECK (("sessions"."story_clock_hour" IS NULL OR "sessions"."story_clock_hour" BETWEEN 0 AND 23));--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_story_clock_minute_check" CHECK (("sessions"."story_clock_minute" IS NULL OR ("sessions"."story_clock_hour" IS NOT NULL AND "sessions"."story_clock_minute" BETWEEN 0 AND 59)));