/**
 * A sampling config plus a prompt becomes an `ImageGenRequest`.
 *
 * Shared by the two things that render an image — the manual "Test Generation"
 * panel in the connection form, and the pipeline's `generate-image` provider —
 * so that a picture generated from the sidebar and one generated by a spec are
 * asked for in exactly the same terms. The first version of this had the socket
 * handler assemble its own parameters inline, which is precisely how the two
 * paths start disagreeing about what "steps" means.
 */

import { resolveSampling } from "$lib/server/utils/resolveSampling"
import type { ImageGenRequest } from "$lib/shared/imageGen/types"

export interface BuildImageRequestArgs {
	prompt: string
	negativePrompt?: string
	/** The stored row, or nothing — in which case the backend keeps its own defaults. */
	sampling?: {
		shape?: string | null
		values?: Record<string, unknown> | null
		enabled?: string[] | null
	} | null
	/** The connection, for its checkpoint. */
	connection?: { model?: string | null } | null
	/**
	 * Per-run values that beat the config — what a review gate's edited form
	 * submits, or what a caller states outright. Undefined entries are ignored
	 * rather than treated as "unset it", so a partial override is partial.
	 */
	overrides?: Partial<ImageGenRequest>
}

export function buildImageRequest({
	prompt,
	negativePrompt,
	sampling,
	connection,
	overrides
}: BuildImageRequestArgs): ImageGenRequest {
	// Already filtered to what is switched on, with declared defaults applied.
	const v = resolveSampling(sampling)

	const req: ImageGenRequest = {
		prompt,
		...(negativePrompt ? { negativePrompt } : {}),
		...num("width", v.width),
		...num("height", v.height),
		...num("steps", v.steps),
		...num("cfg", v.cfg),
		...num("seed", v.seed),
		...num("batch", v.batch),
		...num("clipSkip", v.clipSkip),
		...num("denoise", v.denoise),
		...str("sampler", v.sampler),
		...str("scheduler", v.scheduler),
		// The checkpoint belongs to the connection, not to the sampling config: a
		// config is meant to be pointed at any backend, and a filename that only
		// exists on one of them is the opposite of that.
		...(connection?.model ? { model: connection.model } : {})
	}

	if (!overrides) return req
	const out = req as unknown as Record<string, unknown>
	for (const [key, value] of Object.entries(overrides))
		if (value !== undefined) out[key] = value
	return req
}

/** Present only when it really is a finite number — a stray "" must not become NaN. */
const num = (key: string, value: unknown): Record<string, number> => {
	const n = typeof value === "number" ? value : Number(value)
	return value === undefined || value === null || !Number.isFinite(n)
		? {}
		: { [key]: n }
}

const str = (key: string, value: unknown): Record<string, string> =>
	typeof value === "string" && value.trim() ? { [key]: value.trim() } : {}
