/**
 * Test-only: an attic holding empty 0.5.3 tables, for a suite that writes the
 * legacy rows a 0.5.3 install would have and runs the code that reads them.
 *
 * The tables are built from `drizzle/meta/0093_snapshot.json` — the snapshot of
 * the last 0.5.3 migration, which can never change — with their 0.5.3 column
 * types, NOT NULLs, defaults and identity ids, so a suite can insert a partial
 * row through the typed attic declarations (`./tables`) and have the rest
 * filled the way 0.5.3 filled it. Keys and indexes are left out, as the real
 * attic (made by `CREATE TABLE … AS`) leaves them out.
 */
import fs from "node:fs"
import path from "node:path"
import { sql } from "drizzle-orm"
import { ATTIC_SCHEMA } from "./index"

interface SnapshotColumn {
	name: string
	type: string
	notNull: boolean
	default?: unknown
	identity?: unknown
}

let snapshot: Record<string, { columns: Record<string, SnapshotColumn> }> | null = null

function tables() {
	snapshot ??= JSON.parse(
		fs.readFileSync(
			path.resolve(process.cwd(), "drizzle/meta/0093_snapshot.json"),
			"utf8"
		)
	).tables
	return snapshot!
}

const defaultSql = (v: unknown): string =>
	typeof v === "string" ? v : typeof v === "boolean" || typeof v === "number" ? String(v) : `'${JSON.stringify(v)}'`

/** The 0.5.3 DDL for one table, in the attic. */
export function atticTableDdl(table: string): string {
	const t = tables()[`public.${table}`]
	if (!t) throw new Error(`0.5.3 had no table "${table}"`)
	const cols = Object.values(t.columns).map((c) => {
		const parts = [`"${c.name}"`, c.type]
		if (c.identity) parts.push("GENERATED BY DEFAULT AS IDENTITY")
		else if (c.default !== undefined) parts.push(`DEFAULT ${defaultSql(c.default)}`)
		if (c.notNull) parts.push("NOT NULL")
		return parts.join(" ")
	})
	return `CREATE TABLE "${ATTIC_SCHEMA}"."${table}" (${cols.join(", ")})`
}

/** Create the attic with these 0.5.3 tables, empty. */
export async function buildTestAttic(db: Db, names: string[]): Promise<void> {
	await db.execute(sql.raw(`CREATE SCHEMA IF NOT EXISTS "${ATTIC_SCHEMA}"`))
	for (const name of names) await db.execute(sql.raw(atticTableDdl(name)))
}

/** The legacy config tables the wiring reads, and the rows that select them. */
export const WIRING_TABLES = [
	"context_configs",
	"prompt_configs",
	"narrator_prompt_configs",
	"world_summarize_configs",
	"character_summarize_configs",
	"scene_summarize_configs",
	"graph_build_configs",
	"system_settings",
	"user_settings",
	"chats"
]
