/**
 * Pre-migration backups (see ./backup.ts).
 *
 * The properties worth pinning: a backup is taken exactly when a migration is
 * about to change something, never otherwise; a failed backup stops the
 * migration rather than letting it proceed unprotected; and what lands on disk
 * is a real, restorable database rather than a truncated file.
 */
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest"
import fs from "fs"
import os from "os"
import path from "path"
import { PGlite } from "@electric-sql/pglite"
import { drizzle } from "drizzle-orm/pglite"
import {
	backupBeforeMigrations,
	backupDatabase,
	hasPendingMigrations
} from "./backup"

let dataDir: string
let folder: string
let client: PGlite
let db: any

beforeEach(async () => {
	dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "sp-backup-data-"))
	folder = fs.mkdtempSync(path.join(os.tmpdir(), "sp-backup-mig-"))
	fs.writeFileSync(
		path.join(folder, "0000_first.sql"),
		`CREATE TABLE "widget" ("id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "legacy" text);`
	)
	fs.mkdirSync(path.join(folder, "meta"), { recursive: true })
	fs.writeFileSync(
		path.join(folder, "meta/_journal.json"),
		JSON.stringify({
			version: "7",
			dialect: "postgresql",
			entries: [
				{
					idx: 0,
					version: "7",
					when: 1000,
					tag: "0000_first",
					breakpoints: true
				}
			]
		})
	)
	client = new PGlite()
	db = drizzle(client)
}, 60_000)

afterEach(() => {
	fs.rmSync(dataDir, { recursive: true, force: true })
	fs.rmSync(folder, { recursive: true, force: true })
})

async function markApplied() {
	await client.query(`CREATE SCHEMA IF NOT EXISTS drizzle`)
	await client.query(`CREATE TABLE IF NOT EXISTS drizzle.__drizzle_migrations
		(id SERIAL PRIMARY KEY, hash text NOT NULL, created_at bigint)`)
	await client.query(
		`INSERT INTO drizzle.__drizzle_migrations (hash, created_at) VALUES ('x', 1000)`
	)
}

function backupsIn(): string[] {
	const dir = path.join(dataDir, "backups")
	return fs.existsSync(dir) ? fs.readdirSync(dir) : []
}

describe("when a backup is taken", () => {
	test("before a pending migration on an existing install", async () => {
		await markApplied()
		await client.query(`INSERT INTO drizzle.__drizzle_migrations (hash, created_at)
			VALUES ('y', 999)`) // older row; 1000 is still the high-water mark
		// Pretend a newer migration exists by rewinding what's applied.
		await client.query(
			`DELETE FROM drizzle.__drizzle_migrations WHERE created_at = 1000`
		)

		const res = await backupBeforeMigrations(db, {
			dataDir,
			migrationsFolder: folder,
			label: "0.5.0",
			isFreshInstall: false
		})

		expect(res).not.toBeNull()
		expect(backupsIn()).toHaveLength(1)
		expect(backupsIn()[0]).toMatch(/^serene-pub-0\.5\.0-.*\.tgz$/)
	})

	test("not on a fresh install — there is no user data to protect", async () => {
		const res = await backupBeforeMigrations(db, {
			dataDir,
			migrationsFolder: folder,
			label: "unknown",
			isFreshInstall: true
		})
		expect(res).toBeNull()
		expect(backupsIn()).toHaveLength(0)
	})

	test("not when every migration is already applied", async () => {
		await markApplied()
		// An unchanged instance must not pay a multi-megabyte write per boot.
		expect(await hasPendingMigrations(db, folder)).toBe(false)
		const res = await backupBeforeMigrations(db, {
			dataDir,
			migrationsFolder: folder,
			label: "0.6.0",
			isFreshInstall: false
		})
		expect(res).toBeNull()
		expect(backupsIn()).toHaveLength(0)
	})

	test("treats a database with no migrations table as pending", async () => {
		expect(await hasPendingMigrations(db, folder)).toBe(true)
	})
})

describe("what lands on disk", () => {
	test("is a non-trivial gzip that restores to a working database", async () => {
		await client.query(`CREATE TABLE keeper (id int, note text)`)
		await client.query(`INSERT INTO keeper VALUES (1, 'survives')`)

		const res = await backupDatabase(db, { dataDir, label: "0.5.0" })
		const stat = fs.statSync(res.path)
		expect(stat.size).toBeGreaterThan(1024)
		expect(fs.readFileSync(res.path).subarray(0, 2)).toEqual(
			Buffer.from([0x1f, 0x8b]) // gzip magic
		)

		// The real assertion: it round-trips.
		const restored = await PGlite.create({
			loadDataDir: new Blob([fs.readFileSync(res.path)])
		})
		const rows = await restored.query(`SELECT note FROM keeper`)
		expect((rows.rows[0] as any).note).toBe("survives")
		await restored.close()
	}, 60_000)

	test("leaves no .partial file behind on success", async () => {
		await backupDatabase(db, { dataDir, label: "0.5.0" })
		expect(backupsIn().some((f) => f.endsWith(".partial"))).toBe(false)
	})

	test("never culls existing backups", async () => {
		await backupDatabase(db, { dataDir, label: "0.5.0" })
		await backupDatabase(db, { dataDir, label: "0.5.1" })
		await backupDatabase(db, { dataDir, label: "0.5.2" })
		// Retention is a user-facing control, not something startup decides.
		expect(backupsIn()).toHaveLength(3)
	})
})

describe("failure policy", () => {
	test("a failed backup aborts the migration rather than proceeding", async () => {
		const broken = {
			...db,
			$client: {
				dumpDataDir: async () => {
					throw new Error("disk full")
				}
			},
			execute: db.execute.bind(db)
		}
		// Proceeding here is precisely what the backup exists to prevent.
		await expect(
			backupBeforeMigrations(broken, {
				dataDir,
				migrationsFolder: folder,
				label: "0.5.0",
				isFreshInstall: false
			})
		).rejects.toThrow(/disk full/)
	})

	test("refuses a driver that cannot dump, rather than silently skipping", async () => {
		await expect(
			backupDatabase({ $client: {} } as any, { dataDir, label: "x" })
		).rejects.toThrow(/cannot produce a backup/i)
	})
})
