/**
 * Migration 0141's DATA STEP, against a hand-made pre-state.
 *
 * ## Why not `createTestDb`
 *
 * That helper applies every migration in one pass, so there is no moment at
 * which a row can be inserted in the pre-0141 shape — and the data step's whole
 * job is what happens to rows that were already there. So this file builds the
 * two tables as they stood at 0140, puts the awkward rows in, and then executes
 * `drizzle/0141_layout_presets_v2.sql` itself, statement by statement, exactly
 * as the migrator would. The SQL under test is the shipped file, read from
 * disk: an edit to it that broke this would break a real upgrade too.
 *
 * (That both migrations APPLY on a fresh database is proven by every other
 * integration suite in the repo, all of which build one through the migrator.)
 */
import { PGlite } from "@electric-sql/pglite"
import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import { beforeAll, describe, expect, test } from "vitest"

/** The pre-0141 shape of the two tables the migration touches. */
const PRE_STATE = `
	CREATE TABLE "session_layout_presets" (
		"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		"seed_key" text UNIQUE,
		"genre_id" text NOT NULL,
		"author_user_id" integer,
		"name" text NOT NULL,
		"layout" json DEFAULT '{}'::json NOT NULL,
		"created_at" timestamp DEFAULT now() NOT NULL,
		"updated_at" timestamp DEFAULT now() NOT NULL
	);
	CREATE TABLE "session_panel_layouts" (
		"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		"layout" json DEFAULT '{}'::json NOT NULL
	);
`

type Row = Record<string, any>

let db: PGlite
let rows: Row[]

const byName = (name: string) => rows.find((r) => r.name === name)!

beforeAll(async () => {
	db = new PGlite()
	await db.exec(PRE_STATE)

	// The rows an upgrading install can actually hold.
	await db.exec(`
		INSERT INTO "session_layout_presets" ("seed_key", "genre_id", "author_user_id", "name", "layout") VALUES
			-- The genre's seeded default, under the canonical key.
			('layout:core:genre/chat:default', 'core:genre/chat', NULL, 'Default', '{"zoneLayout":{}}'),
			-- A row left by an older key scheme, in the SAME genre. Both would
			-- take the slug 'default' under a naive derivation, and the partial
			-- unique index would then refuse the migration.
			('layout:core:genre/chat', 'core:genre/chat', NULL, 'Stale', '{}'),
			-- Two of one person's own, one of them named so the slug needs
			-- every character class squeezed out of it.
			(NULL, 'core:genre/chat', 5, 'My Layout!', '{"widgetGrid":{}}'),
			(NULL, 'core:genre/chat', 5, 'My  Layout!', '{}'),
			-- The row the shape says cannot exist: authored AND seed-keyed.
			('layout:core:genre/adventure:default', 'core:genre/adventure', 5, 'Impossible', '{}'),
			-- …and its mirror: no key, no author.
			(NULL, 'core:genre/adventure', NULL, 'Orphan', '{}')
	`)

	const sql = readFileSync(
		resolve("drizzle/0141_layout_presets_v2.sql"),
		"utf8"
	)
	for (const statement of sql.split("--> statement-breakpoint")) {
		const trimmed = statement.trim()
		if (trimmed) await db.exec(trimmed)
	}

	rows = (
		await db.query<Row>(`SELECT * FROM "session_layout_presets" ORDER BY id`)
	).rows
}, 60_000)

describe("0141's data step", () => {
	test("derives origin from the seed key", () => {
		expect(byName("Default").origin).toBe("core")
		expect(byName("Stale").origin).toBe("core")
		expect(byName("My Layout!").origin).toBe("user")
		// Authored wins: the author is the fact somebody made, the key is the
		// reconciler's and is dropped.
		expect(byName("Impossible").origin).toBe("user")
		expect(byName("Impossible").seed_key).toBeNull()
		// Neither: kept, and kept VISIBLE, as a core row under a synthesized
		// non-canonical key.
		expect(byName("Orphan").origin).toBe("core")
		expect(byName("Orphan").seed_key).toMatch(
			/^layout:core:genre\/adventure:legacy-\d+$/
		)
	})

	test("gives the genre's own row the reserved slug and nobody else", () => {
		expect(byName("Default").slug).toBe("default")
		expect(byName("Stale").slug).toBe(`legacy-${byName("Stale").id}`)
		expect(byName("Orphan").slug).toBe(`legacy-${byName("Orphan").id}`)
	})

	test("slugs a person's row from its name, uniquely per author and genre", () => {
		const a = byName("My Layout!")
		const b = byName("My  Layout!")
		expect(a.slug).toBe(`my-layout--${a.id}`)
		expect(b.slug).toBe(`my-layout--${b.id}`)
		expect(a.slug).not.toBe(b.slug)
	})

	test("derives visibility: shipped is shared, a person's is private", () => {
		expect(byName("Default").visibility).toBe("shared")
		expect(byName("Stale").visibility).toBe("shared")
		expect(byName("My Layout!").visibility).toBe("private")
		expect(byName("Impossible").visibility).toBe("private")
	})

	test("leaves the legacy blob exactly as it was", () => {
		expect(byName("Default").layout).toEqual({ zoneLayout: {} })
		expect(byName("My Layout!").layout).toEqual({ widgetGrid: {} })
		// …and adds no document: nothing invents one from a legacy blob.
		expect(byName("Default").document).toBeNull()
	})

	test("the constraints it was ordered before are live afterwards", async () => {
		// The origin triple.
		await expect(
			db.exec(`INSERT INTO "session_layout_presets"
				("seed_key", "genre_id", "author_user_id", "origin", "slug", "name")
				VALUES (NULL, 'core:genre/chat', NULL, 'user', 'x', 'No author')`)
		).rejects.toThrow()
		// One slug per author per genre.
		await expect(
			db.exec(`INSERT INTO "session_layout_presets"
				("seed_key", "genre_id", "author_user_id", "origin", "slug", "name", "visibility")
				VALUES (NULL, 'core:genre/chat', 5, 'user', '${byName("My Layout!").slug}', 'Dup', 'private')`)
		).rejects.toThrow()
	})
})
