name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-alpha'

jobs:
  build-and-release:
    strategy:
      matrix:
        include:
          - target: linux-x64
            os: ubuntu-latest
          # - target: linux-arm64
          #   os: ubuntu-latest
          # - target: linux-arm
          #   os: ubuntu-latest
          # - target: linux-ppc64
          #   os: ubuntu-latest
          - target: macos-x64
            os: macos-latest
          # - target: macos-arm64
          #   os: macos-latest
          - target: windows-x64
            os: windows-latest
          # - target: windows-arm64
          #   os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean node_modules
        shell: bash
        run: |
          if [ -d node_modules ]; then rm -rf node_modules; fi
          if [ -d node_modules ]; then rmdir /s /q node_modules; fi

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Clean build and dist directories
        shell: bash
        run: |
          if [ -d build ]; then rm -rf build; fi
          if [ -d dist ]; then rm -rf dist; fi

      - name: Print architecture info
        run: |
          echo "Node arch: $(node -p 'process.arch')"
          echo "Node platform: $(node -p 'process.platform')"
          uname -a
          uname -m
          sysctl -n machdep.cpu.brand_string || true

      - name: Build app
        run: npm run build

      - name: Bundle for ${{ matrix.target }}
        run: node scripts/bundle-dist.js ${{ matrix.target }}

      - name: Zip dist directory
        run: |
          cd dist
          zip -r "../serene-pub-${{ github.ref_name }}-${{ matrix.target }}.zip" "serene-pub-*-${{ matrix.target }}"
          cd ..

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: serene-pub-*.zip
          prerelease: ${{ contains(github.ref, 'alpha') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

